(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const weekKey=d=>{const x=new Date((d||today())+'T00:00:00');const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x.toISOString().slice(0,10)};
window.renderNeoAdoptionPTM=function(area,ctx){
 const {records:r,call,refresh,status}=ctx;
 const students=(r.students||[]).filter(x=>(x.status||'Active')!=='Withdrawn');
 const teachers=r.teacher_access||[];
 const assignments=r.adoption_assignments||[],calls=r.adoption_calls||[],actions=r.adoption_actions||[],ptms=r.ptm_sessions||[];
 const currentWeek=weekKey(),activeAssignments=assignments.filter(x=>x.status==='Active');
 const assignedIds=new Set(activeAssignments.map(x=>String(x.student_id)));
 const thisWeek=calls.filter(x=>x.week_key===currentWeek),completed=thisWeek.filter(x=>x.outcome==='Completed').length;
 const overdue=actions.filter(x=>x.status!=='Resolved'&&x.due_date<today()).length;
 const due=Math.max(0,activeAssignments.length-new Set(thisWeek.map(x=>String(x.student_id))).size);
 area.innerHTML=`<span class="eyebrow">STUDENT CARE · WEEKLY CYCLE</span><h3>Adoption calls & PTM</h3><p>School master view for teacher ownership, weekly parent calls, follow-up actions and PTM history.</p>
 <div class="portal-grid">
  <article class="portal-card"><p>Children assigned</p><strong class="metric">${activeAssignments.length}/${students.length}</strong></article>
  <article class="portal-card"><p>Calls completed this week</p><strong class="metric">${completed}</strong></article>
  <article class="portal-card"><p>Calls due this week</p><strong class="metric">${due}</strong></article>
  <article class="portal-card"><p>Overdue actions</p><strong class="metric">${overdue}</strong></article>
 </div>
 <section class="panel"><h3>Assign child to teacher</h3><form id="adoptAssign"><div class="fields"><label>Child<select name="student_id" required><option value="">Choose child…</option>${students.filter(s=>!assignedIds.has(String(s.id))).map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+' · '+esc(s.program||'')+'</option>').join('')}</select></label><label>Teacher<select name="teacher_id" required><option value="">Choose teacher…</option>${teachers.map(t=>'<option value="'+esc(t.account_id||t.id)+'">'+esc(t.name||t.email||t.account_id||t.id)+'</option>').join('')}</select></label><label>Assigned on<input type="date" name="assigned_on" value="${today()}" required></label><label>Notes<input name="notes" maxlength="500"></label></div><button>Assign child</button></form></section>
 <section class="panel"><h3>Record weekly call</h3><form id="adoptCall"><div class="fields"><label>Child<select name="student_id" required><option value="">Choose child…</option>${activeAssignments.map(a=>'<option value="'+esc(a.student_id)+'" data-teacher="'+esc(a.teacher_id)+'">'+esc(a.student_name||a.student_id)+' · '+esc(a.teacher_name||'Teacher')+'</option>').join('')}</select></label><label>Teacher<input name="teacher_name" readonly placeholder="Auto from assignment"></label><input type="hidden" name="teacher_id"><label>Call date<input type="date" name="call_date" value="${today()}" required></label><label>Outcome<select name="outcome"><option>Completed</option><option>Not reached</option><option>Missed</option></select></label></div><div class="fields"><label>Parent feedback<textarea name="parent_feedback" maxlength="1600"></textarea></label><label>Learning note<textarea name="learning_note" maxlength="1000"></textarea></label><label>Participation<textarea name="participation_note" maxlength="1000"></textarea></label><label>Home practice<textarea name="home_practice_note" maxlength="1000"></textarea></label><label>Parent concern<textarea name="parent_concern" maxlength="1200"></textarea></label></div><button>Save weekly call</button></form></section>
 <section class="panel"><h3>Next action</h3><form id="adoptAction"><div class="fields"><label>Child<select name="student_id" required><option value="">Choose child…</option>${students.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+'</option>').join('')}</select></label><label>Action<input name="title" maxlength="200" required></label><label>Owner<input name="owner" maxlength="120" required placeholder="Teacher / School / Parent"></label><label>Due date<input type="date" name="due_date" required></label><label>Status<select name="status"><option>Open</option><option>In progress</option><option>Resolved</option></select></label></div><label>Notes<textarea name="notes" maxlength="1200"></textarea></label><button>Save action</button></form></section>
 <section class="panel"><h3>PTM session</h3><form id="ptmForm"><div class="fields"><label>Child<select name="student_id" required><option value="">Choose child…</option>${students.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name)+'</option>').join('')}</select></label><label>PTM date<input type="date" name="session_date" value="${today()}" required></label><label><input type="checkbox" name="parent_attended"> Parent attended</label></div><label>Progress summary<textarea name="progress_summary" maxlength="1600" required></textarea></label><label>Discussion points<textarea name="discussion_points" maxlength="2000" required></textarea></label><label>Agreed actions<textarea name="agreed_actions" maxlength="1600"></textarea></label><label>Parent-safe report<textarea name="parent_safe_report" maxlength="2000"></textarea></label><button>Save PTM</button></form></section>
 <h3>Child follow-up list</h3><div class="portal-grid">${students.slice(0,60).map(s=>{const a=activeAssignments.find(x=>String(x.student_id)===String(s.id)),lc=calls.filter(x=>String(x.student_id)===String(s.id)).sort((x,y)=>String(y.call_date).localeCompare(String(x.call_date)))[0],oa=actions.filter(x=>String(x.student_id)===String(s.id)&&x.status!=='Resolved').length,pc=ptms.filter(x=>String(x.student_id)===String(s.id)).length;return '<article class="portal-card"><h3>'+esc(s.name)+'</h3><p>'+esc(s.program||'')+' · '+esc(a?.teacher_name||'Unassigned')+'</p><p>Last call: '+esc(lc?lc.call_date+' · '+lc.outcome:'No call yet')+'</p><p>Open actions: <b>'+oa+'</b> · PTMs: <b>'+pc+'</b></p></article>'}).join('')}</div>`;
 const wire=async(id,kind,transform=x=>x)=>{const form=area.querySelector(id);if(!form)return;form.onsubmit=async e=>{e.preventDefault();const b=transform(Object.fromEntries(new FormData(form)));b.request_id=crypto.randomUUID();const btn=e.submitter;btn.disabled=true;try{await call(kind,'POST',b);status('✓ Saved.');await refresh()}catch(err){status(err.message);btn.disabled=false}}};
 wire('#adoptAssign','adoption_assignments');
 const cf=area.querySelector('#adoptCall');if(cf){const sel=cf.elements.student_id;sel.onchange=()=>{const a=activeAssignments.find(x=>String(x.student_id)===String(sel.value));cf.elements.teacher_id.value=a?.teacher_id||'';cf.elements.teacher_name.value=a?.teacher_name||''};wire('#adoptCall','adoption_calls',b=>({...b,week_key:weekKey(b.call_date)}))}
 wire('#adoptAction','adoption_actions');
 wire('#ptmForm','ptm_sessions',b=>({...b,parent_attended:area.querySelector('#ptmForm [name="parent_attended"]').checked}));
};
})();