(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
window.renderNeoAdoptionPTM=function(area,ctx){
 const {records:r,call,refresh,status}=ctx,students=(r.students||[]).filter(x=>(x.status||'Active')!=='Withdrawn'),classrooms=r.classrooms||[],teachers=r.teacher_access||[],assignments=r.adoption_assignments||[],calls=r.adoption_calls||[],actions=r.adoption_actions||[],ptms=r.ptm_sessions||[];
 const active=assignments.filter(x=>x.status==='Active'),assigned=new Set(active.map(x=>String(x.student_id))),unassigned=students.filter(x=>!assigned.has(String(x.id))),overdue=actions.filter(x=>x.status!=='Resolved'&&x.due_date&&x.due_date<today()).length;
 area.innerHTML=`<span class="eyebrow">STUDENT CARE · SCHOOL MASTER</span><h3>Adoption assignment & monitoring</h3><p>School administration only assigns children and monitors completion. Weekly calls, follow-up actions and PTM entry are handled by the assigned teacher in the Teacher Portal.</p>
 <div class="portal-grid"><article class="portal-card"><p>Assigned children</p><strong class="metric">${active.length}/${students.length}</strong></article><article class="portal-card"><p>Unassigned children</p><strong class="metric">${unassigned.length}</strong></article><article class="portal-card"><p>Weekly calls recorded</p><strong class="metric">${calls.length}</strong></article><article class="portal-card"><p>Overdue actions</p><strong class="metric">${overdue}</strong></article></div>
 <section class="panel"><h3>Bulk assign children</h3><p class="form-note">Choose a class, select any 1–40 children, then assign them together to one teacher.</p><div class="fields"><label>Classroom<select id="adoptClass"><option value="">Choose classroom…</option>${classrooms.map(c=>'<option value="'+esc(c.id)+'">'+esc(c.name||c.program||c.id)+'</option>').join('')}</select></label><label>Teacher<select id="adoptTeacher"><option value="">Choose teacher…</option>${teachers.map(t=>'<option value="'+esc(t.account_id||t.id)+'">'+esc(t.name||t.email||t.account_id||t.id)+'</option>').join('')}</select></label><label>Assigned on<input id="adoptDate" type="date" value="${today()}"></label></div><div id="adoptChildren" class="portal-card"><p>Select a classroom to load children.</p></div><button id="assignSelected" type="button">Assign selected children</button></section>
 <h3>Current ownership</h3><div class="portal-grid">${active.slice(0,80).map(a=>'<article class="portal-card"><h3>'+esc(a.student_name||a.student_id)+'</h3><p>'+esc(a.teacher_name||a.teacher_id)+'</p><p>Assigned: '+esc(a.assigned_on||'—')+'</p></article>').join('')||'<p class="portal-empty">No children assigned yet.</p>'}</div>
 <h3>Progress monitoring</h3><div class="portal-grid">${students.slice(0,80).map(s=>{const a=active.find(x=>String(x.student_id)===String(s.id)),lc=calls.filter(x=>String(x.student_id)===String(s.id)).sort((x,y)=>String(y.call_date||'').localeCompare(String(x.call_date||'')))[0],oa=actions.filter(x=>String(x.student_id)===String(s.id)&&x.status!=='Resolved').length,pc=ptms.filter(x=>String(x.student_id)===String(s.id)).length;return '<article class="portal-card"><h3>'+esc(s.name)+'</h3><p>'+esc(s.program||'')+' · '+esc(a?.teacher_name||'Unassigned')+'</p><p>Last call: '+esc(lc?lc.call_date+' · '+lc.outcome:'No call yet')+'</p><p>Open actions: <b>'+oa+'</b> · PTMs: <b>'+pc+'</b></p></article>'}).join('')}</div>`;
 const classSel=area.querySelector('#adoptClass'),childrenBox=area.querySelector('#adoptChildren');
 const drawChildren=()=>{const cid=classSel.value,list=students.filter(s=>s.classroom_id===cid&&!assigned.has(String(s.id)));childrenBox.innerHTML=cid?`<label style="display:block;margin-bottom:10px"><input type="checkbox" id="adoptSelectAll"> Select all (${list.length})</label><div class="portal-grid">${list.map(s=>'<label class="portal-card" style="cursor:pointer"><input type="checkbox" data-child-id="'+esc(s.id)+'"> <strong>'+esc(s.name)+'</strong><br><small>'+esc(s.program||'')+'</small></label>').join('')||'<p class="portal-empty">All children in this classroom are already assigned.</p>'}</div>`:'<p>Select a classroom to load children.</p>';const all=childrenBox.querySelector('#adoptSelectAll');if(all)all.onchange=()=>childrenBox.querySelectorAll('[data-child-id]').forEach(x=>x.checked=all.checked)};
 classSel.onchange=drawChildren;
 area.querySelector('#assignSelected').onclick=async()=>{const teacher=area.querySelector('#adoptTeacher').value,date=area.querySelector('#adoptDate').value,ids=[...childrenBox.querySelectorAll('[data-child-id]:checked')].map(x=>x.dataset.childId);if(!classSel.value)return status('Choose a classroom.');if(!teacher)return status('Choose a teacher.');if(!ids.length)return status('Select at least one child.');if(ids.length>40)return status('Select up to 40 children at a time.');const t=teachers.find(x=>String(x.account_id||x.id)===String(teacher));const btn=area.querySelector('#assignSelected');btn.disabled=true;try{let done=0;for(const id of ids){await call('adoption_assignments','POST',{request_id:crypto.randomUUID(),student_id:id,teacher_id:teacher,assigned_on:date,notes:'Bulk school assignment'});done++}status('✓ '+done+' children assigned to '+(t?.name||'teacher')+'.');await refresh()}catch(e){status(e.message);btn.disabled=false}};
};
})();