/* Date-only values must never pass through a UTC conversion on import. */
window.neoLocalDateKey=function(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
window.neoParseCalendarDate=function(value){
 if(value instanceof Date){if(!Number.isFinite(value.getTime()))throw Error('Invalid date');return window.neoLocalDateKey(value)}
 const text=String(value??'').trim();let parts=text.match(/^(\d{4})-(\d{2})-(\d{2})$/),y,m,d;
 if(parts){[,y,m,d]=parts}else{parts=text.match(/^(\d{2})([/-])(\d{2})\2(\d{4})$/);if(!parts)throw Error('Use YYYY-MM-DD, DD/MM/YYYY or DD-MM-YYYY dates.');d=parts[1];m=parts[3];y=parts[4]}
 y=Number(y);m=Number(m);d=Number(d);const date=new Date(y,m-1,d,12);
 if(y<1900||y>2200||date.getFullYear()!==y||date.getMonth()!==m-1||date.getDate()!==d)throw Error('Invalid calendar date: '+text);
 return window.neoLocalDateKey(date);
};
window.renderNeoCalendar=async function(area,{api,editable=false,state=null}){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
 try{
 state=state||await api('calendar');
 let academic={status:'Not published',working_dates:[]};try{academic=await api('academic-calendar')}catch(_e){}
 const workingDates=new Set(Array.isArray(academic.working_dates)?academic.working_dates:[]);
 let events=state.events.map(e=>({...e})),revision=state.revision,selected='',editing=-1;
 const types=['Holiday','PTM','Meeting','Celebration','Event','Academic','Assessment','Exam','School reopening','Other'];
 const normalizeType=t=>{const v=String(t||'').trim();const aliases={'PTM / meeting':'PTM','Assessment / exam':'Assessment','School Reopening':'School reopening'};return aliases[v]||v};
 const kind=t=>{t=normalizeType(t);return t==='Holiday'?'holiday':t==='PTM'||t==='Meeting'?'meeting':t==='Celebration'?'celebration':t==='Academic'?'academicEvent':t==='Assessment'||t==='Exam'?'assessment':t==='School reopening'?'reopening':t==='Other'?'other':'event'};
 const palette={event:'#16a34a',holiday:'#ef4444',meeting:'#f97316',celebration:'#d946ef',academicEvent:'#14b8a6',assessment:'#eab308',reopening:'#7c3aed',other:'#64748b',academic:'#0284c7'};
 const marker=k=>`<span class="neo-calendar-dot ${k}" aria-hidden="true" style="width:10px;height:10px;flex:0 0 10px;background:${palette[k]};box-shadow:0 0 0 1px #fff,0 1px 3px #0002"></span>`;
 area.innerHTML=`<h3>School calendar</h3><p>School events are shared with parents and teachers. ${workingDates.size?`The published academic calendar contains <strong>${workingDates.size} working days</strong> (${esc([...workingDates][0])} → ${esc([...workingDates][workingDates.size-1])}). Working days are highlighted in blue.`:'The 200-day academic calendar has not been published to this account yet.'}</p><div class="fields"><label>View<select id="calendarRange"><option value="week">Week</option><option value="month" selected>Month</option><option value="all">All</option></select></label><label>Starting date<input id="calendarDate" type="date" value="${esc(state.today)}"></label></div>${editable?`<details class="portal-editor"><summary>Add event / holiday</summary><form id="calendarForm"><div class="fields"><label>Date<input name="date" type="date" required></label><label>Category<select name="type">${types.map(v=>'<option>'+v+'</option>').join('')}</select></label><label>Title<input name="title" required maxlength="160"></label><label>Description<textarea name="description" maxlength="2000"></textarea></label></div><button>Add to draft</button></form></details><button id="calendarTemplate" class="secondary">Download event template</button><label>Import events Excel (.xlsx)<input id="calendarImport" type="file" accept=".xlsx"></label><p>Columns: date, type, title, description. Supported categories include Holiday, Event, Meeting/PTM, Academic, Exam/Assessment, Celebration and School reopening. Import adds to the draft; review and Save to publish.</p><button type="button" id="calendarSave">Save calendar for families and teachers</button>`:''}<button type="button" id="calendarExport" class="secondary">Download calendar</button><p id="calendarStatus" role="status" aria-live="polite"></p><div id="calendarEvents"></div>`;
 const message=t=>{const n=area.querySelector('#calendarStatus');if(n)n.textContent=t};
 function draw(){
 const start=window.neoParseCalendarDate(area.querySelector('#calendarDate').value),range=area.querySelector('#calendarRange').value;const d=new Date(start+'T12:00:00');let from=start,end=start,grid='';
 if(range==='week'){const last=new Date(d);last.setDate(last.getDate()+6);end=window.neoLocalDateKey(last)}
 if(range==='month'){const first=new Date(d.getFullYear(),d.getMonth(),1,12),last=new Date(d.getFullYear(),d.getMonth()+1,0,12);from=window.neoLocalDateKey(first);end=window.neoLocalDateKey(last);let cells=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map((n,i)=>`<div class="neo-weekday" style="${i===0||i===6?'background:#eef1f5;color:#536174':'background:#f7f9fc'}">${n}</div>`).join('');for(let i=0;i<first.getDay();i++)cells+='<div class="neo-month-day empty" style="background:#f1f3f6;border:1px solid #d8dee8"></div>';for(let day=1;day<=last.getDate();day++){const dateObj=new Date(d.getFullYear(),d.getMonth(),day,12),key=window.neoLocalDateKey(dateObj),items=events.filter(e=>e.date===key),markers=[...new Set(items.map(e=>kind(e.type)))],working=workingDates.has(key),weekend=[0,6].includes(dateObj.getDay());cells+=`<button type="button" class="neo-month-day ${working?'neo-working-day':''}" data-calendar-day="${key}" style="background:${working?'#f1f9ff':weekend?'#f2f4f7':'#fff'};border:1px solid #d8dee8;box-shadow:${working?'inset 0 0 0 2px #0284c7':'none'};min-height:78px"><span class="neo-day-number">${day}</span><span class="neo-calendar-markers" style="gap:6px;margin-top:12px">${markers.map(marker).join('')}${working?marker('academic'):''}</span></button>`}for(let i=last.getDay();i<6;i++)cells+='<div class="neo-month-day empty" style="background:#f1f3f6;border:1px solid #d8dee8"></div>';const legend=[['event','Event'],['holiday','Holiday'],['meeting','PTM / meeting'],['celebration','Celebration'],['academicEvent','Academic event'],['assessment','Assessment / exam'],['reopening','School reopening'],['other','Other'],['academic','Academic / working day']];grid=`<section class="neo-calendar-shell"><div class="neo-calendar-toolbar"><button type="button" class="secondary" id="calendarPrevious">‹ Previous</button><h3>${esc(d.toLocaleDateString('en-IN',{month:'long',year:'numeric'}))}</h3><button type="button" class="secondary" id="calendarNext">Next ›</button></div><div class="neo-calendar-legend">${legend.map(([k,t])=>`<span><i class="neo-dot" style="background:${palette[k]}"></i>${t}</span>`).join('')}</div><div class="neo-month-grid" style="border:1px solid #cfd7e3;background:#d8dee8;gap:0">${cells}</div></section>`}
 const visible=events.map((e,i)=>({e,i})).filter(({e})=>(range==='all'||e.date>=from&&e.date<=end)&&(!selected||range!=='month'||e.date===selected)).sort((a,b)=>a.e.date.localeCompare(b.e.date));area.querySelector('#calendarEvents').innerHTML=grid+`<section><h3>All calendar items</h3><div class="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Title</th><th>Description</th>${editable?'<th>Draft actions</th>':''}</tr></thead><tbody>${visible.map(({e,i})=>`<tr><td>${esc(e.date)}</td><td>${marker(kind(e.type))} ${esc(e.type)}</td><td>${esc(e.title)}</td><td>${esc(e.description)}</td>${editable?`<td><button type="button" class="secondary" data-edit-event="${i}">Edit draft</button> <button type="button" class="secondary" data-remove-event="${i}">Remove from draft</button></td>`:''}</tr>`).join('')}</tbody></table></div></section>`;area.querySelectorAll('[data-calendar-day]').forEach(b=>b.onclick=()=>{selected=selected===b.dataset.calendarDay?'':b.dataset.calendarDay;draw()});for(const [id,step] of [['calendarPrevious',-1],['calendarNext',1]]){const b=area.querySelector('#'+id);if(b)b.onclick=()=>{area.querySelector('#calendarDate').value=window.neoLocalDateKey(new Date(d.getFullYear(),d.getMonth()+step,1,12));selected='';draw()}}area.querySelectorAll('[data-remove-event]').forEach(b=>b.onclick=()=>{events.splice(Number(b.dataset.removeEvent),1);draw();message('Unsaved changes. Save to publish.')});area.querySelectorAll('[data-edit-event]').forEach(b=>b.onclick=()=>{editing=Number(b.dataset.editEvent);const f=area.querySelector('#calendarForm');for(const k of ['date','type','title','description'])f.elements[k].value=events[editing][k]||'';f.closest('details').open=true})}
 area.querySelector('#calendarRange').onchange=()=>{selected='';draw()};area.querySelector('#calendarDate').onchange=()=>{selected='';draw()};draw();
 area.querySelector('#calendarExport').onclick=async()=>{try{await window.neoExport('neo-school-calendar',[...events,...[...workingDates].map(date=>({date,type:'Academic working day',title:'Working day',description:'Published 200-day academic calendar'}))])}catch(e){message(e.message)}};
 if(!editable)return;
 area.querySelector('#calendarTemplate').onclick=async()=>{try{await window.neoExport('neo-event-template',[{date:'',type:'',title:'',description:''}])}catch(e){message(e.message)}};
 area.querySelector('#calendarForm').onsubmit=e=>{e.preventDefault();const item=Object.fromEntries(new FormData(e.target));item.date=window.neoParseCalendarDate(item.date);if(editing>=0)events[editing]=item;else events.push(item);editing=-1;draw();e.target.reset();message('Added to draft. Save the calendar to publish.')};
 const saveButton=area.querySelector('#calendarSave');saveButton.addEventListener('click',async()=>{if(saveButton.disabled)return;saveButton.disabled=true;saveButton.textContent='Saving…';message(`Saving ${events.length} calendar items…`);try{const b=await api('calendar',{revision,events});revision=b.revision;message(`Save accepted by server. Verifying ${events.length} items…`);const verify=await api('calendar');const saved=Array.isArray(verify.events)?verify.events:[];if(saved.length!==events.length)throw Error(`Save verification failed: server has ${saved.length} of ${events.length} items.`);events=saved.map(e=>({...e}));revision=verify.revision||revision;draw();message(`Calendar saved and verified: ${saved.length} items published · Revision ${revision}. Parents and teachers can refresh now.`)}catch(err){message('SAVE ERROR: '+err.message)}finally{saveButton.disabled=false;saveButton.textContent='Save calendar for families and teachers'}});
 area.querySelector('#calendarImport').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const x=await window.neoLoadExcel(),wb=x.read(await file.arrayBuffer(),{type:'array',cellDates:false,sheetRows:502}),sheet=wb.Sheets[wb.SheetNames[0]],rows=x.utils.sheet_to_json(sheet,{defval:''});const incoming=rows.map(r=>({date:window.neoParseCalendarDate(typeof r.date==='number'?(()=>{const d=x.SSF.parse_date_code(r.date,{date1904:!!wb.Workbook?.WBProps?.date1904});return `${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`})():r.date),type:normalizeType(r.type),title:String(r.title),description:String(r.description||'')}));if(incoming.some(e=>!e.title.trim()||!types.includes(e.type)))throw Error('Check dates, category and title.');events.push(...incoming);area.querySelector('#calendarRange').value='all';draw();message(`Imported ${incoming.length} events to draft. Review and Save calendar to publish.`)}catch(err){message(err.message)}};
 }catch(e){area.textContent='Calendar unavailable: '+e.message}
};
