window.renderNeoCalendar=async function(area,{api,editable=false,state=null}){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 try{state=state||await api('calendar');let events=state.events.slice(),revision=state.revision;
 area.innerHTML=`<h3>School calendar</h3><p>School events are shared with parents and teachers. Holidays added here are excluded when generating a new curriculum calendar. An already approved plan is not automatically moved.</p><div class="fields"><label>View<select id="calendarRange"><option value="week">Week</option><option value="month">Month</option><option value="all">All</option></select></label><label>Starting date<input id="calendarDate" type="date" value="${esc(state.today)}"></label></div>${editable?`<details class="portal-editor"><summary>Add event / holiday</summary><form id="calendarForm"><div class="fields"><label>Date<input name="date" type="date" required></label><label>Category<select name="type">${['Holiday','PTM','Celebration','Event','Assessment','School reopening','Other'].map(v=>'<option>'+v+'</option>').join('')}</select></label><label>Title<input name="title" required maxlength="160"></label><label>Description<textarea name="description" maxlength="2000"></textarea></label></div><button>Add to draft</button></form></details><button id="calendarTemplate" class="secondary">Download event template</button><label>Import events Excel (.xlsx)<input id="calendarImport" type="file" accept=".xlsx"></label><p>Columns: date, type, title, description. Import adds to the draft; review and Save to publish.</p><button id="calendarSave">Save calendar for families and teachers</button>`:''}<button id="calendarExport" class="secondary">Download calendar</button><p id="calendarStatus" role="status"></p><div id="calendarEvents"></div>`;
 const message=t=>area.querySelector('#calendarStatus').textContent=t;
 function draw(){const start=area.querySelector('#calendarDate').value,range=area.querySelector('#calendarRange').value;let end=start;if(range==='week')end=new Date(Date.parse(start)+6*86400000).toISOString().slice(0,10);else if(range==='month'){const d=new Date(start+'T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+1);d.setUTCDate(d.getUTCDate()-1);end=d.toISOString().slice(0,10)}area.querySelector('#calendarEvents').innerHTML='<div class="portal-grid">'+events.map((e,i)=>({e,i})).filter(({e})=>range==='all'||e.date>=start&&e.date<=end).sort((a,b)=>a.e.date.localeCompare(b.e.date)).map(({e,i})=>`<article class="portal-card"><span class="portal-pill">${esc(e.date)} · ${esc(e.type)}</span><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p>${editable?`<button class="secondary" data-remove-event="${i}">Remove from draft</button>`:''}</article>`).join('')+'</div>';area.querySelectorAll('[data-remove-event]').forEach(b=>b.onclick=()=>{events.splice(Number(b.dataset.removeEvent),1);draw();message('Unsaved changes. Save to publish.')})}
 area.querySelector('#calendarRange').onchange=draw;area.querySelector('#calendarDate').onchange=()=>{if(area.querySelector('#calendarDate').value)draw()};draw();
 area.querySelector('#calendarExport').onclick=async()=>{try{await window.neoExport('neo-school-calendar',events)}catch(e){message(e.message)}};
 if(!editable)return;
 area.querySelector('#calendarTemplate').onclick=async()=>{try{await window.neoExport('neo-event-template',[{date:'',type:'',title:'',description:''}])}catch(e){message(e.message)}};
 area.querySelector('#calendarForm').onsubmit=e=>{e.preventDefault();events.push(Object.fromEntries(new FormData(e.target)));area.querySelector('#calendarRange').value='all';draw();e.target.reset();message('Added to draft. Save the calendar to publish.')};
 area.querySelector('#calendarSave').onclick=async e=>{e.target.disabled=true;try{const b=await api('calendar',{revision,events});revision=b.revision;message('Calendar saved. Parents and teachers can refresh to see it.')}catch(err){message(err.message)}finally{e.target.disabled=false}};
 area.querySelector('#calendarImport').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>1500000)throw Error('Maximum file size 1.5 MB.');const x=await window.neoLoadExcel(),wb=x.read(await file.arrayBuffer(),{type:'array',cellDates:true,sheetRows:502}),sheet=wb.Sheets[wb.SheetNames[0]];if(Object.values(sheet).some(c=>c&&c.f))throw Error('Use values, not formulas.');const rows=x.utils.sheet_to_json(sheet,{defval:''});if(rows.length+events.length>500)throw Error('Maximum 500 events.');const incoming=rows.map(r=>({date:r.date instanceof Date?r.date.toISOString().slice(0,10):String(r.date),type:String(r.type),title:String(r.title),description:String(r.description||'')}));if(incoming.some(e=>!/^\d{4}-\d{2}-\d{2}$/.test(e.date)||!e.title.trim()))throw Error('Check dates and event titles.');events.push(...incoming);area.querySelector('#calendarRange').value='all';draw();message('Imported to draft. Review before Save.')}catch(err){message(err.message)}};
 }catch(e){area.textContent='Calendar unavailable: '+e.message}
};
