(function(){
 const base='https://neo-lead-crm-api.umakanthgilla.workers.dev',key='neo_transport_token';
 const app=document.getElementById('app'),login=document.getElementById('loginPanel'),message=document.getElementById('message'),loginStatus=document.getElementById('loginStatus'),signOut=document.getElementById('signOut'),staffName=document.getElementById('staffName');
 let token=sessionStorage.getItem(key)||'',current=null,selectedRoute='',startChoices=[],activeView='route',menuOpen=true,viewHistory=[],documents=null,documentVehicle='',documentUrl='',careRecords=null,careVehicle='',staffDocuments=null,selectedStaff='',selectedCareType='Fuel refill';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const paths={bus:'<path d="M5 17V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v12H5Z"/><path d="M5 11h14M7 17v3m10-3v3M8 14h.01M16 14h.01"/>',route:'<circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18h6a4 4 0 0 0 4-4v-6"/>',check:'<path d="M4 12l5 5L20 6"/>',alert:'<path d="M12 3 2 21h20L12 3Z"/><path d="M12 9v5m0 3h.01"/>',child:'<circle cx="12" cy="7" r="3"/><path d="M5 21v-3a7 7 0 0 1 14 0v3"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',fuel:'<path d="M4 20V4h11v16H4Zm0-9h11m0-4 3 2v8a2 2 0 0 0 4 0v-6l-2-2"/>',camera:'<path d="M3 7h4l2-3h6l2 3h4v13H3V7Z"/><circle cx="12" cy="13" r="3"/>',file:'<path d="M6 2h8l5 5v15H6V2Z"/><path d="M14 2v6h5M9 13h7M9 17h7"/>'};
 const icon=(name,color='')=>`<span class="transport-icon ${color}" aria-hidden="true"><svg viewBox="0 0 24 24">${paths[name]}</svg></span>`;
 const status=s=>{message.textContent=s;loginStatus.textContent=login.hidden?'':s;clearTimeout(status.timer);status.timer=setTimeout(()=>{message.textContent='';loginStatus.textContent=''},45000)};
 const api=async(path,method='GET',body)=>{const r=await fetch(base+'/api/transport/'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json().catch(()=>({error:'Unreadable response.'}));if(!r.ok)throw Error(d.error||'Transport request failed.');return d};
 const logout=()=>{window.NeoTransportPush?.signOut(token);if(documentUrl)URL.revokeObjectURL(documentUrl);documentUrl='';token='';sessionStorage.removeItem(key);current=null;selectedRoute='';activeView='route';menuOpen=true;viewHistory=[];documents=null;documentVehicle='';careRecords=null;careVehicle='';staffDocuments=null;selectedStaff='';app.hidden=true;login.hidden=false;document.body.classList.remove('transport-authenticated');signOut.hidden=true;staffName.textContent=''};signOut.onclick=logout;
 document.getElementById('togglePassword').onclick=()=>{const input=document.getElementById('transportPassword'),button=document.getElementById('togglePassword'),visible=input.type==='password';input.type=visible?'text':'password';button.setAttribute('aria-label',visible?'Hide password':'Show password');button.title=visible?'Hide password':'Show password';button.setAttribute('aria-pressed',String(visible))};
 document.getElementById('forgotPassword').onclick=()=>{const button=document.getElementById('forgotPassword'),help=document.getElementById('forgotHelp');help.hidden=!help.hidden;button.setAttribute('aria-expanded',String(!help.hidden))};
 async function picture(file){if(!file||!file.type.startsWith('image/'))throw Error('Take a vehicle odometer photo.');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let data=canvas.toDataURL('image/jpeg',.7);if(data.length>205000)data=canvas.toDataURL('image/jpeg',.45);if(data.length>205000)throw Error('Photo is too large. Take a smaller photo.');return data}
 const byId=id=>current.students.find(s=>s.id===id)?.name||id;
 const manifest=(route,run,direction)=>current.assignments.filter(a=>a.route_id===route.id&&Number(a.run_no||1)===run).sort((a,b)=>{const x=route.stops.indexOf(a.stop),y=route.stops.indexOf(b.stop);return(direction==='Drop'?y-x:x-y)||String(a.created_at).localeCompare(String(b.created_at))||a.id.localeCompare(b.id)});
 const absentInMorning=(route,run)=>new Set((current.trips.find(t=>t.route_id===route.id&&t.direction==='Pickup'&&Number(t.run_no||1)===run)?.events||[]).filter(e=>e.type==='Absent').map(e=>e.student_id));
 function tripCard(route,direction,run,count){
  const trip=current.trips.find(t=>t.route_id===route.id&&t.direction===direction&&Number(t.run_no||1)===run),children=trip?.manifest||manifest(route,run,direction);if(!children.length)return '';
  const morningAbsent=direction==='Drop'?absentInMorning(route,run):new Set();
  const heading=direction==='Pickup'?'Morning pickup':'Return drop';
  const finalEvents=new Map((trip?.events||[]).filter(e=>['Picked up','Dropped at stop','Absent'].includes(e.type)).map(e=>[e.student_id,e]));
  const done=children.filter(a=>finalEvents.has(a.student_id)).length,next=children.find(a=>!finalEvents.has(a.student_id));
  const finished=trip?.status==='Completed',started=trip?.status==='Started';
  const progress=finished||started&&!next?100:Math.round(done/children.length*100);
  const tripStops=trip?.route_stops||route.stops;
  const startLabel=direction==='Pickup'?tripStops[0]||'Route start':'School';
  const endLabel=direction==='Pickup'?'School':tripStops[0]||'Route end';
  const journey=`<div class="transport-journey" aria-label="${esc(heading)} progress: ${done} of ${children.length} children recorded">
    <div class="transport-journey-meta"><strong>${finished?'Trip completed':started?next?'Next stop':'All children recorded':'Ready to start'}</strong><span>${done} / ${children.length}</span></div>
    <div class="transport-journey-track" role="img" aria-label="${done} of ${children.length} stops recorded"><span class="transport-journey-fill" style="width:${progress}%"></span><span class="transport-journey-bus" style="left:${progress}%">${icon('bus')}</span></div>
    <div class="transport-journey-ends"><span>${esc(startLabel)}</span><span>${esc(endLabel)}</span></div>
   </div>`;
  const itinerary=`<details class="transport-itinerary"><summary>${icon('route')}View all ${children.length} stops</summary><ol>${children.map((a,index)=>{const event=finalEvents.get(a.student_id);return `<li class="${event?'is-done':a===next&&started?'is-next':''}"><span class="transport-stop-number">${event?icon(event.type==='Absent'?'alert':'check'):index+1}</span><span><b>${esc(a.name||byId(a.student_id))}</b><small>${esc(a.stop)}</small></span>${event?`<span class="transport-stop-state">${esc(event.type)}</span>`:''}</li>`}).join('')}</ol></details>`;
  return `<article class="transport-row transport-trip-card"><h3 class="transport-section-title">${icon(direction==='Pickup'?'child':'bus',direction==='Pickup'?'green':'gold')}${heading}${count>1?' · Trip '+run:''}</h3>`+
   journey+
   (trip?`<p class="transport-trip-reading">Status: <strong>${esc(trip.status)}</strong> · Start ${esc(trip.odometer_start_km)} km ${trip.odometer_end_km!=null?' · Finish '+esc(trip.odometer_end_km)+' km':''}</p>`:'')+
   (started&&next?`<div class="transport-next-child"><span class="transport-step-label">STOP ${done+1} OF ${children.length}</span><div class="transport-next-name">${icon('child','green')}<span><b>${esc(next.name||byId(next.student_id))}</b><small>${esc(next.stop)}</small></span></div>${morningAbsent.has(next.student_id)?`<div class="transport-notice transport-warning" role="alert">${icon('alert','gold')}<p><strong>Morning pickup: Absent.</strong> Check with the parent or attendant whether this child is on the return vehicle.</p></div>`:''}<div class="transport-actions"><button data-child="${esc(next.student_id)}" data-trip="${esc(trip.id)}" data-event="${direction==='Pickup'?'Picked up':'Dropped at stop'}" ${morningAbsent.has(next.student_id)?'data-morning-absent="true"':''}>${icon('check')}${direction==='Pickup'?'Picked up':morningAbsent.has(next.student_id)?'Verify & drop off':'Dropped off'}</button><button class="secondary" data-child="${esc(next.student_id)}" data-trip="${esc(trip.id)}" data-event="Absent">${icon('alert','gold')}Absent</button></div></div>`:'')+
   (!trip?`<button type="button" class="transport-open-start" data-open-start="${esc(route.id)}" data-direction="${direction}" data-run="${run}">${icon('bus')}Start trip</button>`:'')+
   (started&&!next?`<form data-finish="${esc(trip.id)}" class="transport-finish-form"><h4>${icon('check','green')}All children recorded. Finish the trip.</h4><div class="transport-form-fields"><label>Finish odometer (km)<input type="number" min="${esc(trip.odometer_start_km)}" name="odometer_km" required></label><label>Finish odometer photo<input type="file" accept="image/*" capture="environment" name="photo" required></label></div><button>${icon('check')}Finish trip</button></form>`:'')+
   itinerary+
   (trip?.events||[]).filter(e=>e.type==='Emergency').map(e=>`<div class="transport-notice transport-warning" role="status">${icon('alert','gold')}<p>Emergency reported: ${esc(e.emergency_type)} · ${esc(e.note||'School informed')}</p></div>`).join('')+
   (started?`<details class="transport-trip-tools"><summary>${icon('alert','gold')}Report route emergency</summary><form data-emergency="${esc(trip.id)}" class="transport-emergency-form"><div class="transport-form-fields"><label>Type<select name="type" required><option value="">Choose…</option><option>Breakdown</option><option>Delay</option><option>Medical</option><option>Other</option></select></label><label>Short note for school<input name="message" maxlength="200" placeholder="What happened?"></label></div><p>School receives the details; route parents receive a general service update.</p><button type="submit" class="secondary">Send emergency alert</button></form></details>`:'')+`</article>`;
 }
 const docLabels={insurance:'Insurance',pollution:'Pollution certificate',fitness:'Fitness certificate',tax:'Road tax',rc:'Vehicle RC',license:'Driving licence',aadhaar:'Aadhaar card',id_proof:'ID proof'};
 async function loadDocuments(vehicleId){
  documents=null;documentVehicle=vehicleId;render();
  try{const result=await api('driver/documents/'+encodeURIComponent(vehicleId));if(activeView==='documents'&&documentVehicle===vehicleId){documents=result.documents;render()}}
  catch(err){if(activeView==='documents'&&documentVehicle===vehicleId){documents=[];render();status(err.message)}}
 }
 async function loadCare(vehicleId){
  careRecords=null;careVehicle=vehicleId;render();
  try{const result=await api('driver/care/'+encodeURIComponent(vehicleId));if(activeView==='care'&&careVehicle===vehicleId){careRecords=result.records;render()}}
  catch(err){if(activeView==='care'&&careVehicle===vehicleId){careRecords=[];render();status(err.message)}}
 }
 async function loadStaffDocuments(staffId){
  staffDocuments=null;selectedStaff=staffId;render();try{const result=await api('driver/staff-documents/'+encodeURIComponent(staffId));if(activeView==='staff'&&selectedStaff===staffId){staffDocuments=result.documents;render()}}catch(err){if(activeView==='staff'&&selectedStaff===staffId){staffDocuments=[];render();status(err.message)}}
 }
 async function openDocument(id,kind='vehicle'){
  const dialog=document.getElementById('transportDocumentDialog'),image=dialog.querySelector('img'),title=dialog.querySelector('[data-document-title]');
  const record=(kind==='staff'?staffDocuments:documents)?.find(d=>d.id===id);if(!record)return;
  try{
   const response=await fetch(base+'/api/transport/'+(kind==='staff'?'staff-document/':'document/')+encodeURIComponent(id),{headers:{Authorization:'Bearer '+token}});
   if(!response.ok)throw Error('Document unavailable. Refresh and try again.');
   const blob=await response.blob();if(blob.type!=='image/jpeg')throw Error('Document image unavailable.');
   if(documentUrl)URL.revokeObjectURL(documentUrl);documentUrl=URL.createObjectURL(blob);
   image.src=documentUrl;image.alt=(docLabels[record.type]||record.type)+' document';title.textContent=(docLabels[record.type]||record.type)+' · '+(kind==='staff'?current.crew?.find(x=>x.id===selectedStaff)?.name||'Staff':current.vehicles.find(v=>v.id===documentVehicle)?.registration_no||'Vehicle');
   dialog.showModal();
  }catch(err){status(err.message)}
 }
 function render(){
  const route=current.routes.find(r=>r.id===selectedRoute)||current.routes[0];selectedRoute=route?.id||'';
  login.hidden=true;app.hidden=false;document.body.classList.add('transport-authenticated');signOut.hidden=false;staffName.textContent=current.name+' · '+current.role;
  window.NeoAlertSound?.count('transport:'+current.account_id,current.reminders.length+current.trips.reduce((n,t)=>n+(t.events||[]).filter(e=>e.type==='Emergency').length,0));
  const vehicle=route&&current.vehicles.find(v=>v.id===route.vehicle_id),crew=route?[route.driver_staff_id,route.attendant_staff_id].filter(id=>id&&(current.role!=='Attendant'||id===current.staff_id)).map(id=>current.crew?.find(x=>x.id===id)||{id,name:id}):[];
  if(!crew.some(x=>x.id===selectedStaff))selectedStaff=crew[0]?.id||'';
  const availableTrips=current.routes.flatMap(r=>['Pickup','Drop'].flatMap(direction=>Array.from({length:Number(r.trip_count||1)},(_,i)=>({route:r,direction,run:i+1})).filter(t=>manifest(r,t.run,t.direction).length&&!current.trips.some(v=>v.route_id===r.id&&v.direction===t.direction&&Number(v.run_no||1)===t.run))));startChoices=availableTrips;
  document.body.querySelector(':scope > #transportStartDialog')?.remove();
  app.innerHTML=`<div class="transport-work-bar"><button type="button" data-view="route" aria-current="${activeView==='route'}">${icon('bus')}<span>Today’s Assigned Trips &amp; Vehicle</span></button><button type="button" data-menu-toggle aria-expanded="${menuOpen}" aria-controls="transportTools">${icon('route','gold')}<span>Menu</span></button></div>
   <nav id="transportTools" class="transport-menu-panel" aria-label="Transport tools" ${menuOpen?'':'hidden'}>
    <details class="transport-nav-group" ${activeView==='documents'||activeView==='staff'?'open':''}><summary>${icon('file','green')}<span>Documents</span></summary><div class="transport-nav-children"><button type="button" data-view="documents" aria-current="${activeView==='documents'}">${icon('file','green')}<span>Vehicle Documents</span></button><button type="button" data-view="staff" data-staff-target="driver" aria-current="${activeView==='staff'&&selectedStaff===route?.driver_staff_id}" ${current.role==='Attendant'?'disabled title="Driver documents are available to assigned drivers"':''}>${icon('child','green')}<span>Driver Documents</span></button><button type="button" data-view="staff" data-staff-target="attendant" aria-current="${activeView==='staff'&&selectedStaff===route?.attendant_staff_id}" ${!route?.attendant_staff_id?'disabled title="No attendant assigned"':''}>${icon('child','green')}<span>Attendant Documents</span></button></div></details>
    <details class="transport-nav-group" ${activeView==='care'?'open':''}><summary>${icon('fuel','gold')}<span>Vehicle Maintenance</span></summary><div class="transport-nav-children"><button type="button" data-view="care" data-care-target="Fuel refill" aria-current="${activeView==='care'&&selectedCareType==='Fuel refill'}">${icon('fuel','gold')}<span>Fuel Refill</span></button><button type="button" data-view="care" data-care-target="Tyre air" aria-current="${activeView==='care'&&selectedCareType==='Tyre air'}">${icon('check','green')}<span>Tyre Air Check</span></button><button type="button" data-view="care" data-care-target="Maintenance" aria-current="${activeView==='care'&&selectedCareType==='Maintenance'}">${icon('route','gold')}<span>Repairs &amp; Service</span></button></div></details>
    <div class="transport-push-slot"></div>${current.reminders.length?`<div class="transport-menu-reminders"><strong>${icon('alert','gold')}Vehicle renewals</strong>${current.reminders.map(r=>`<p>${esc(current.vehicles.find(v=>v.id===r.vehicle_id)?.registration_no||'Vehicle')}: ${esc(r.type)} ${r.date?'renew by '+esc(r.date):'date missing'} ${r.days_remaining!==null?'('+r.days_remaining+' days)':''}</p>`).join('')}</div>`:''}</nav>`+
   (current.routes.length?`<div class="transport-route-picker"><strong>${icon('bus')}Assigned routes &amp; vehicles</strong><div class="transport-route-options">${current.routes.map(r=>`<button type="button" data-route-choice="${esc(r.id)}" aria-pressed="${r.id===selectedRoute}">${esc(r.name)}<small>${esc(current.vehicles.find(v=>v.id===r.vehicle_id)?.registration_no||'Vehicle')}</small></button>`).join('')}</div><small>${current.routes.length} route${current.routes.length===1?'':'s'} assigned to this login</small></div>`:'')+
   (activeView!=='route'?`<button type="button" class="transport-return" data-view="route">← Today's Route</button>`:'')+
   (activeView==='staff'?
    `<section class="transport-card transport-document-section"><h1>${icon('child','green')}${selectedStaff===route?.driver_staff_id?'Driver':'Attendant'} Documents</h1><p>Only documents for staff assigned to this route are shown.</p>${crew.length?`<label>Choose staff member<select data-staff-select>${crew.map(x=>`<option value="${esc(x.id)}" ${x.id===selectedStaff?'selected':''}>${esc(x.name)} · ${x.id===route.driver_staff_id?'Driver':'Helper'}</option>`).join('')}</select></label>`:'<p>No assigned staff.</p>'}${staffDocuments===null?'<p>Loading documents…</p>':`<div class="transport-document-grid">${(selectedStaff===route?.driver_staff_id?['license','aadhaar','id_proof']:['aadhaar','id_proof']).map(type=>{const doc=staffDocuments.find(x=>x.type===type);return `<article class="transport-document-card"><h2>${icon('file')}${docLabels[type]}${type==='license'?' · Required':''}</h2>${doc?`<p>${type==='license'?'Valid until '+esc(doc.expiry_date):'Uploaded '+esc(doc.uploaded_at.slice(0,10))}</p><button type="button" data-staff-document="${esc(doc.id)}">View document</button>`:'<p>Not uploaded by school yet.</p>'}</article>`}).join('')}</div>`}</section>`:
   (activeView==='care'?
    `<section class="transport-card transport-care-card"><h1>${icon('fuel','gold')}Vehicle Care</h1><p class="transport-care-intro"><strong>${esc(vehicle?.registration_no||'Your assigned vehicle')}</strong> · Report a refill, tyre air check or repair to the school. This report does not make a finance entry. After payment, the school confirms it to generate one voucher and one Money Out ledger entry.</p>${route?`<form data-care="${esc(route.vehicle_id)}"><div class="transport-form-fields"><label>Report type<select name="type" required><option ${selectedCareType==='Fuel refill'?'selected':''}>Fuel refill</option><option ${selectedCareType==='Tyre air'?'selected':''}>Tyre air</option><option ${selectedCareType==='Maintenance'?'selected':''}>Maintenance</option></select></label><label data-care-field="odometer">Odometer reading (km)<input name="odometer_km" type="number" min="0" max="9999999" required></label><label data-care-field="litres">Fuel quantity (litres)<input name="litres" type="number" min="0.01" max="500" step="0.01" required></label><label data-care-field="note">Details<input name="note" maxlength="300" placeholder="Fuel station and fuel type"></label><label data-care-field="amount">Expense amount (₹; 0 if no expense)<input name="amount" type="number" min="0" step="0.01" value="0" required></label><label data-care-field="photo">Invoice photo (required when amount is above 0)<input name="photo" type="file" accept="image/*" capture="environment"></label></div><p class="transport-care-help" data-care-help></p><button type="submit">Send report to school</button></form>`:'<p>Ask school to assign a route and vehicle first.</p>'}</section><section class="transport-card"><h2>Recent vehicle care</h2>${careRecords===null?'<p>Loading…</p>':careRecords.length?careRecords.map(c=>`<div class="transport-row"><strong>${esc(c.type)}</strong>${c.odometer_km!=null?' · '+esc(c.odometer_km)+' km':''} · ${esc(c.reported_at||'')}<p>${esc(c.note||'')} ${c.amount_paise?' · ₹'+(c.amount_paise/100).toFixed(2):''} · ${esc(c.voucher_no||c.status)}</p></div>`).join(''):'<p>No reports for this vehicle yet.</p>'}</section>`:
   (activeView==='documents'?
    `<section class="transport-card transport-document-section"><h1>${icon('file','green')}Vehicle Documents</h1><p><strong>${esc(vehicle?.registration_no||'No assigned vehicle')}</strong>${route?' · '+esc(route.name):''}. School uploaded documents for this assigned vehicle.</p>${!route?'<p>Ask your school to assign a route and vehicle.</p>':documents===null?'<p role="status">Loading documents…</p>':documents.length?'<div class="transport-document-grid">'+['insurance','pollution','fitness','tax','rc'].map(type=>{const doc=documents.find(d=>d.type===type);return `<article class="transport-document-card"><h2>${icon('file')}${docLabels[type]}</h2>${doc?`<p>${type==='rc'?'Registration certificate':'Valid until <strong>'+esc(doc.expiry_date)+'</strong>'}</p><button type="button" data-document="${esc(doc.id)}">View document</button>`:'<p>Not uploaded by school yet.</p>'}</article>`}).join('')+'</div>':'<p>No documents uploaded for this vehicle yet. Please contact the school office.</p>'}</section>`:
    `<section class="transport-trip-heading"><div><h1>${icon('route')}Today's Route</h1><p>${esc(route?.name||'Assigned route')} · ${esc(vehicle?.registration_no||'Vehicle pending')}</p></div>${availableTrips.length?`<button type="button" data-open-start="${esc(availableTrips[0].route.id)}" data-direction="${availableTrips[0].direction}" data-run="${availableTrips[0].run}">${icon('bus')}Start a trip</button>`:''}</section>`+
    (route?`<div class="transport-trip-grid">${['Pickup','Drop'].flatMap(direction=>Array.from({length:Number(route.trip_count||1)},(_,i)=>tripCard(route,direction,i+1,Number(route.trip_count||1)))).join('')}</div>`:'<section class="transport-card">No assigned route. Ask your school to assign one.</section>'))))+
   `<div id="transportStartDialog" class="transport-start-dialog" role="dialog" aria-modal="true" aria-labelledby="transportStartTitle" hidden><form id="transportStartForm"><div class="transport-start-top"><h2 id="transportStartTitle">${icon('bus')}Before starting</h2><button type="button" data-close-start aria-label="Close trip start">✕</button></div><div data-start-step="checks"><p>Confirm all three vehicle checks and upload the starting odometer photo.</p><div class="transport-checks"><label><input type="checkbox" name="fuel_ok" required>Fuel checked</label><label><input type="checkbox" name="tyres_ok" required>Tyre air checked</label><label><input type="checkbox" name="condition_ok" required>Vehicle condition checked</label></div><div class="transport-form-fields"><label>Start odometer (km)<input type="number" min="0" name="odometer_km" required></label><label>Start odometer photo<input type="file" accept="image/*" capture="environment" name="photo" required></label></div><button type="button" data-continue-start>Continue to trip selection</button></div><div data-start-step="selection" hidden><p>Choose the assigned route and trip to start.</p><fieldset class="transport-trip-choices"><legend>Assigned trip</legend>${availableTrips.map((t,i)=>`<label><input type="radio" name="trip_choice" value="${i}" ${i===0?'checked':''} required><span><b>${esc(t.route.name)}</b><small>${esc(current.vehicles.find(v=>v.id===t.route.vehicle_id)?.registration_no||'Vehicle')} · ${t.direction==='Pickup'?'Morning pickup':'Return drop'}${Number(t.route.trip_count||1)>1?' · Trip '+t.run:''}</small></span></label>`).join('')}</fieldset><div class="transport-start-actions"><button type="button" data-back-start>← Checks</button><button type="submit">${icon('bus')}Start selected trip</button></div></div></form></div>`+
   `<dialog id="transportDocumentDialog" class="transport-document-dialog" aria-label="Vehicle document"><div class="transport-document-toolbar"><strong data-document-title></strong><button type="button" data-close-document aria-label="Close document">Close ✕</button></div><img alt="" /></dialog>`;
  const oldBar=app.querySelector('.transport-work-bar'),oldTools=app.querySelector('#transportTools');
  const sidebar=document.createElement('nav');sidebar.className='transport-sidebar';sidebar.setAttribute('aria-label','Transport sections');
  sidebar.innerHTML='<a class="transport-sidebar-logo" href="/" aria-label="Neo School India home"><img src="/neo-top-logo.jpeg" alt="Neo School India"></a><div class="transport-sidebar-scroll"></div><button type="button" class="transport-side-signout" id="transportSideSignout">'+icon('route')+'<span>Sign out</span></button>';
  const scroll=sidebar.querySelector('.transport-sidebar-scroll');scroll.append(oldBar,oldTools);
  const hero=document.createElement('div');hero.className='portal-hero transport-portal-hero';
  const alertCount=current.reminders.length+current.trips.reduce((n,t)=>n+(t.events||[]).filter(e=>e.type==='Emergency').length,0);
  hero.innerHTML='<div><span class="eyebrow">NEO · TRANSPORT PORTAL</span><h2>'+esc(current.name)+'</h2><p>'+esc(current.role)+' · '+esc(route?.name||'Assigned routes')+'</p><div class="transport-hero-actions"><span class="portal-pill">'+esc(vehicle?.registration_no||'Vehicle pending')+'</span><button type="button" id="transportHeroBack" '+(viewHistory.length?'':'hidden')+' aria-label="Go back to previous section">← Back</button></div></div><div class="transport-hero-controls"><button type="button" id="transportHeroRefresh" title="Refresh latest updates" aria-label="Refresh latest updates">↻</button><button type="button" id="transportHeroBell" aria-label="'+alertCount+' transport alerts" aria-expanded="false"><svg viewBox="0 0 24 24" width="22" height="22" fill="currentColor" aria-hidden="true"><path d="M12 2a2 2 0 0 0-2 2v.35C7.08 5.2 5 7.9 5 11v4.1l-1.7 2.55A1 1 0 0 0 4.13 19h15.74a1 1 0 0 0 .83-1.55L19 15.1V11c0-3.1-2.08-5.8-5-6.65V4a2 2 0 0 0-2-2Zm-2.35 19a2.5 2.5 0 0 0 4.7 0h-4.7Z"/></svg><span class="transport-alert-count" '+(alertCount?'':'hidden')+'>'+alertCount+'</span></button><img src="/neo%20owl.jpeg" alt="Neo owl" width="85" height="105"></div><div id="transportHeroAlerts" class="transport-hero-alerts" hidden><strong>Transport alerts</strong>'+(current.reminders.map(r=>'<p>'+esc(r.type)+' · '+esc(r.date||'Renewal date pending')+'</p>').join('')+current.trips.flatMap(t=>(t.events||[]).filter(e=>e.type==='Emergency').map(e=>'<p>Emergency · '+esc(t.route_name||'Route')+' · '+esc(e.note||'School notified')+'</p>')).join('')||'<p>No transport alerts.</p>')+'</div>';
  const content=document.createElement('div');content.className='transport-content';content.dataset.view=activeView;for(const node of [...app.childNodes])content.append(node);const routeTitle=content.querySelector(':scope > .transport-trip-heading');if(routeTitle)content.prepend(routeTitle);
  app.append(sidebar,hero,content);
  const startDialog=app.querySelector('#transportStartDialog'),startForm=app.querySelector('#transportStartForm');
  const checksStep=startDialog.querySelector('[data-start-step="checks"]'),selectionStep=startDialog.querySelector('[data-start-step="selection"]');
  document.body.append(startDialog);
  startDialog.querySelector('[data-close-start]').onclick=()=>startDialog.hidden=true;
  startDialog.onkeydown=e=>{if(e.key==='Escape'){e.preventDefault();startDialog.hidden=true}};
  startDialog.querySelector('[data-continue-start]').onclick=()=>{
   const fields=checksStep.querySelectorAll('input');
   for(const field of fields)if(!field.reportValidity())return;
   if(!availableTrips.length){status('No assigned trips are available to start. Refresh the page or contact the school.');return}
   checksStep.hidden=true;selectionStep.hidden=false;startForm.querySelector('input[name="trip_choice"]:checked')?.focus();
  };
  startDialog.querySelector('[data-back-start]').onclick=()=>{selectionStep.hidden=true;checksStep.hidden=false};
  startForm.onsubmit=async e=>{
   e.preventDefault();if(!startForm.reportValidity())return;
   const choice=availableTrips[Number(startForm.elements.namedItem('trip_choice').value)];
   if(!choice){status('Choose an assigned trip.');return}
   const button=e.submitter;button.disabled=true;
   const field=name=>startForm.elements.namedItem(name);
   try{
    await api('driver/start','POST',{route_id:choice.route.id,direction:choice.direction,run_no:choice.run,fuel_ok:field('fuel_ok').checked,tyres_ok:field('tyres_ok').checked,condition_ok:field('condition_ok').checked,odometer_km:Number(field('odometer_km').value),photo:await picture(field('photo').files[0])});
    selectedRoute=choice.route.id;startDialog.hidden=true;await draw();status('Trip started; parent updates are available in the Parent Portal.');
   }catch(err){status(err.message);button.disabled=false}
  };

  sidebar.querySelector('#transportSideSignout').onclick=logout;
  hero.querySelector('#transportHeroRefresh').onclick=()=>draw().then(()=>status('Transport details refreshed.')).catch(err=>status(err.message));
  hero.querySelector('#transportHeroBell').onclick=()=>{const panel=hero.querySelector('#transportHeroAlerts');panel.hidden=!panel.hidden;hero.querySelector('#transportHeroBell').setAttribute('aria-expanded',String(!panel.hidden))};
  hero.querySelector('#transportHeroBack').onclick=()=>{activeView=viewHistory.pop()||'route';render();if(activeView==='documents'&&route)loadDocuments(route.vehicle_id);if(activeView==='care'&&route)loadCare(route.vehicle_id);if(activeView==='staff'&&selectedStaff)loadStaffDocuments(selectedStaff)};
  window.NeoTransportPush?.mount(app.querySelector('.transport-push-slot'),token,'transport');
  app.querySelector('[data-menu-toggle]').onclick=()=>{menuOpen=!menuOpen;render()};
  app.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(activeView!==b.dataset.view)viewHistory.push(activeView);if(b.dataset.staffTarget&&route){const id=b.dataset.staffTarget==='driver'?route.driver_staff_id:route.attendant_staff_id;if(id!==selectedStaff){selectedStaff=id||'';staffDocuments=null}}if(b.dataset.careTarget)selectedCareType=b.dataset.careTarget;activeView=b.dataset.view;menuOpen=true;render();if(activeView==='documents'&&route&&documentVehicle!==route.vehicle_id)loadDocuments(route.vehicle_id);if(activeView==='care'&&route&&careVehicle!==route.vehicle_id)loadCare(route.vehicle_id);if(activeView==='staff'&&selectedStaff)loadStaffDocuments(selectedStaff)});
  app.querySelectorAll('[data-document]').forEach(b=>b.onclick=()=>openDocument(b.dataset.document));
  app.querySelectorAll('[data-staff-document]').forEach(b=>b.onclick=()=>openDocument(b.dataset.staffDocument,'staff'));
  const staffSelect=app.querySelector('[data-staff-select]');if(staffSelect)staffSelect.onchange=()=>loadStaffDocuments(staffSelect.value);
  app.querySelector('[data-close-document]').onclick=()=>app.querySelector('#transportDocumentDialog').close();
  app.querySelector('#transportDocumentDialog').onclose=()=>{if(documentUrl)URL.revokeObjectURL(documentUrl);documentUrl=''};
  app.querySelectorAll('[data-care]').forEach(f=>{
   const type=f.elements.namedItem('type'),field=name=>f.querySelector('[data-care-field="'+name+'"]'),odometer=f.elements.namedItem('odometer_km'),litres=f.elements.namedItem('litres'),note=f.elements.namedItem('note'),amount=f.elements.namedItem('amount'),photo=f.elements.namedItem('photo');
   const update=()=>{const fuel=type.value==='Fuel refill',air=type.value==='Tyre air';field('odometer').hidden=!fuel;odometer.required=fuel;if(!fuel)odometer.value='';field('litres').hidden=!fuel;litres.required=fuel;if(!fuel)litres.value='';note.placeholder=fuel?'Fuel station and fuel type':air?'Air pressure checked or tyre issue':'Repair or service work completed';f.querySelector('[data-care-help]').textContent=fuel?'Enter litres and attach the fuel bill if an expense was incurred.':air?'Record the tyre air check. Enter an amount only if there was a paid service.':'Describe the repair and attach the invoice when reporting an expense.';photo.required=Number(amount.value)>0};
   type.onchange=()=>{selectedCareType=type.value;update()};amount.oninput=update;update();
   f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const values=new FormData(f),paise=Math.round(Number(values.get('amount'))*100);try{if(!Number.isSafeInteger(paise)||paise<0)throw Error('Enter a valid expense amount.');const file=photo.files[0];await api('driver/care','POST',{vehicle_id:f.dataset.care,type:values.get('type'),odometer_km:type.value==='Fuel refill'?Number(values.get('odometer_km')):null,litres:type.value==='Fuel refill'?Number(values.get('litres')):null,amount_paise:paise,note:values.get('note'),photo:file?await picture(file):null});status('Report sent. School will confirm payment before the voucher and ledger entry are posted.');await loadCare(f.dataset.care)}catch(err){status(err.message);e.submitter.disabled=false}};
  });
  app.querySelectorAll('[data-child]').forEach(b=>b.onclick=async()=>{if(b.dataset.morningAbsent==='true'&&b.dataset.event==='Dropped at stop'&&!confirm('Morning pickup was marked Absent for '+byId(b.dataset.child)+'. Have you verified this child is on the return vehicle and confirmed with the parent or attendant?'))return;b.disabled=true;try{await api('driver/event','POST',{trip_id:b.dataset.trip,student_id:b.dataset.child,event_type:b.dataset.event});await draw();status('Child update recorded.')}catch(err){status(err.message);b.disabled=false}});
  app.querySelectorAll('[data-emergency]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const type=f.elements.namedItem('type').value,message=f.elements.namedItem('message').value.trim();if(!confirm('Report '+type+' for this route to the school and parents?'))return;e.submitter.disabled=true;try{await api('driver/emergency','POST',{trip_id:f.dataset.emergency,type,message});await draw();status('Emergency alert sent to school and route parents.')}catch(err){status(err.message);e.submitter.disabled=false}});
  app.querySelectorAll('[data-finish]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const x=name=>f.elements.namedItem(name);try{await api('driver/finish','POST',{trip_id:f.dataset.finish,odometer_km:Number(x('odometer_km').value),photo:await picture(x('photo').files[0])});await draw();status('Trip completed.')}catch(err){status(err.message);e.submitter.disabled=false}});
 }
 async function draw(){current=await api('driver/me');render()}
 document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const b=await api('login','POST',Object.fromEntries(new FormData(e.target)));token=b.token;sessionStorage.setItem(key,token);e.target.reset();await draw()}catch(err){status(err.message)}finally{e.submitter.disabled=false}};
 setInterval(async()=>{if(!token||!current||document.hidden)return;try{const next=await api('driver/me'),previous=current.reminders.length+current.trips.reduce((n,t)=>n+(t.events||[]).filter(e=>e.type==='Emergency').length,0),incoming=next.reminders.length+next.trips.reduce((n,t)=>n+(t.events||[]).filter(e=>e.type==='Emergency').length,0);window.NeoAlertSound?.count('transport:'+next.account_id,incoming);if(incoming!==previous){current=next;render();if(incoming>previous)status('New vehicle or route alert.')}}catch{}},30000);
 document.addEventListener('click',e=>{
  const routeButton=e.target.closest?.('[data-route-choice]');
  if(routeButton&&app.contains(routeButton)){e.preventDefault();const id=routeButton.dataset.routeChoice;if(!current?.routes.some(r=>r.id===id))return;selectedRoute=id;documents=null;documentVehicle='';careRecords=null;careVehicle='';staffDocuments=null;selectedStaff='';render();const route=current.routes.find(r=>r.id===id);if(activeView==='documents')loadDocuments(route.vehicle_id);if(activeView==='care')loadCare(route.vehicle_id);if(activeView==='staff'&&selectedStaff)loadStaffDocuments(selectedStaff);return}
  const button=e.target.closest?.('[data-open-start]');
  if(!button||!app.contains(button))return;
  e.preventDefault();
  status('Opening trip checks…');
  try{
   if(!startChoices.length){status('No trip is ready to start. Ask the school to check child and route assignments.');return}
   const dialog=document.getElementById('transportStartDialog'),form=document.getElementById('transportStartForm');
   if(!dialog||!form)throw Error('Trip checks are unavailable; refresh the page.');
   form.reset();dialog.querySelector('[data-start-step="checks"]').hidden=false;dialog.querySelector('[data-start-step="selection"]').hidden=true;
   const index=startChoices.findIndex(t=>t.route.id===button.dataset.openStart&&t.direction===button.dataset.direction&&t.run===Number(button.dataset.run));
   form.elements.namedItem('trip_choice').value=String(index>=0?index:0);
   dialog.hidden=false;dialog.querySelector('[data-close-start]').focus();status('Trip checks opened.');
  }catch(err){console.error('Transport start popup:',err);status('Unable to open trip checks: '+err.message)}
 },true);
 if(token)draw().catch(err=>{logout();status(err.message)});
})();
