(function(){
 const base='https://neo-lead-crm-api.umakanthgilla.workers.dev',key='neo_transport_token';
 const app=document.getElementById('app'),login=document.getElementById('loginPanel'),message=document.getElementById('message'),loginStatus=document.getElementById('loginStatus'),signOut=document.getElementById('signOut'),staffName=document.getElementById('staffName');
 let token=sessionStorage.getItem(key)||'',current=null,selectedRoute='';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const paths={bus:'<path d="M5 17V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v12H5Z"/><path d="M5 11h14M7 17v3m10-3v3M8 14h.01M16 14h.01"/>',route:'<circle cx="6" cy="18" r="2"/><circle cx="18" cy="6" r="2"/><path d="M8 18h6a4 4 0 0 0 4-4v-6"/>',check:'<path d="M4 12l5 5L20 6"/>',alert:'<path d="M12 3 2 21h20L12 3Z"/><path d="M12 9v5m0 3h.01"/>',child:'<circle cx="12" cy="7" r="3"/><path d="M5 21v-3a7 7 0 0 1 14 0v3"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',fuel:'<path d="M4 20V4h11v16H4Zm0-9h11m0-4 3 2v8a2 2 0 0 0 4 0v-6l-2-2"/>',camera:'<path d="M3 7h4l2-3h6l2 3h4v13H3V7Z"/><circle cx="12" cy="13" r="3"/>'};
 const icon=(name,color='')=>`<span class="transport-icon ${color}" aria-hidden="true"><svg viewBox="0 0 24 24">${paths[name]}</svg></span>`;
 const status=s=>{message.textContent=s;loginStatus.textContent=login.hidden?'':s;clearTimeout(status.timer);status.timer=setTimeout(()=>{message.textContent='';loginStatus.textContent=''},7000)};
 const api=async(path,method='GET',body)=>{const r=await fetch(base+'/api/transport/'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json().catch(()=>({error:'Unreadable response.'}));if(!r.ok)throw Error(d.error||'Transport request failed.');return d};
 const logout=()=>{token='';sessionStorage.removeItem(key);current=null;selectedRoute='';app.hidden=true;login.hidden=false;signOut.hidden=true;staffName.textContent=''};signOut.onclick=logout;
 document.getElementById('togglePassword').onclick=()=>{const input=document.getElementById('transportPassword'),button=document.getElementById('togglePassword'),visible=input.type==='password';input.type=visible?'text':'password';button.setAttribute('aria-label',visible?'Hide password':'Show password');button.title=visible?'Hide password':'Show password';button.setAttribute('aria-pressed',String(visible))};
 document.getElementById('forgotPassword').onclick=()=>{const button=document.getElementById('forgotPassword'),help=document.getElementById('forgotHelp');help.hidden=!help.hidden;button.setAttribute('aria-expanded',String(!help.hidden))};
 async function picture(file){if(!file||!file.type.startsWith('image/'))throw Error('Take a vehicle odometer photo.');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let data=canvas.toDataURL('image/jpeg',.7);if(data.length>205000)data=canvas.toDataURL('image/jpeg',.45);if(data.length>205000)throw Error('Photo is too large. Take a smaller photo.');return data}
 const byId=id=>current.students.find(s=>s.id===id)?.name||id;
 const manifest=(route,run,direction)=>current.assignments.filter(a=>a.route_id===route.id&&Number(a.run_no||1)===run).sort((a,b)=>{const x=route.stops.indexOf(a.stop),y=route.stops.indexOf(b.stop);return(direction==='Drop'?y-x:x-y)||String(a.created_at).localeCompare(String(b.created_at))||a.id.localeCompare(b.id)});
 const absentInMorning=(route,run)=>new Set((current.trips.find(t=>t.route_id===route.id&&t.direction==='Pickup'&&Number(t.run_no||1)===run)?.events||[]).filter(e=>e.type==='Absent').map(e=>e.student_id));
 function tripCard(route,direction,run,count){
  const children=manifest(route,run,direction);if(!children.length)return '';
  const trip=current.trips.find(t=>t.route_id===route.id&&t.direction===direction&&Number(t.run_no||1)===run),morningAbsent=direction==='Drop'?absentInMorning(route,run):new Set();
  const heading=direction==='Pickup'?'Morning pickup':'Return drop';
  return `<article class="transport-row"><h3 class="transport-section-title">${icon(direction==='Pickup'?'child':'bus',direction==='Pickup'?'green':'gold')}${heading}${count>1?' · Trip '+run:''}</h3>`+
   (morningAbsent.size?`<div class="transport-notice transport-warning" role="alert">${icon('alert','gold')}<p><strong>${morningAbsent.size} morning absent:</strong> Confirm whether each child came to school with a parent before return drop. Morning absence does not automatically mark the return trip absent.</p></div>`:'')+
   (trip?`<p>Status: <strong>${esc(trip.status)}</strong> · Start ${esc(trip.odometer_start_km)} km ${trip.odometer_end_km!=null?' · Finish '+esc(trip.odometer_end_km)+' km':''}</p><ol>${children.map(a=>{const event=(trip.events||[]).find(e=>e.student_id===a.student_id&&['Picked up','Dropped at stop','Absent'].includes(e.type)),warn=morningAbsent.has(a.student_id);return `<li class="transport-row"><b>${esc(byId(a.student_id))}</b> · ${esc(a.stop)} ${event?`<span class="transport-badge">${esc(event.type)}</span>`:''}${warn?`<div class="transport-notice transport-warning" role="alert">${icon('alert','gold')}<p><strong>Morning pickup: Absent.</strong> Check with the parent or attendant whether this child is on the return vehicle.</p></div>`:''}${trip.status==='Started'&&!event?`<div class="transport-actions"><button data-child="${esc(a.student_id)}" data-trip="${esc(trip.id)}" data-event="${direction==='Pickup'?'Picked up':'Dropped at stop'}" ${warn?'data-morning-absent="true"':''}>${direction==='Pickup'?'Picked up':warn?'Verify & drop off':'Dropped off'}</button><button class="secondary" data-child="${esc(a.student_id)}" data-trip="${esc(trip.id)}" data-event="Absent">Absent</button></div>`:''}</li>`}).join('')}</ol>${trip.status==='Started'?`<form data-finish="${esc(trip.id)}"><div class="transport-form-fields"><label>Finish odometer (km)<input type="number" min="${esc(trip.odometer_start_km)}" name="odometer_km" required></label><label>Finish odometer photo<input type="file" accept="image/*" capture="environment" name="photo" required></label></div><button>${icon('check')}Finish trip</button></form>`:''}`:
   `<p>${children.length} assigned children.</p><form data-start="${esc(route.id)}" data-direction="${direction}" data-run="${run}"><div class="transport-checks"><label><input type="checkbox" name="fuel_ok" required>Fuel checked</label><label><input type="checkbox" name="tyres_ok" required>Tyre air checked</label><label><input type="checkbox" name="condition_ok" required>Vehicle condition checked</label></div><div class="transport-form-fields"><label>Start odometer (km)<input type="number" min="0" name="odometer_km" required></label><label>Start odometer photo<input type="file" accept="image/*" capture="environment" name="photo" required></label></div><button>${icon('bus')}Start trip</button></form>`)+`</article>`;
 }
 function render(){
  const route=current.routes.find(r=>r.id===selectedRoute)||current.routes[0];selectedRoute=route?.id||'';
  login.hidden=true;app.hidden=false;signOut.hidden=false;staffName.textContent=current.name+' · '+current.role;
  app.innerHTML=`<section class="transport-card transport-hero"><h1>${icon('route')}Today's Route</h1><p>${esc(current.name)} · ${esc(current.role)}. Complete vehicle checks and record each child in stop order.</p></section>`+
   (current.reminders.length?`<section class="transport-card"><h2>${icon('alert','gold')}Vehicle renewals</h2>${current.reminders.map(r=>`<div class="transport-notice">${icon('clock','gold')}<p>${esc(current.vehicles.find(v=>v.id===r.vehicle_id)?.registration_no||'Vehicle')}: ${esc(r.type)} ${r.date?'renew by '+esc(r.date):'date missing'} ${r.days_remaining!==null?'('+r.days_remaining+' days)':''}</p></div>`).join('')}</section>`:'')+
   (current.routes.length>1?`<nav class="transport-route-tabs" aria-label="Assigned routes">${current.routes.map(r=>`<button type="button" data-route="${esc(r.id)}" aria-current="${r.id===selectedRoute}">${icon('bus')}${esc(r.name)}</button>`).join('')}</nav>`:'')+
   (route?`<section class="transport-card"><h2>${icon('bus','green')}${esc(route.name)} <span class="transport-badge">${esc(current.vehicles.find(v=>v.id===route.vehicle_id)?.registration_no||'')}</span></h2><p><strong>Stops:</strong> ${esc(route.stops.join(' → '))}</p><div class="transport-trip-grid">${['Pickup','Drop'].flatMap(direction=>Array.from({length:Number(route.trip_count||1)},(_,i)=>tripCard(route,direction,i+1,Number(route.trip_count||1)))).join('')}</div></section>`:'<section class="transport-card">No assigned route. Ask your school to assign one.</section>');
  app.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{selectedRoute=b.dataset.route;render()});
  app.querySelectorAll('[data-start]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const x=name=>f.elements.namedItem(name);try{await api('driver/start','POST',{route_id:f.dataset.start,direction:f.dataset.direction,run_no:Number(f.dataset.run),fuel_ok:x('fuel_ok').checked,tyres_ok:x('tyres_ok').checked,condition_ok:x('condition_ok').checked,odometer_km:Number(x('odometer_km').value),photo:await picture(x('photo').files[0])});await draw();status('Trip started; parent updates are available in the Parent Portal.')}catch(err){status(err.message);e.submitter.disabled=false}});
  app.querySelectorAll('[data-child]').forEach(b=>b.onclick=async()=>{if(b.dataset.morningAbsent==='true'&&b.dataset.event==='Dropped at stop'&&!confirm('Morning pickup was marked Absent for '+byId(b.dataset.child)+'. Have you verified this child is on the return vehicle and confirmed with the parent or attendant?'))return;b.disabled=true;try{await api('driver/event','POST',{trip_id:b.dataset.trip,student_id:b.dataset.child,event_type:b.dataset.event});await draw();status('Child update recorded.')}catch(err){status(err.message);b.disabled=false}});
  app.querySelectorAll('[data-finish]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const x=name=>f.elements.namedItem(name);try{await api('driver/finish','POST',{trip_id:f.dataset.finish,odometer_km:Number(x('odometer_km').value),photo:await picture(x('photo').files[0])});await draw();status('Trip completed.')}catch(err){status(err.message);e.submitter.disabled=false}});
 }
 async function draw(){current=await api('driver/me');render()}
 document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const b=await api('login','POST',Object.fromEntries(new FormData(e.target)));token=b.token;sessionStorage.setItem(key,token);e.target.reset();await draw()}catch(err){status(err.message)}finally{e.submitter.disabled=false}};
 if(token)draw().catch(err=>{logout();status(err.message)});
})();
