(function(){
 const base='https://neo-lead-crm-api.umakanthgilla.workers.dev',key='neo_transport_token',app=document.getElementById('app'),login=document.getElementById('loginPanel'),message=document.getElementById('message'),signOut=document.getElementById('signOut'),staffName=document.getElementById('staffName');let token=sessionStorage.getItem(key)||'',current=null;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const status=s=>{message.textContent=s;clearTimeout(status.timer);status.timer=setTimeout(()=>message.textContent='',7000)};
 const api=async(path,method='GET',body)=>{const r=await fetch(base+'/api/transport/'+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json().catch(()=>({error:'Unreadable response.'}));if(!r.ok)throw Error(d.error||'Transport request failed.');return d};
 const logout=()=>{token='';sessionStorage.removeItem(key);current=null;app.hidden=true;login.hidden=false;signOut.hidden=true;staffName.textContent=''};signOut.onclick=logout;
 async function picture(file){if(!file||!file.type.startsWith('image/'))throw Error('Take a vehicle odometer photo.');const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let data=canvas.toDataURL('image/jpeg',.7);if(data.length>205000)data=canvas.toDataURL('image/jpeg',.45);if(data.length>205000)throw Error('Photo is too large. Take a smaller photo.');return data}
 const byId=(id)=>current.students.find(s=>s.id===id)?.name||id;
 const manifest=(route,run,direction)=>current.assignments.filter(a=>a.route_id===route.id&&Number(a.run_no||1)===run).sort((a,b)=>{const x=route.stops.indexOf(a.stop),y=route.stops.indexOf(b.stop);return(direction==='Drop'?y-x:x-y)||String(a.created_at).localeCompare(String(b.created_at))||a.id.localeCompare(b.id)});
 async function draw(){current=await api('driver/me');login.hidden=true;app.hidden=false;signOut.hidden=false;staffName.textContent=current.name+' · '+current.role;
  app.innerHTML=`<section class="card"><h1>Today's transport</h1><p>${esc(current.name)} · ${esc(current.role)}. Complete the vehicle checks and record each child in stop order.</p>${current.reminders.map(r=>`<p class="notice">${esc(current.vehicles.find(v=>v.id===r.vehicle_id)?.registration_no||'Vehicle')}: ${esc(r.type)} ${r.date?'renew by '+esc(r.date):'date missing'} ${r.days_remaining!==null?'('+r.days_remaining+' days)':''}</p>`).join('')}</section>`+
   current.routes.map(route=>{const vehicle=current.vehicles.find(v=>v.id===route.vehicle_id),count=Number(route.trip_count||1);return `<section class="card"><h2>${esc(route.name)} <span class="badge">${esc(vehicle?.registration_no||'')}</span></h2><p>Stops: ${esc(route.stops.join(' → '))}</p>${['Pickup','Drop'].flatMap(direction=>Array.from({length:count},(_,i)=>{const run=i+1,children=manifest(route,run,direction),trip=current.trips.find(t=>t.route_id===route.id&&t.direction===direction&&Number(t.run_no||1)===run);if(!children.length)return '';return `<div class="row"><h3>${direction==='Pickup'?'Morning pickup':'Return drop'}${count>1?' · Trip '+run:''}</h3>${trip?`<p>Status: <strong>${esc(trip.status)}</strong> · Start ${esc(trip.odometer_start_km)} km ${trip.odometer_end_km!=null?' · Finish '+esc(trip.odometer_end_km)+' km':''}</p><ol>${children.map(a=>{const event=(trip.events||[]).find(e=>e.student_id===a.student_id&&['Picked up','Dropped at stop','Absent'].includes(e.type));return `<li class="row"><b>${esc(byId(a.student_id))}</b> · ${esc(a.stop)} ${event?'<span class="badge">'+esc(event.type)+'</span>':''}${trip.status==='Started'&&!event?`<div class="actions"><button data-child="${esc(a.student_id)}" data-trip="${esc(trip.id)}" data-event="${direction==='Pickup'?'Picked up':'Dropped at stop'}">${direction==='Pickup'?'Picked up':'Dropped off'}</button><button class="secondary" data-child="${esc(a.student_id)}" data-trip="${esc(trip.id)}" data-event="Absent">Absent</button></div>`:''}</li>`}).join('')}</ol>${trip.status==='Started'?`<form data-finish="${esc(trip.id)}"><label>Finish odometer (km)<input type="number" min="${esc(trip.odometer_start_km)}" name="odometer_km" required></label><label>Finish odometer photo<input type="file" accept="image/*" capture="environment" name="photo" required></label><button>Finish trip</button></form>`:''}`:`<p>${children.length} assigned children.</p><form data-start="${esc(route.id)}" data-direction="${direction}" data-run="${run}"><label><input type="checkbox" name="fuel_ok" required>Fuel checked</label><label><input type="checkbox" name="tyres_ok" required>Tyre air checked</label><label><input type="checkbox" name="condition_ok" required>Vehicle condition checked</label><label>Start odometer (km)<input type="number" min="0" name="odometer_km" required></label><label>Start odometer photo<input type="file" accept="image/*" capture="environment" name="photo" required></label><button>Start trip</button></form>`}</div>`})).join('')}</section>`}).join('')||'<section class="card">No assigned route. Ask your school to assign one.</section>';
  app.querySelectorAll('[data-start]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await api('driver/start','POST',{route_id:f.dataset.start,direction:f.dataset.direction,run_no:Number(f.dataset.run),fuel_ok:f.fuel_ok.checked,tyres_ok:f.tyres_ok.checked,condition_ok:f.condition_ok.checked,odometer_km:Number(f.odometer_km.value),photo:await picture(f.photo.files[0])});await draw();status('Trip started; parent alerts recorded.')}catch(err){status(err.message);e.submitter.disabled=false}});
  app.querySelectorAll('[data-child]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('driver/event','POST',{trip_id:b.dataset.trip,student_id:b.dataset.child,event_type:b.dataset.event});await draw();status('Child update recorded.')}catch(err){status(err.message);b.disabled=false}});
  app.querySelectorAll('[data-finish]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await api('driver/finish','POST',{trip_id:f.dataset.finish,odometer_km:Number(f.odometer_km.value),photo:await picture(f.photo.files[0])});await draw();status('Trip completed.')}catch(err){status(err.message);e.submitter.disabled=false}});
 }
 document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const b=await api('login','POST',Object.fromEntries(new FormData(e.target)));token=b.token;sessionStorage.setItem(key,token);e.target.reset();await draw()}catch(err){status(err.message)}finally{e.submitter.disabled=false}};
 if(token)draw().catch(err=>{logout();status(err.message)});
})();
