(()=>{
const role=document.body.dataset.role,base='https://neo-lead-crm-api.umakanthgilla.workers.dev/api/'+role+'/',key='neo_'+role+'_token';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let token=sessionStorage.getItem(key)||'',data=null,tab='overview',generation=0;
const money=x=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(x/100),status=s=>{$('familyStatus').textContent=s};
function logout(){generation++;token='';data=null;sessionStorage.removeItem(key);$('familyApp').hidden=true;$('familyApp').replaceChildren();$('familyLogout').hidden=true;$('familyLogin').hidden=false}
async function api(path,method='GET',body){const r=await fetch(base+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json().catch(()=>({error:'Unreadable server response.'}));if(!r.ok){if(r.status===401&&path!=='login')logout();throw Error(b.error||'Request failed.')}return b}
async function learningApi(path,body){const r=await fetch('https://neo-lead-crm-api.umakanthgilla.workers.dev/api/learning/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json();if(!r.ok)throw Error(b.error||'Learning request failed.');return b}
async function refresh(silent=false){const stamp=++generation;if(!silent)status('Loading your workspace…');try{const next=await api('me');const kinds=role==='parent'?['feed','timetable','calendar','period-execution']:['feed','plans','timetable','calendar','period-execution'];const responses=await Promise.allSettled(kinds.map(k=>learningApi(k)));next.learning={errors:{}};responses.forEach((r,i)=>{if(r.status==='fulfilled')next.learning[kinds[i]]=r.value;else next.learning.errors[kinds[i]]=r.reason.message});if(stamp!==generation)return;if(silent&&$('reportPreview'))return;if(silent&&JSON.stringify(next)===JSON.stringify(data))return;data=next;$('familyLogin').hidden=true;$('familyLogout').hidden=false;$('familyApp').hidden=false;render();if(!silent)status('Updated: '+new Date().toLocaleTimeString('en-IN')+'. Latest saved school updates loaded.')}catch(e){if(stamp===generation||!token)status(e.message)}}
$('familyLogout').onclick=()=>{logout();status('Signed out.')};
$('familyLoginForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;status('Signing in…');try{const b=await api('login','POST',Object.fromEntries(new FormData(e.target)));token=b.token;sessionStorage.setItem(key,token);e.target.reset();await refresh()}catch(error){status(error.message)}finally{e.submitter.disabled=false}};
const select=(key,label,items)=>`<label>${label}<select name="${key}" required><option value="">Choose…</option>${items.map(([v,t])=>`<option value="${esc(v)}">${esc(t)}</option>`).join('')}</select></label>`;
const card=(title,body)=>`<article class="portal-card"><h3>${esc(title)}</h3>${body}</article>`;
function render(){
 const tabs=role==='parent'?{overview:'Today',calendar:'School calendar',timetable:'Child timetable',activities:'Learning journal',attendance:'Attendance',homework:'Homework',fees:'Fees & receipts',announcements:'School notices',tickets:'Concerns & support',supplies:'Books & uniforms',downloads:'Documents & reports',password:'Password'}:{overview:'Today',calendar:'School calendar',timetable:'My timetable',curriculum:'My curriculum',activities:'Student comments',attendance:'Mark attendance',homework:'Post homework',tasks:'My tasks & reports',announcements:'Announcements',tickets:'Parent concerns',employee_hub:'Employee Hub',downloads:'Documents & reports',password:'Password'};
 $('familyApp').innerHTML=`<div class="portal-hero"><div><span class="eyebrow">NEO · ${role.toUpperCase()} PORTAL</span><h2>${esc(role==='parent'?data.child.name:data.name)}</h2><p>${esc(data.school.name)} · ${esc(data.school.city)}</p><span class="portal-pill">${role==='parent'?esc(data.child.program+' · '+data.child.academic_year):data.classrooms.length+' assigned classrooms'}</span></div><img src="/neo%20owl.jpeg" alt="Neo owl" width="85" height="105"></div><nav class="family-tabs" aria-label="${role} workspace">${Object.entries(tabs).map(([k,v])=>`<button data-tab="${k}" aria-pressed="${k===tab}">${v}</button>`).join('')}<button id="familyRefresh" class="secondary" title="Reload the latest saved school updates. Save any work before refreshing.">Refresh school updates</button><button id="familyDownload" class="secondary">Preview download</button></nav><div id="familyContent"></div>`;
 $('familyApp').querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});$('familyRefresh').onclick=()=>refresh();
 const reportNames={overview:'Learning updates',activities:'Learning updates',attendance:'Attendance',homework:'Homework',fees:'Fee statement',announcements:'School notices',tickets:'Complaint history',supplies:'Books and uniforms',timetable:'Timetable',curriculum:'Curriculum',tasks:'Tasks'};
 const name=reportNames[tab];$('familyDownload').hidden=!name;$('familyDownload').textContent=name?'Preview '+name+' download':'Download';
 $('familyRefresh').title='Reload saved attendance, homework, notices and other school updates. Save any unfinished work first.';
 $('familyDownload').onclick=async()=>{const activeTab=tab;try{
 let rows;
 if(tab==='fees'&&role==='parent')rows=data.invoices.map(i=>{const paid=data.payments.filter(p=>p.invoice_id===i.id).reduce((n,p)=>n+p.amount_paise,0);return {Fee:i.description||i.title||i.fee_head||i.id,Due_date:i.due_date,Assigned_INR:i.amount_paise/100,Received_INR:paid/100,Outstanding_INR:(i.amount_paise-paid)/100}});
 else if(tab==='tickets'){const result=await learningApi('tickets');rows=result.tickets.flatMap(t=>(t.history?.length?t.history:[{}]).map(h=>({Ticket:t.id,Subject:t.subject,Category:t.category,Current_status:t.status,Updated:t.updated_at,History_date:h.date,By:h.actor,Status:h.status,Message:h.message})));}
 else if(tab==='homework')rows=[...(data.learning?.feed?.scheduled_homework||[]),...(data.homework||[])];
 else if(tab==='supplies')rows=[...(data.stock_moves||[]).map(r=>({...r,Record_type:'Issued item'})),...(data.orders||[]).map(r=>({...r,Record_type:'Order'}))];
 else if(tab==='curriculum')rows=(data.learning?.plans?.plans||[]).flatMap(p=>p.lessons.map(l=>({...l,classroom_id:p.classroom_id,date:p.working_dates[l.day-1]})));
 else if(tab==='timetable')rows=[...(data.learning?.timetable?.slots||[]).map(r=>({...r,Schedule:'Weekly'})),...(data.learning?.timetable?.periods||[]).map(r=>({...r,Schedule:'Dated'}))];
 else if(['overview','activities'].includes(tab))rows=data.learning?.feed?.activities;
 else rows=data[tab];
 if(tab!==activeTab)return;
 if(!Array.isArray(rows))throw Error('This report is unavailable. Refresh school updates and try again.');
 if(!rows.length){status('No '+name.toLowerCase()+' records to download yet.');return;}
 const filename='neo-'+role+'-'+tab+'-'+window.neoLocalDateKey(new Date());
 let preview=$('reportPreview');if(preview)preview.remove();preview=document.createElement('section');preview.id='reportPreview';preview.className='neo-report-preview';
 const headers=[...new Set(rows.flatMap(r=>Object.keys(r)))],value=v=>typeof v==='object'?JSON.stringify(v):String(v??'');
 preview.innerHTML=`<h3>${esc(name)} — Excel download</h3><p>${rows.length} rows · File: ${esc(filename)}.xlsx</p><p>Preview of the first 3 records. The download contains all ${rows.length} records.</p><div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,3).map(r=>`<tr>${headers.map(h=>`<td>${esc(value(r[h]))}</td>`).join('')}</tr>`).join('')}</tbody></table></div><button id="confirmReportDownload">Download ${esc(name)} (.xlsx)</button> <button id="closeReportPreview" class="secondary">Close preview</button><p role="status" id="reportDownloadStatus"></p>`;
 $('familyContent').prepend(preview);preview.scrollIntoView({behavior:'smooth'});$('closeReportPreview').onclick=()=>preview.remove();$('confirmReportDownload').onclick=async e=>{e.target.disabled=true;try{await window.neoExport(filename,rows);$('reportDownloadStatus').textContent=name+' download prepared. Check your Downloads folder.'}catch(err){$('reportDownloadStatus').textContent=err.message}finally{e.target.disabled=false}};
 }catch(e){status(e.message)}};
 const area=$('familyContent');
 if(tab==='employee_hub'&&role==='teacher'){
  area.innerHTML=`<div class="learning-welcome"><div><span class="eyebrow">EMPLOYEE HUB</span><h2>Employee Hub</h2><p>Your personal staff services, documents and reports in one place.</p></div></div><div class="portal-grid">${card('HR Desk','<p>Attendance, leave, salary, payslips, advances and recovery — linked to your Staff ID.</p><button class="secondary" data-hr-desk>Open HR Desk</button>')}${card('My Documents','<p>Your staff documents and school-issued records will be available here as the document workflow is connected.</p><span class="portal-pill">Personal documents</span>')}${card('Downloads & Reports','<p>Open your teacher reports and download the records available to your login.</p><button class="secondary" data-employee-downloads>Open downloads & reports</button>')}</div><p class="form-note">HR Desk actions will use your logged-in Staff ID; staff details are never re-entered.</p>`;
  area.querySelector('[data-employee-downloads]').onclick=()=>{tab='downloads';render()};area.querySelector('[data-hr-desk]').onclick=()=>{tab='hr_desk';render()};return
 }
 if(tab==='hr_desk'&&role==='teacher'){
  area.innerHTML='<p>Loading HR Desk…</p>';
  api('hr').then(hr=>{
   const slips=(hr.payroll||[]).slice().sort((a,b)=>String(b.month).localeCompare(String(a.month)));
   area.innerHTML=`<div class="learning-welcome"><div><span class="eyebrow">EMPLOYEE HUB · HR DESK</span><h2>HR Desk</h2><p>Leave, salary advance, attendance and payslips for your linked Staff profile.</p></div></div>
   <div class="portal-grid">${card('Attendance',`<strong class="metric">${(hr.attendance||[]).length}</strong><p>attendance records</p>`)}${card('Leave requests',`<strong class="metric">${(hr.leaves||[]).length}</strong><p>submitted requests</p>`)}${card('Salary advances',`<strong class="metric">${(hr.advances||[]).length}</strong><p>requests / recovery plans</p>`)}</div>
   <div class="portal-grid"><article class="portal-card"><h3>Apply leave</h3><form id="employeeLeave"><label>Leave type<select name="leave_type" required><option>Casual</option><option>Sick</option><option>Earned</option><option>Unpaid</option><option>Other</option></select></label><label>From<input type="date" name="from_date" required></label><label>To<input type="date" name="to_date" required></label><label>Reason<textarea name="reason" required maxlength="1000"></textarea></label><button>Submit leave request</button></form></article>
   <article class="portal-card"><h3>Request salary advance</h3><form id="employeeAdvance"><label>Amount (INR)<input type="number" name="amount" min="1" step=".01" required></label><label>Recovery starts<input type="month" name="recovery_month" required></label><label>Recovery plan<select name="installments" required><option value="1">Next salary — full recovery</option><option value="2">2 months</option><option value="3">3 months</option><option value="custom">Custom installment</option></select></label><label>Reason<textarea name="reason" required maxlength="1000"></textarea></label><button>Submit advance request</button></form></article></div>
   <h3>My requests</h3><div class="portal-grid">${[...(hr.leaves||[]).map(x=>card('Leave · '+x.leave_type,`<p>${esc(x.from_date)} → ${esc(x.to_date)}</p><span class="portal-pill">${esc(x.status)}</span><p>${esc(x.reason||'')}</p>`)),...(hr.advances||[]).map(x=>card('Advance · '+money(x.amount_paise),`<p>Recovery: ${esc(x.installments||1)} month(s) from ${esc(x.recovery_month||'—')}</p><span class="portal-pill">${esc(x.status)}</span><p>${esc(x.reason||'')}</p>`))].join('')||'<p class="portal-empty">No HR requests yet.</p>'}</div>
   <h3>Salary & payslips</h3><div class="portal-grid">${slips.map(x=>card('Salary · '+x.month,`<p>${x.attendance_complete===true?'Final':'Provisional'} · ${esc(x.status||'Draft')}</p><strong>${money(x.net_paise??Math.max(0,(x.gross_paise||0)-(x.deductions_paise||0)))}</strong><p>Gross ${money(x.gross_paise||0)} · Deductions ${money(x.deductions_paise||0)}</p>${x.attendance_complete===true&&['Approved','Paid'].includes(x.status)?'<button class="secondary" data-employee-slip="'+esc(x.id)+'">Payslip</button>':'<small>Payslip available after final attendance and approval.</small>'}`)).join('')||'<p class="portal-empty">No payroll records yet.</p>'}</div>`;
   const leave=area.querySelector('#employeeLeave');leave.onsubmit=async e=>{e.preventDefault();const btn=e.submitter,body=Object.fromEntries(new FormData(e.target));if(body.from_date>body.to_date){status('Leave end date cannot be before the start date.');return}body.request_id=crypto.randomUUID();btn.disabled=true;btn.textContent='Submitting…';try{await api('hr/leave','POST',body);status('✓ Leave request submitted to HR.');render()}catch(err){status(err.message);btn.disabled=false;btn.textContent='Submit leave request'}};
   const adv=area.querySelector('#employeeAdvance');adv.onsubmit=async e=>{e.preventDefault();const btn=e.submitter,body=Object.fromEntries(new FormData(e.target)),amount=Number(body.amount);if(!Number.isFinite(amount)||amount<=0){status('Enter a valid salary advance amount.');return}if(!/^\\d{4}-\\d{2}$/.test(body.recovery_month||'')){status('Choose the recovery start month.');return}if(body.installments==='custom'){const n=Number(prompt('Enter number of monthly installments (1–24):','4'));if(!Number.isInteger(n)||n<1||n>24){status('Custom recovery must be between 1 and 24 monthly installments.');return}body.installments=n}else body.installments=Number(body.installments);body.amount_paise=Math.round(amount*100);delete body.amount;body.request_id=crypto.randomUUID();btn.disabled=true;btn.textContent='Submitting…';try{await api('hr/advance','POST',body);status('✓ Salary advance request submitted to HR for review. Finance release is separate from HR approval.');render()}catch(err){status(err.message);btn.disabled=false;btn.textContent='Submit advance request'}};
   area.querySelectorAll('[data-employee-slip]').forEach(b=>b.onclick=()=>{const x=slips.find(y=>y.id===b.dataset.employeeSlip);if(!x)return;const w=open('','_blank');w.document.write('<!doctype html><title>Salary Payslip</title><h1>'+esc(data.school.name)+'</h1><h2>Salary Payslip · '+esc(x.month)+'</h2><p>'+esc(data.name)+'</p><p>Gross: '+money(x.gross_paise||0)+'</p><p>Deductions: '+money(x.deductions_paise||0)+'</p><p><b>Net: '+money(x.net_paise||0)+'</b></p>');w.document.close();w.print()});
  }).catch(e=>{area.innerHTML='<p class="portal-empty">'+esc(e.message)+'</p>'});return
 }
 if(tab==='downloads'){const items=role==='parent'?
[['Attendance report','attendance'],['Homework report','homework'],['Learning journal','activities'],['Fee statement & receipts','fees'],['School notices','announcements'],['Complaint history','tickets'],['Books & uniforms','supplies'],['Child timetable','timetable']]:
[['Attendance report','attendance'],['Homework records','homework'],['Student comments / learning updates','activities'],['My timetable','timetable'],['Curriculum','curriculum'],['Tasks & reports','tasks'],['Announcements','announcements'],['Parent concerns','tickets']];
 area.innerHTML=`<div class="learning-welcome"><div><span class="eyebrow">DOCUMENTS & REPORTS</span><h2>${role==='parent'?'My child’s downloads':'My reports & downloads'}</h2><p>${role==='parent'?'Only records linked to '+esc(data.child.name)+' are available here.':'Reports are limited to your assigned classrooms, students and teacher work.'}</p></div></div><div class="portal-grid">${items.map(([title,target])=>card(title,`<p>Open the related workspace, review the records, then use its preview/download control.</p><button class="secondary" data-report-target="${target}">Open ${esc(title)}</button>`)).join('')}</div><p class="form-note">Hall tickets and report cards will appear here when the school publishes child-specific documents through the connected document workflow.</p>`;
 area.querySelectorAll('[data-report-target]').forEach(b=>b.onclick=()=>{tab=b.dataset.reportTarget;render()});return}
 if(tab==='calendar'){window.renderNeoCalendar(area,{api:learningApi,state:data.learning.calendar});return}
 if(tab==='timetable'&&role==='parent'){const t=data.learning.timetable;if(!t){area.textContent=data.learning.errors.timetable||'Timetable unavailable';return}area.innerHTML='<h3>Your child’s timetable</h3><label>Date<input id=parentTimetableDate type=date value="'+esc(t.today)+'"></label><div id=parentPeriods></div>';const draw=()=>{const date=area.querySelector('#parentTimetableDate').value;if(!date)return;const dated=(t.periods||[]).filter(p=>p.date===date),slots=dated.length?dated:t.slots.filter(s=>s.weekday===new Date(date+'T00:00:00Z').getUTCDay());area.querySelector('#parentPeriods').innerHTML='<div class=portal-grid>'+slots.slice().sort((a,b)=>a.start.localeCompare(b.start)).map(s=>card(s.subject,`<p>${esc(s.start)}–${esc(s.end)}</p><p>${esc(s.period||s.type||'')}</p>`)).join('')+'</div>'+(slots.length?'':'<p>No periods scheduled.</p>')};area.querySelector('#parentTimetableDate').onchange=draw;draw();return}
 if(tab==='homework'&&role==='parent'){const today=new Date(Date.now()+330*60000).toISOString().slice(0,10),curriculumHomework=(data.learning.feed?.scheduled_homework||[]).slice().sort((a,b)=>(a.date||'').localeCompare(b.date||'')),publishedHomework=(data.homework||[]).slice().sort((a,b)=>{const ac=!a.due_date||a.due_date>=today,bc=!b.due_date||b.due_date>=today;return bc-ac||(a.due_date||'').localeCompare(b.due_date||'')}),dueNow=publishedHomework.filter(h=>!h.due_date||h.due_date>=today).length,pastDue=publishedHomework.filter(h=>h.due_date&&h.due_date<today).length;area.innerHTML=`<div class="learning-welcome"><div><span class="eyebrow">HOME LEARNING</span><h2>Homework</h2><p>Published classroom work and curriculum activities for ${esc(data.child.name)}.</p></div><div><span class="portal-pill">${curriculumHomework.length+publishedHomework.length} available</span> <span class="portal-pill">${dueNow} current</span>${pastDue?` <span class="portal-pill">${pastDue} past due</span>`:''}</div></div><div class="portal-grid">${[...curriculumHomework.map(h=>card(h.subject+' · '+h.topic,`<span class="portal-pill">Curriculum · ${esc(h.date)}</span><p>${esc(h.instructions)}</p>`)),...publishedHomework.map(h=>card(h.title,`<span class="portal-pill">${esc(h.subject||h.homework_type||'Homework')}</span>${h.due_date&&h.due_date<today?'<span class="portal-pill">Past due</span>':''}<p>${esc(h.instructions)}</p>${h.due_date?`<small>Due ${esc(h.due_date)}</small>`:''}`))].join('')||'<p class="portal-empty">No homework has been published for your child yet.</p>'}</div><p class="form-note">Only homework published by the school is shown here.</p>`;return}
 if(tab==='tickets'){window.renderNeoTickets(area,{api:learningApi,role,status});return}
 if(tab==='supplies'){const issued=(data.stock_moves||[]).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')),orders=(data.orders||[]).slice().sort((a,b)=>{const aDone=['Completed','Delivered','Closed','Cancelled'].includes(a.status),bDone=['Completed','Delivered','Closed','Cancelled'].includes(b.status);return aDone-bDone||(b.date||b.created_at||'').localeCompare(a.date||a.created_at||'')}),activeOrders=orders.filter(o=>!['Completed','Delivered','Closed','Cancelled'].includes(o.status)).length;area.innerHTML=`<div class="portal-grid">${card('Items issued',`<strong class="metric">${issued.length}</strong><p>school issue records</p>`)}${card('Orders',`<strong class="metric">${orders.length}</strong><p>${activeOrders} active · ${orders.length-activeOrders} completed/closed</p>`)}</div><h3>Items issued to your child</h3><div class="portal-grid">${issued.map(m=>card(m.item_name,`<span class="portal-pill">${esc(m.type||'Issued')}</span><p>Quantity: ${esc(m.quantity)}</p><p>Size: ${esc(m.size||'—')}</p><small>${esc(m.date||'')}</small>`)).join('')||'<p class="portal-empty">No items issued yet.</p>'}</div><h3>School orders for your child</h3><div class="portal-grid">${orders.map(o=>card(o.item,`<span class="portal-pill">${esc(o.status||'Recorded')}</span><p>${esc(o.category||'School item')} · Quantity ${esc(o.quantity)}</p>${o.date||o.created_at?`<small>Recorded ${esc(o.date||String(o.created_at).slice(0,10))}</small>`:''}`)).join('')||'<p class="portal-empty">No child-linked orders yet.</p>'}</div><p class="form-note">These are school-recorded issue and order records for your child.</p>`;return}
 if(tab==='announcements'){const notices=(data.announcements||[]).slice().sort((a,b)=>(b.date||b.created_at||'').localeCompare(a.date||a.created_at||'')),categories=new Set(notices.map(a=>a.category||'General')).size;area.innerHTML=`<div class="learning-welcome"><div><span class="eyebrow">SCHOOL COMMUNICATION</span><h2>Announcements</h2><p>Official updates published by ${esc(data.school.name)}.</p></div><div><span class="portal-pill">${notices.length} published</span> <span class="portal-pill">${categories} categor${categories===1?'y':'ies'}</span></div></div><div class="portal-grid">${notices.slice(0,50).map(a=>card(a.title,`<span class="portal-pill">${esc(a.category||'General')}</span>${a.date||a.created_at?`<small>${esc(a.date||String(a.created_at).slice(0,10))}</small>`:''}<p style="white-space:pre-wrap">${esc(a.message)}</p>`)).join('')||'<p class="portal-empty">No published announcements yet.</p>'}</div>${notices.length>50?'<p class="form-note">Showing the latest 50 notices. Use Download for the full announcement history.</p>':''}<p class="form-note">This page shows school-published notices only.</p>`;return}
 if(tab==='password'){area.innerHTML='<section class="panel"><h3>Change password</h3><form id="passwordForm"><label>Current password<input type="password" name="current_password" required autocomplete="current-password" maxlength="128"></label><label>New password<input type="password" name="password" required minlength="8" maxlength="128" autocomplete="new-password"></label><button>Change password</button></form></section>';$('passwordForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await api('password','POST',Object.fromEntries(new FormData(e.target)));logout();status('Password changed. Sign in with the new password.')}catch(error){status(error.message);e.submitter.disabled=false}};return}
 if(['overview','activities','timetable','curriculum'].includes(tab)&&window.renderNeoLearningFamily){window.renderNeoLearningFamily(area,{role,tab,data,esc,api:learningApi,refresh,status});return}
 if(role==='teacher'){renderTeacher(area);return}
 const paid=id=>data.payments.filter(p=>p.invoice_id===id).reduce((n,p)=>n+p.amount_paise,0);

 if(tab==='attendance'){const attendance=data.attendance.slice().sort((a,b)=>b.date.localeCompare(a.date)),present=attendance.filter(a=>a.status==='Present').length,absent=attendance.filter(a=>a.status==='Absent').length,leave=attendance.filter(a=>a.status==='Leave').length,total=attendance.length,pct=total?Math.round(present*100/total):0;area.innerHTML=`<div class="portal-grid">${card('Attendance recorded',`<strong class="metric">${total}</strong><p>School days recorded</p>`)}${card('Present',`<strong class="metric">${present}</strong><p>${pct}% of recorded days</p>`)}${card('Absent / Leave',`<strong class="metric">${absent+leave}</strong><p>${absent} absent · ${leave} leave</p>`)}</div><h3>Attendance history</h3><div class="portal-grid">${attendance.slice(0,60).map(a=>card(a.date,`<span class="portal-pill">${esc(a.status)}</span>${a.status==='Absent'?'<p>Absent</p>':a.status==='Leave'?'<p>Leave recorded</p>':''}`)).join('')||'<p class="portal-empty">No attendance has been recorded yet.</p>'}</div>${attendance.length>60?'<p class="form-note">Showing the latest 60 records. Use Download for the full attendance history.</p>':''}<p class="form-note">Attendance shown here is the school’s saved record. Contact the school if a date needs correction.</p>`;}

 if(tab==='fees'){const today=new Date(Date.now()+330*60000).toISOString().slice(0,10),invoices=(data.invoices||[]).slice().sort((a,b)=>{const ab=a.amount_paise-paid(a.id),bb=b.amount_paise-paid(b.id),ap=ab>0,bp=bb>0,ao=ap&&a.due_date&&a.due_date<today,bo=bp&&b.due_date&&b.due_date<today;return bo-ao||bp-ap||(a.due_date||'').localeCompare(b.due_date||'')}),payments=(data.payments||[]).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')),assigned=invoices.reduce((n,i)=>n+i.amount_paise,0),received=invoices.reduce((n,i)=>n+paid(i.id),0),outstanding=Math.max(0,assigned-received),dueCount=invoices.filter(i=>i.amount_paise-paid(i.id)>0).length,overdueCount=invoices.filter(i=>i.amount_paise-paid(i.id)>0&&i.due_date&&i.due_date<today).length;area.innerHTML=`<div class="portal-grid">${card('Total assigned',`<strong class="metric">${money(assigned)}</strong><p>School fee requests</p>`)}${card('Received',`<strong class="metric">${money(received)}</strong><p>Payments recorded by school</p>`)}${card('Outstanding',`<strong class="metric">${money(outstanding)}</strong><p>${dueCount} fee request${dueCount===1?'':'s'} with balance${overdueCount?` · ${overdueCount} overdue`:''}</p>`)}</div><h3>Fee requests</h3><div class="portal-grid">${invoices.map(i=>card(i.title,`<span class="portal-pill">${i.amount_paise-paid(i.id)<=0?'Paid':i.due_date&&i.due_date<today?'Overdue':'Payment due'}</span><p>Due ${esc(i.due_date)}</p><p>Amount: ${money(i.amount_paise)}</p><p>Received: ${money(paid(i.id))}</p><strong>Balance: ${money(Math.max(0,i.amount_paise-paid(i.id)))}</strong>`)).join('')||'<p class="portal-empty">No fee requests yet.</p>'}</div><h3>Payments recorded by school</h3><div class="portal-grid">${payments.map(p=>card(money(p.amount_paise),`<p>${esc(p.date)} · ${esc(p.method)}</p><p>Reference: ${esc(p.reference)}</p><small>Receipt ID: ${esc(p.id)}</small>`)).join('')||'<p class="portal-empty">No receipts yet.</p>'}</div><p class="form-note">These figures reflect payments recorded by the school. Contact the school for corrections or payment questions.</p>`;} 
}
function renderTeacher(area){
 if(tab==='tasks'){
 const today=new Date(Date.now()+330*60000).toISOString().slice(0,10),tasks=(data.tasks||[]).slice().sort((a,b)=>{const aDone=['Completed','Not completed'].includes(a.status),bDone=['Completed','Not completed'].includes(b.status),ao=!aDone&&a.due_date&&a.due_date<today,bo=!bDone&&b.due_date&&b.due_date<today;return aDone-bDone||bo-ao||(a.due_date||'').localeCompare(b.due_date||'')}),open=tasks.filter(t=>!['Completed','Not completed'].includes(t.status)),completed=tasks.filter(t=>t.status==='Completed').length,notCompleted=tasks.filter(t=>t.status==='Not completed').length,overdue=open.filter(t=>t.due_date&&t.due_date<today).length,dueToday=open.filter(t=>t.due_date===today).length;
 area.innerHTML=`<div class="portal-grid">${card('Open tasks',`<strong class="metric">${open.length}</strong><p>awaiting your outcome${overdue?` · ${overdue} overdue`:''}${dueToday?` · ${dueToday} due today`:''}</p>`)}${card('Completed',`<strong class="metric">${completed}</strong><p>${notCompleted} not completed</p>`)}</div><h3>My tasks & report deadlines</h3><div class="portal-grid">${tasks.map(t=>`<article class="portal-card"><h3>${esc(t.title)}</h3><span class="portal-pill">${esc(t.status)}</span>${!['Completed','Not completed'].includes(t.status)&&t.due_date&&t.due_date<today?'<span class="portal-pill">Overdue</span>':t.due_date===today?'<span class="portal-pill">Due today</span>':''}<p>Due ${esc(t.due_date)}</p><p>${esc(t.instructions)}</p>${(t.history||[]).slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(h=>`<p>${esc(h.date)} · ${esc(h.status)}: ${esc(h.comment)}</p>`).join('')}${['Completed','Not completed'].includes(t.status)?'<p class="form-note">Outcome saved. This task is locked unless the school assigns or reopens it.</p>':`<form data-task="${esc(t.id)}">${select('status','Outcome',[['Completed','Completed'],['Not completed','Not completed']])}<label>Completion note / reason<textarea name="comment" required maxlength="1000"></textarea></label><button>Save outcome</button></form>`}</article>`).join('')||'<p class="portal-empty">No assigned tasks.</p>'}</div>`;
 area.querySelectorAll('[data-task]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;const t=data.tasks.find(t=>t.id===f.dataset.task);try{await api('tasks','POST',{...Object.fromEntries(new FormData(f)),id:t.id,revision:t.revision});await refresh();status('Task outcome saved.')}catch(err){status(err.message);e.submitter.disabled=false}});return;
 }

 const name=id=>data.students.find(s=>s.id===id)?.name||id;
 if(tab==='overview'){const today=new Date(Date.now()+330*60000).toISOString().slice(0,10),todayAttendance=(data.attendance||[]).filter(a=>a.date===today),recorded=new Set(todayAttendance.map(a=>a.student_id)).size,pendingAttendance=Math.max(0,data.students.length-recorded),openTaskRows=(data.tasks||[]).filter(t=>!['Completed','Not completed'].includes(t.status)),openTasks=openTaskRows.length,overdueTasks=openTaskRows.filter(t=>t.due_date&&t.due_date<today).length,dueTodayTasks=openTaskRows.filter(t=>t.due_date===today).length;area.innerHTML=`<div class="learning-welcome"><div><span class="eyebrow">TEACHER DASHBOARD</span><h2>My classrooms today</h2><p>${esc(today)} · ${data.classrooms.length} assigned classrooms</p></div><span class="portal-pill">${data.students.length} students</span></div><div class="portal-grid">${card('Attendance today',`<strong class="metric">${recorded}/${data.students.length}</strong><p>assigned students recorded · ${pendingAttendance} pending</p>`)}${card('Open tasks',`<strong class="metric">${openTasks}</strong><p>awaiting an outcome${overdueTasks?` · ${overdueTasks} overdue`:''}${dueTodayTasks?` · ${dueTodayTasks} due today`:''}</p>`)}</div><h3>Assigned classrooms</h3><div class="portal-grid">${data.classrooms.slice().sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''))).map(c=>card(c.name,`<p>${esc(c.program)} · ${esc(c.academic_year)}</p><strong class="metric">${data.students.filter(s=>s.classroom_id===c.id).length}</strong><p>Assigned students · ${Math.max(0,data.students.filter(s=>s.classroom_id===c.id).length-new Set(todayAttendance.filter(a=>data.students.some(s=>s.id===a.student_id&&s.classroom_id===c.id)).map(a=>a.student_id)).size)} attendance pending</p>`)).join('')||'<p class="portal-empty">Ask your school administrator to assign a classroom.</p>'}</div><h3>Your students</h3><div class="portal-grid">${data.students.slice().sort((a,b)=>{const ac=data.classrooms.find(c=>c.id===a.classroom_id)?.name||'',bc=data.classrooms.find(c=>c.id===b.classroom_id)?.name||'';return ac.localeCompare(bc)||String(a.name||'').localeCompare(String(b.name||''))}).map(s=>card(s.name,`<p>${esc(s.program)} · ${esc(data.classrooms.find(c=>c.id===s.classroom_id)?.name||'Assigned classroom')}</p>`)).join('')||'<p class="portal-empty">No students assigned yet.</p>'}</div>`;return}
 if(tab==='attendance'){
 const attendance=data.attendance.slice().sort((a,b)=>b.date.localeCompare(a.date)),today=new Date(Date.now()+330*60000).toISOString().slice(0,10),todayRows=attendance.filter(a=>a.date===today),todayPresent=todayRows.filter(a=>a.status==='Present').length,todayAbsent=todayRows.filter(a=>a.status==='Absent').length,todayLeave=todayRows.filter(a=>a.status==='Leave').length,classroomSummary=data.classrooms.slice().sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''))).map(c=>{const students=data.students.filter(s=>s.classroom_id===c.id),ids=new Set(students.map(s=>s.id)),rows=todayRows.filter(a=>ids.has(a.student_id));const recorded=new Set(rows.map(a=>a.student_id)).size;return {name:c.name,total:students.length,recorded,pending:Math.max(0,students.length-recorded),present:rows.filter(a=>a.status==='Present').length,absent:rows.filter(a=>a.status==='Absent').length,leave:rows.filter(a=>a.status==='Leave').length}}),todayRecorded=new Set(todayRows.map(a=>a.student_id)).size,todayPending=Math.max(0,data.students.length-todayRecorded),todayComplete=data.students.length>0&&todayPending===0;
 area.innerHTML=`<div class="portal-grid">${card('Today recorded',`<strong class="metric">${todayRecorded}</strong><p>of ${data.students.length} assigned students · ${todayComplete?'Attendance complete':todayPending+' pending'}</p>`)}${card('Present today',`<strong class="metric">${todayPresent}</strong><p>${todayAbsent} absent · ${todayLeave} leave</p>`)}</div><h3>Today by classroom</h3><div class="portal-grid">${classroomSummary.map(c=>card(c.name,`<strong class="metric">${c.recorded}/${c.total}</strong><p>recorded · ${c.pending} pending · ${c.present} present · ${c.absent} absent · ${c.leave} leave</p>`)).join('')||'<p class="portal-empty">No classrooms assigned.</p>'}</div><section class="panel"><h3>Record attendance</h3><form id="teacherForm"><div class="fields">${select('student_id','Student',data.students.slice().sort((a,b)=>{const ac=data.classrooms.find(c=>c.id===a.classroom_id)?.name||'',bc=data.classrooms.find(c=>c.id===b.classroom_id)?.name||'';return ac.localeCompare(bc)||String(a.name||'').localeCompare(String(b.name||''))}).map(s=>[s.id,`${s.name} · ${data.classrooms.find(c=>c.id===s.classroom_id)?.name||s.program||'Classroom'}`]))}<label>Date<input type="date" name="date" required></label>${select('status','Attendance',['Present','Absent','Leave'].map(x=>[x,x]))}</div><button>Save attendance</button></form><p class="form-note">Saved attendance is visible to this child’s parent. Saving again updates the same student and date.</p></section><h3>Recent attendance</h3><div class="portal-grid">${attendance.slice(0,30).map(a=>card(name(a.student_id),`<span class="portal-pill">${esc(a.status)}</span><p>${esc(a.date)} · ${esc(data.classrooms.find(c=>c.id===data.students.find(s=>s.id===a.student_id)?.classroom_id)?.name||'Assigned classroom')}</p>`)).join('')||'<p class="portal-empty">No attendance has been recorded yet.</p>'}</div>${attendance.length>30?'<p class="form-note">Showing the latest 30 records. Use Download for the full attendance history.</p>':''}`;
 const date=new Date(Date.now()+330*60000).toISOString().slice(0,10);area.querySelector('[name=date]').value=date;area.querySelector('[name=date]').max=date;
 }else if(tab==='homework'){const today=new Date(Date.now()+330*60000).toISOString().slice(0,10),homework=(data.homework||[]).slice().sort((a,b)=>{const ac=!a.due_date||a.due_date>=today,bc=!b.due_date||b.due_date>=today;return bc-ac||(a.due_date||'').localeCompare(b.due_date||'')}),published=homework.filter(h=>h.published).length,drafts=homework.length-published,current=homework.filter(h=>!h.due_date||h.due_date>=today).length;area.innerHTML=`<div class="portal-grid">${card('Homework saved',`<strong class="metric">${homework.length}</strong><p>${current} current · ${published} published · ${drafts} draft</p>`)}</div><section class="panel"><h3>Classroom homework</h3><form id="teacherForm"><div class="fields">${select('classroom_id','Classroom',data.classrooms.slice().sort((a,b)=>String(a.name||'').localeCompare(String(b.name||''))).map(c=>[c.id,c.name]))}${select('subject','Subject',['English','Early maths','Environment','Art','Physical development','Telugu','Hindi','Other'].map(x=>[x,x]))}${select('homework_type','Homework type',['Reading','Story / conversation','Counting','Drawing','Practical activity','Revision','Worksheet','Other'].map(x=>[x,x]))}<label>Today’s topic<input name="topic" required maxlength="200"></label><label>Title<input name="title" required maxlength="200"></label><label>Due date<input name="due_date" type="date" min="${today}" required></label></div><label>Instructions<textarea name="instructions" required maxlength="2000" rows="4"></textarea></label><label class="check"><input type="checkbox" name="published">Publish to parents now</label><button>Save homework</button></form><p class="form-note">Drafts stay internal. Published homework is visible to parents of the selected classroom.</p></section><h3>Saved homework</h3><div class="portal-grid">${homework.map(h=>card(h.title,`<span class="portal-pill">${h.published?'Published to parents':'Draft'}</span>${h.due_date&&h.due_date<today?'<span class="portal-pill">Past due</span>':''}<p>${esc(h.subject||h.homework_type||'Homework')}${h.topic?' · '+esc(h.topic):''}</p><p>${esc(h.instructions)}</p><small>Due ${esc(h.due_date)} · ${esc(data.classrooms.find(c=>c.id===h.classroom_id)?.name||'Assigned classroom')}</small>`)).join('')||'<p class="portal-empty">No homework saved yet.</p>'}</div>`;} 
 const form=$('teacherForm');if(form){let id=crypto.randomUUID();form.onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;const b=Object.fromEntries(new FormData(form));b.request_id=id;if(tab==='homework')b.published=b.published==='on';try{await api(tab,'POST',b);id=crypto.randomUUID();await refresh();status(tab==='attendance'?'Attendance saved. Saving this student and date again will update the existing record.':'Saved. Published updates are available in the parent portal.')}catch(error){status(error.message);button.disabled=false}}}
}
// Refresh on return to the page, without interrupting a form in progress.
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&token&&role==='parent'&&!['password','tickets'].includes(tab))refresh(true)});
setInterval(()=>{if(token&&role==='parent'&&!document.hidden&&!['password','tickets'].includes(tab))refresh(true)},30000);
if(token)refresh();
})();

