(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const apiBase='https://neo-lead-crm-api.umakanthgilla.workers.dev';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const labelClass=c=>[c?.program,c?.name&&c?.name!==c?.program?('Section '+c.name):'',c?.academic_year].filter(Boolean).join(' · ');
const uniq=a=>[...new Set(a.filter(Boolean))];
const shuffle=a=>a.slice().sort(()=>Math.random()-.5);
window.renderNeoAssessmentEngine=async function(area,ctx){
 const {tab,records:r,call,status,school,token,refresh}=ctx,classes=r.classrooms||[],bank=r.question_bank||[],tests=r.online_tests||[],attempts=r.online_test_attempts||[];
 const learning=async path=>{const res=await fetch(apiBase+'/api/learning/'+path+'?school_id='+encodeURIComponent(school.school_id),{headers:{Authorization:'Bearer '+token}}),b=await res.json();if(!res.ok)throw Error(b.error||'Learning data unavailable.');return b};
 let feed={activities:[]},plans={plans:[]};try{[feed,plans]=await Promise.all([learning('feed'),learning('plans')])}catch(_e){}
 const completed=Array.isArray(feed.activities)?feed.activities:[],planRows=Array.isArray(plans.plans)?plans.plans:[];
 const lessonFor=x=>{const p=planRows.find(p=>p.id===x.plan_id);return p?.lessons?.find(l=>String(l.id)===String(x.lesson_id))||x};
 const completedRows=completed.map(x=>({...x,...lessonFor(x)}));
 const chapterOf=x=>String(x.chapter||x.unit||x.concept||'Topic').trim();
 if(tab==='teaching_progress'){
  const byClass=classes.map(c=>{const rows=completedRows.filter(x=>x.classroom_id===c.id),subjects=uniq(rows.map(x=>x.subject));return {c,rows,subjects}});
  area.innerHTML='<span class="eyebrow">ACADEMICS · TEACHING</span><h3>Teaching progress / chapter completion</h3><p>Teacher-confirmed completed curriculum is the source for Question Bank and Online Tests. Planned lessons are not treated as completed.</p><div class="portal-grid">'+byClass.map(({c,rows,subjects})=>'<article class="portal-card"><h3>'+esc(labelClass(c)||c.id)+'</h3><strong class="metric">'+rows.length+'</strong><p>completed concepts · '+subjects.length+' subjects</p><details><summary>View completed topics</summary>'+subjects.map(s=>'<p><b>'+esc(s)+'</b><br>'+esc(uniq(rows.filter(x=>x.subject===s).map(chapterOf)).slice(0,20).join(' · ')||'—')+'</p>').join('')+'</details></article>').join('')+'</div>';
  return;
 }
 if(tab==='question_bank'){
  const classOpts=classes.map(c=>'<option value="'+esc(c.id)+'">'+esc(labelClass(c)||c.id)+'</option>').join('');
  area.innerHTML='<span class="eyebrow">ASSESSMENT · QUESTION BANK</span><h3>Question Bank</h3><p>Generate drafts only from teacher-confirmed completed curriculum. Review every generated question before approving it for tests.</p>'+
  '<section class="panel"><h3>Generate from completed chapters</h3><div class="fields"><label>Classroom<select id="qbClass"><option value="">Choose classroom…</option>'+classOpts+'</select></label><label>Subject<select id="qbSubject"><option value="">Choose class first…</option></select></label><label>Difficulty<select id="qbDifficulty"><option>Mixed</option><option>Basic</option><option>Medium</option><option>Hard</option></select></label></div><div id="qbTopics" class="portal-card"><p>Select class and subject.</p></div><button type="button" id="qbGenerate">Generate draft questions</button></section>'+
  '<section class="panel"><h3>Add / author question</h3><form id="qbManual"><div class="fields"><label>Classroom<select name="classroom_id" required><option value="">Choose…</option>'+classOpts+'</select></label><label>Subject<input name="subject" required maxlength="120"></label><label>Chapter<input name="chapter" required maxlength="180"></label><label>Topic<input name="topic" maxlength="180"></label><label>Difficulty<select name="difficulty"><option>Basic</option><option>Medium</option><option>Hard</option></select></label><label>Question type<select name="question_type"><option>MCQ</option><option>True / False</option><option>Fill in the Blank</option><option>Short Answer</option></select></label><label>Marks<input name="marks" type="number" min="1" max="20" value="1"></label></div><label>Question<textarea name="question_text" required maxlength="1200"></textarea></label><label>MCQ options — one per line<textarea name="options_text" placeholder="Option A\nOption B\nOption C\nOption D"></textarea></label><label>Correct answer<textarea name="correct_answer" maxlength="500"></textarea></label><button>Save draft question</button></form></section>'+
  '<section class="panel"><div style="display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap"><div><h3 style="margin-bottom:4px">Bank records</h3><p style="margin:0">Review in a compact list, select only the questions you want, then approve together.</p></div><div class="actions"><button type="button" id="qbApproveSelected">Approve selected</button><button type="button" class="secondary" id="qbDraftSelected">Return selected to draft</button></div></div><div class="fields" style="margin-top:14px"><label>Search<input id="qbSearch" type="search" placeholder="Question, subject, chapter"></label><label>Status<select id="qbStatus"><option value="">All</option><option>Draft</option><option>Approved</option></select></label><label>Difficulty<select id="qbFilterDifficulty"><option value="">All</option><option>Basic</option><option>Medium</option><option>Hard</option></select></label><label>Type<select id="qbFilterType"><option value="">All</option><option>MCQ</option><option>True / False</option><option>Fill in the Blank</option><option>Short Answer</option></select></label></div><div id="qbSelectionSummary" class="portal-system-note"><strong>0 selected</strong><span>Select questions below. You can approve or return them to draft in one action.</span></div><div id="qbList"></div></section>';
  const classSel=area.querySelector('#qbClass'),subSel=area.querySelector('#qbSubject'),topicBox=area.querySelector('#qbTopics');
  const redrawSubjects=()=>{const rows=completedRows.filter(x=>x.classroom_id===classSel.value),subs=uniq(rows.map(x=>x.subject));subSel.innerHTML='<option value="">Choose subject…</option>'+subs.map(s=>'<option>'+esc(s)+'</option>').join('');topicBox.innerHTML='<p>Choose subject.</p>'};
  classSel.onchange=redrawSubjects;
  subSel.onchange=()=>{const rows=completedRows.filter(x=>x.classroom_id===classSel.value&&x.subject===subSel.value),topics=uniq(rows.map(chapterOf));topicBox.innerHTML=topics.length?'<label><input type="checkbox" id="qbAll"> Select all completed topics</label><div class="portal-grid">'+topics.map(t=>'<label class="portal-card"><input type="checkbox" data-qb-topic value="'+esc(t)+'"> <strong>'+esc(t)+'</strong></label>').join('')+'</div>':'<p>No completed topics found.</p>';const all=topicBox.querySelector('#qbAll');if(all)all.onchange=()=>topicBox.querySelectorAll('[data-qb-topic]').forEach(x=>x.checked=all.checked)};
  area.querySelector('#qbGenerate').onclick=async e=>{const cid=classSel.value,subject=subSel.value,diff=area.querySelector('#qbDifficulty').value,topics=[...topicBox.querySelectorAll('[data-qb-topic]:checked')].map(x=>x.value);if(!cid||!subject||!topics.length)return status('Choose class, subject and at least one completed topic.');const rows=completedRows.filter(x=>x.classroom_id===cid&&x.subject===subject&&topics.includes(chapterOf(x)));if(!rows.length)return status('No completed lesson data found.');e.target.disabled=true;try{let count=0;const allConcepts=uniq(completedRows.filter(x=>x.classroom_id===cid&&x.subject===subject).map(chapterOf));for(const row of rows.slice(0,20)){const chapter=chapterOf(row),levels=diff==='Mixed'?['Basic','Medium','Hard']:[diff];for(const level of levels){let qtype='Short Answer',question='',answer='',options=[];if(level==='Basic'){qtype='MCQ';question=row.objective?'Which topic best matches this learning objective: "'+row.objective+'"?':'Which topic was completed in this lesson?';answer=chapter;options=shuffle(uniq([chapter,...allConcepts.filter(x=>x!==chapter)]).slice(0,4));while(options.length<2)options.push('None of these');if(!options.includes(chapter))options[0]=chapter;}else if(level==='Medium'){question=row.question_1||row.question_2||('Explain '+chapter+' in your own words.');}else{question=row.question_3||row.question_2||('Apply '+chapter+' to a new example and explain your reasoning.');}await call('question_bank','POST',{request_id:crypto.randomUUID(),classroom_id:cid,subject,chapter,topic:row.concept||chapter,difficulty:level,question_type:qtype,question_text:question,options,correct_answer:answer,marks:level==='Hard'?2:1,status:'Draft',source:'Completed curriculum',source_lesson_id:String(row.lesson_id||row.id||'')});count++;}}status('✓ '+count+' draft questions generated. Review before approval.');await refresh()}catch(err){status(err.message);e.target.disabled=false}};
  const manual=area.querySelector('#qbManual');manual.onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(manual));b.request_id=crypto.randomUUID();b.marks=Number(b.marks);b.options=b.options_text.split('\n').map(x=>x.trim()).filter(Boolean);delete b.options_text;b.status='Draft';b.source='Manual';e.submitter.disabled=true;try{await call('question_bank','POST',b);status('✓ Draft question saved.');await refresh()}catch(err){status(err.message);e.submitter.disabled=false}};
  const search=area.querySelector('#qbSearch'),statusFilter=area.querySelector('#qbStatus'),difficultyFilter=area.querySelector('#qbFilterDifficulty'),typeFilter=area.querySelector('#qbFilterType'),summary=area.querySelector('#qbSelectionSummary');
  const selected=new Set();
  const filtered=()=>bank.filter(q=>{
    const term=(search.value||'').trim().toLowerCase();
    if(term&&!([q.question_text,q.subject,q.chapter,q.topic].join(' ').toLowerCase().includes(term)))return false;
    if(statusFilter.value&&q.status!==statusFilter.value)return false;
    if(difficultyFilter.value&&q.difficulty!==difficultyFilter.value)return false;
    if(typeFilter.value&&q.question_type!==typeFilter.value)return false;
    return true;
  });
  const syncSummary=()=>{summary.innerHTML='<strong>'+selected.size+' selected</strong><span>'+esc(filtered().length)+' questions shown · choose only what you want to approve.</span>'};
  const draw=()=>{const rows=filtered().slice(0,150);area.querySelector('#qbList').innerHTML=rows.length?'<div class="table-wrap"><table class="neo-ledger-table"><thead><tr><th style="width:42px"><input type="checkbox" id="qbSelectAll" aria-label="Select all visible"></th><th style="width:120px">Level / Type</th><th>Question</th><th style="width:180px">Subject / Chapter</th><th style="width:90px">Marks</th><th style="width:110px">Status</th><th style="width:100px">Preview</th></tr></thead><tbody>'+rows.map((q,i)=>'<tr><td><input type="checkbox" data-qb-select="'+esc(q.id)+'" '+(selected.has(q.id)?'checked':'')+'></td><td><span class="eyebrow">'+esc(q.difficulty)+'</span><br><small>'+esc(q.question_type)+'</small></td><td><b>'+esc(q.question_text.length>150?q.question_text.slice(0,150)+'…':q.question_text)+'</b></td><td>'+esc(q.subject)+'<br><small>'+esc(q.chapter)+'</small></td><td>'+esc(q.marks)+'</td><td><b>'+esc(q.status)+'</b></td><td><button type="button" class="secondary" data-qb-preview="'+esc(q.id)+'">View</button></td></tr><tr data-qb-detail="'+esc(q.id)+'" hidden><td colspan="7"><div class="portal-card"><p><b>Full question:</b> '+esc(q.question_text)+'</p>'+(q.options?.length?'<p><b>Options:</b> '+q.options.map(esc).join(' · ')+'</p>':'')+'<p><b>Correct answer:</b> '+esc(q.correct_answer||'Teacher review')+'</p><p><b>Source:</b> '+esc(q.source||'—')+' · <b>Topic:</b> '+esc(q.topic||q.chapter||'—')+'</p></div></td></tr>').join('')+'</tbody></table></div>':'<p class="portal-empty">No questions match these filters.</p>';
    area.querySelectorAll('[data-qb-select]').forEach(x=>x.onchange=()=>{x.checked?selected.add(x.dataset.qbSelect):selected.delete(x.dataset.qbSelect);syncSummary()});
    const all=area.querySelector('#qbSelectAll');if(all){const visible=rows.map(x=>x.id);all.checked=visible.length>0&&visible.every(id=>selected.has(id));all.onchange=()=>{visible.forEach(id=>all.checked?selected.add(id):selected.delete(id));draw();syncSummary()}};
    area.querySelectorAll('[data-qb-preview]').forEach(b=>b.onclick=()=>{const row=area.querySelector('[data-qb-detail="'+CSS.escape(b.dataset.qbPreview)+'"]');row.hidden=!row.hidden;b.textContent=row.hidden?'View':'Hide'});
    syncSummary();
  };
  const updateQ=async(id,state)=>{const q=bank.find(x=>x.id===id);await call('question_bank/'+id,'PATCH',{status:state,question_text:q.question_text,correct_answer:q.correct_answer||'',marks:q.marks||1})};
  const batchUpdate=async state=>{const ids=[...selected];if(!ids.length)return status('Select at least one question first.');const button=state==='Approved'?area.querySelector('#qbApproveSelected'):area.querySelector('#qbDraftSelected');button.disabled=true;try{for(const id of ids)await updateQ(id,state);status('✓ '+ids.length+' question'+(ids.length===1?'':'s')+' '+(state==='Approved'?'approved':'returned to draft')+'.');selected.clear();await refresh()}catch(err){status(err.message);button.disabled=false}};
  area.querySelector('#qbApproveSelected').onclick=()=>batchUpdate('Approved');
  area.querySelector('#qbDraftSelected').onclick=()=>batchUpdate('Draft');
  [search,statusFilter,difficultyFilter,typeFilter].forEach(el=>el.addEventListener(el===search?'input':'change',draw));
  draw();return;
 }
 if(tab==='online_tests'){
  const classOpts=classes.map(c=>'<option value="'+esc(c.id)+'">'+esc(labelClass(c)||c.id)+'</option>').join('');
  area.innerHTML='<span class="eyebrow">ASSESSMENT · ONLINE TESTS</span><h3>Create & publish online test</h3><p>Only approved Question Bank items can be published. Mixed selection uses approximately 40% Basic, 40% Medium and 20% Hard when enough questions are available.</p><section class="panel"><form id="testForm"><div class="fields"><label>Classroom<select name="classroom_id" id="testClass" required><option value="">Choose…</option>'+classOpts+'</select></label><label>Subject<select name="subject" id="testSubject" required><option value="">Choose class first…</option></select></label><label>Difficulty<select name="difficulty" id="testDifficulty"><option>Mixed</option><option>Basic</option><option>Medium</option><option>Hard</option></select></label><label>No. of questions<input name="count" type="number" min="1" max="100" value="10"></label><label>Duration (minutes)<input name="duration_minutes" type="number" min="5" max="180" value="20"></label><label>Attempts<input name="attempts_allowed" type="number" min="1" max="5" value="1"></label><label>Start date<input name="start_date" type="date" value="'+today()+'" required></label><label>Due date<input name="due_date" type="date" value="'+today()+'" required></label></div><label>Test title<input name="title" required maxlength="180" placeholder="Science Weekly Test"></label><div id="testChapters" class="portal-card"><p>Choose class and subject.</p></div><label><input type="checkbox" name="show_result" checked> Show auto-evaluated result after submission</label><button>Create & publish test</button></form></section><h3>Published / draft tests</h3><div class="portal-grid">'+(tests.map(t=>'<article class="portal-card"><span class="eyebrow">'+esc(t.status)+'</span><h3>'+esc(t.title)+'</h3><p>'+esc(t.subject)+' · '+esc((t.chapters||[]).join(', '))+'</p><p>'+esc((t.question_ids||[]).length)+' questions · '+esc(t.duration_minutes)+' min · '+esc(t.start_date)+' → '+esc(t.due_date)+'</p></article>').join('')||'<p class="portal-empty">No online tests yet.</p>')+'</div>';
  const cs=area.querySelector('#testClass'),ss=area.querySelector('#testSubject'),chap=area.querySelector('#testChapters');
  const update=()=>{const approved=bank.filter(q=>q.status==='Approved'&&q.classroom_id===cs.value),subs=uniq(approved.map(q=>q.subject));ss.innerHTML='<option value="">Choose subject…</option>'+subs.map(s=>'<option>'+esc(s)+'</option>').join('');chap.innerHTML='<p>Choose subject.</p>'};
  cs.onchange=update;ss.onchange=()=>{const rows=bank.filter(q=>q.status==='Approved'&&q.classroom_id===cs.value&&q.subject===ss.value),chs=uniq(rows.map(q=>q.chapter));chap.innerHTML=chs.length?'<label><input type="checkbox" id="testAll"> Select all chapters</label><div class="portal-grid">'+chs.map(x=>'<label class="portal-card"><input type="checkbox" data-test-chapter value="'+esc(x)+'"> '+esc(x)+'</label>').join('')+'</div>':'<p>No approved questions for this subject.</p>';const a=chap.querySelector('#testAll');if(a)a.onchange=()=>chap.querySelectorAll('[data-test-chapter]').forEach(x=>x.checked=a.checked)};
  area.querySelector('#testForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),b=Object.fromEntries(fd),chapters=[...chap.querySelectorAll('[data-test-chapter]:checked')].map(x=>x.value);if(!chapters.length)return status('Select at least one chapter.');const count=Math.max(1,Math.min(100,Number(b.count)||10)),pool=bank.filter(q=>q.status==='Approved'&&q.classroom_id===b.classroom_id&&q.subject===b.subject&&chapters.includes(q.chapter));let selected=[];if(b.difficulty==='Mixed'){const basic=shuffle(pool.filter(q=>q.difficulty==='Basic')),medium=shuffle(pool.filter(q=>q.difficulty==='Medium')),hard=shuffle(pool.filter(q=>q.difficulty==='Hard'));selected=[...basic.slice(0,Math.ceil(count*.4)),...medium.slice(0,Math.ceil(count*.4)),...hard.slice(0,Math.max(1,Math.floor(count*.2)))];selected=uniq(selected.map(q=>q.id)).map(id=>pool.find(q=>q.id===id));if(selected.length<count)selected=[...selected,...shuffle(pool.filter(q=>!selected.some(x=>x.id===q.id))).slice(0,count-selected.length)]}else selected=shuffle(pool.filter(q=>q.difficulty===b.difficulty)).slice(0,count);if(!selected.length)return status('Not enough approved questions for this selection. Approve Question Bank items first.');e.submitter.disabled=true;try{await call('online_tests','POST',{request_id:crypto.randomUUID(),title:b.title,classroom_id:b.classroom_id,subject:b.subject,chapters,difficulty:b.difficulty,question_ids:selected.map(q=>q.id),duration_minutes:Number(b.duration_minutes),attempts_allowed:Number(b.attempts_allowed),start_date:b.start_date,due_date:b.due_date,show_result:fd.has('show_result'),status:'Published'});status('✓ Online test published with '+selected.length+' questions.');await refresh()}catch(err){status(err.message);e.submitter.disabled=false}};
  return;
 }
 if(tab==='test_analytics'){
  const byTest=tests.map(t=>{const a=attempts.filter(x=>x.test_id===t.id),scores=a.filter(x=>Number(x.total_marks)>0).map(x=>Math.round(Number(x.auto_score||0)/Number(x.total_marks)*100)),avg=scores.length?Math.round(scores.reduce((n,x)=>n+x,0)/scores.length):0,pending=a.filter(x=>x.status==='Pending review').length;return {t,a,avg,pending}});
  area.innerHTML='<span class="eyebrow">ASSESSMENT · ANALYTICS</span><h3>Online test results & chapter analytics</h3><p>Auto-scored questions are summarized immediately. Short answers remain clearly marked for teacher review.</p><div class="portal-grid">'+(byTest.map(({t,a,avg,pending})=>'<article class="portal-card"><h3>'+esc(t.title)+'</h3><strong class="metric">'+a.length+'</strong><p>attempts · average auto score '+avg+'%</p><p>Pending short-answer review: <b>'+pending+'</b></p><details><summary>Student attempts</summary>'+a.slice(0,40).map(x=>'<p>'+esc(x.student_name||x.student_id)+' · '+esc(x.auto_score)+'/'+esc(x.total_marks)+' · '+esc(x.status)+'</p>').join('')+'</details></article>').join('')||'<p class="portal-empty">No attempts recorded yet.</p>')+'</div>';return;
 }
};
})();