/* Password visibility and administrator-assisted recovery. No credentials are transmitted here. */
(()=>{
'use strict';
const style=document.createElement('style');style.textContent=`.neo-password-field{display:flex!important;align-items:center;gap:8px;min-width:0}.neo-password-field input{flex:1;min-width:0;width:100%}.neo-eye{display:inline-flex!important;align-items:center;justify-content:center;flex:0 0 44px;width:44px!important;min-height:44px;padding:8px!important;border:1px solid #cbd7ed!important;border-radius:12px!important;background:#eef4ff!important;color:#102052!important}.neo-eye:focus-visible{outline:3px solid #008fbd;outline-offset:2px}.neo-eye svg{width:23px;height:23px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.neo-recovery{margin:18px 0;padding:14px;border:1px solid #dbe4f4;border-radius:14px;background:#f7faff;color:#102052}.neo-recovery summary{cursor:pointer;font-weight:700}.neo-recovery p{line-height:1.6}.neo-recovery textarea{box-sizing:border-box;width:100%;min-height:100px;padding:10px;font:inherit}.neo-recovery button{margin-top:10px}`;document.head.append(style);
const pairs=new Set();
function paint(input,button){const visible=input.type==='text';button.setAttribute('aria-label',visible?'Hide password':'Show password');button.title=visible?'Hide password':'Show password';button.setAttribute('aria-pressed',String(visible));button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>'+(visible?'':'<path d="m3 3 18 18"/>')+'</svg>'}
function enhance(){document.querySelectorAll('input[type="password"]').forEach(input=>{if(input.dataset.neoEye||input.closest('.password-wrap'))return;input.dataset.neoEye='true';if(input.autocomplete==='new-password'||input.getAttribute('autocomplete')==='new-password'){input.minLength=8;input.pattern='(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9\\s]).{8,128}';input.title='8–128 characters: uppercase, lowercase, number and symbol';}const wrap=document.createElement('span');wrap.className='neo-password-field';input.before(wrap);wrap.append(input);const button=document.createElement('button');button.type='button';button.className='neo-eye';wrap.append(button);pairs.add({input,button});paint(input,button);button.onclick=()=>{input.type=input.type==='password'?'text':'password';paint(input,button);input.focus()}})}
function hide(){for(const pair of pairs){if(!pair.input.isConnected){pairs.delete(pair);continue}pair.input.type='password';paint(pair.input,pair.button)}}
document.addEventListener('visibilitychange',()=>{if(document.hidden)hide()});document.addEventListener('submit',hide,true);document.addEventListener('reset',hide,true);
enhance();new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});
const form=document.querySelector('#familyLoginForm')||document.querySelector('#loginForm');if(!form)return;
const role=document.body.dataset.role||'school',school=role==='school';
const details=document.createElement('details');details.className='neo-recovery';details.innerHTML='<summary>Forgot password?</summary><p>'+(school?'Head office can reset your school password after verifying your identity.':'Your school administrator can reset your '+role+' password after verifying your identity.')+'</p><p>Enter your '+(school?'School ID':'login ID')+' above, then copy the request below and send it through your usual private contact with '+(school?'head office':'the school office')+'. Do not include your password.</p><textarea readonly aria-label="Password reset request"></textarea><button type="button">Copy reset request</button><p role="status">No request has been sent automatically. After the administrator resets your password, return here and sign in with the new one.</p>';
form.after(details);const request=details.querySelector('textarea'),status=details.querySelector('[role="status"]');
function update(){const id=form.querySelector('[name="account_id"],[name="school_id"]')?.value.trim()||'[enter your login ID]';request.value='Please help me reset my Neo School India '+role+' login password. My login ID is '+id+'. Please verify my identity and share the replacement password privately.'}
details.addEventListener('toggle',()=>{if(details.open)update()});form.addEventListener('input',update);details.querySelector('button').onclick=async()=>{update();try{await navigator.clipboard.writeText(request.value);status.textContent='Copied. Send this request privately to '+(school?'head office.':'your school administrator.')}catch{request.focus();request.select();status.textContent='Select and copy the request, then send it privately to your administrator.'}};
})();
