/* Neo school workspace. Uses existing school/head-office sessions. */
(()=>{
const root=document.createElement('section');root.id='neoWorkspace';root.hidden=true;document.querySelector('main').insertBefore(root,document.getElementById('detail'));
let school=null,tab='dashboard',records={},errors={},generation=0,loading=false;
const learningTabs=['curriculum','timetable','learning_report'];
const names={dashboard:'Overview',curriculum:'Curriculum & calendar',timetable:'Teacher timetable',learning_report:'Learning report',students:'Students',classrooms:'Classrooms',fee_structures:'Fee structures',homework:'Homework',announcements:'Parent notices',parent_access:'Parent access',teacher_access:'Teacher access',teacher_tasks:'Teacher tasks & reports',enquiries:'Enquiries',attendance:'Attendance',invoices:'Assigned fees',payments:'Collect payment',inventory:'Inventory',reports:'Reports & Excel',tickets:'Parent concerns',orders:'Orders',ledger:'Head-office payments',support:'Support'};
const classes=['Playgroup','Nursery','LKG','UKG','Daycare'];
const money=x=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(x/100);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const student=id=>records.students?.find(x=>x.id===id);
const label=r=>student(r.student_id)?.name||r.student_id;
const paid=id=>(records.payments||[]).filter(p=>p.invoice_id===id).reduce((n,p)=>n+p.amount_paise,0);
async function call(kind,method='GET',data,id=''){
 const requestToken=token;
 const r=await fetch(BASE+'/api/portal/'+encodeURIComponent(school.school_id)+'/'+kind+(id?'/'+encodeURIComponent(id):''),{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});
 const b=await r.json().catch(()=>({error:'The server returned an unreadable response.'}));if(!r.ok){if(r.status===401&&token===requestToken){window.closeNeoWorkspace();document.getElementById('logout').click()}throw Error(r.status===404?'This feature requires the latest CRM Worker. Ask head office to deploy portal v2.':b.error||'Request failed.');}return b;
}
async function loadRecords(){const stamp=++generation;loading=true;renderContent();const keys=Object.keys(names).filter(k=>k!=='dashboard'&&!learningTabs.includes(k)&&!['inventory','reports','tickets'].includes(k));keys.push('stock_items','stock_moves');const results=await Promise.allSettled(keys.map(async k=>[k,await call(k)]));if(stamp!==generation)return false;errors={};results.forEach((result,i)=>{const k=keys[i];if(result.status==='fulfilled'){records[k]=result.value[1].records||result.value[1].accounts||[]}else{errors[k]=result.reason.message;delete records[k]}});loading=false;renderContent();return !errors[tab]}
window.openNeoWorkspace=s=>{school=s;tab='dashboard';records={};errors={};root.hidden=false;root.innerHTML=`<div class="portal-hero"><div><span class="eyebrow">LEARN · GROW · LEAD</span><h2>${esc(s.name)}</h2><p>Your people. Your classrooms. Your school.</p><span class="portal-pill">${esc(s.city)} · ${mode==='admin'?'Head-office view':'School administrator'}</span></div><img src="/neo%20owl.jpeg" alt="Neo owl" width="100" height="120"></div><nav aria-label="School workspace">${Object.entries(names).map(([k,v])=>`<button data-tab="${k}" aria-pressed="${k===tab}"><span class="nav-dot" aria-hidden="true"></span>${v}</button>`).join('')}</nav><div id="portalStatus" role="status" aria-live="polite"></div><div id="portalContent"></div>`;root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderContent()});loadRecords()};
window.closeNeoWorkspace=()=>{generation++;school=null;records={};errors={};loading=false;root.hidden=true;root.replaceChildren()};
const input=(key,title,type='text',required=true)=>`<label>${title}<input name="${key}" type="${type}" ${required?'required':''} ${type==='number'?'min="1" step="1"':''} ${type==='text'?'maxlength="200"':''}></label>`;
const select=(key,title,options)=>`<label>${title}<select name="${key}" required><option value="">Choose…</option>${options.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}">${esc(t)}</option>`}).join('')}</select></label>`;
const chooseStudent=()=>select('student_id','Student',(records.students||[]).map(s=>[s.id,s.name+' · '+s.program]));
const amount=()=>'<label>Amount (INR)<input name="amount" type="number" min="0.01" max="1000000" step="0.01" required></label>';
const notes=()=>'<label>Notes<textarea name="notes" maxlength="1000" rows="3"></textarea></label>';
const chooseClassroom=(required=true)=>select('classroom_id','Classroom',(records.classrooms||[]).map(c=>[c.id,c.name+' · '+c.program+' · '+c.academic_year])).replace('required',required?'required':'');
const publish=()=>'<label class="check"><input type="checkbox" name="published">Publish to parents now</label>';
function fields(){switch(tab){
case 'teacher_tasks':return select('teacher_id','Teacher',(records.teacher_access||[]).filter(t=>t.active).map(t=>[t.account_id,t.name]))+input('title','Task / report name')+input('due_date','Due date','date')+'<label>Responsibilities / preparation<textarea name="instructions" required maxlength="2000"></textarea></label>';
case 'classrooms':return input('name','Classroom / section name')+select('program','Programme',classes)+input('academic_year','Academic starting year','number')+input('teacher','Class teacher name')+input('capacity','Room capacity','number');
case 'fee_structures':return chooseClassroom()+input('title','Fee / instalment name')+amount()+input('due_date','Due date','date');
case 'homework':return chooseClassroom()+select('subject','Subject',['English','Early maths','Environment','Art','Physical development','Telugu','Hindi','Other'])+input('topic',"Today’s topic")+select('homework_type','Homework type',['Reading','Story / conversation','Counting','Drawing','Practical activity','Revision','Worksheet','Other'])+input('title','Activity title')+'<label>Instructions<textarea name="instructions" required maxlength="2000" rows="4"></textarea></label>'+input('due_date','Due date','date')+publish();
case 'announcements':return select('category','Announcement type',['General','Holiday','Reopening','Timing change','PTM','Celebration','Event','Assessment','Field trip','Materials reminder','Other'])+select('audience','Audience',['Parents and teachers','Teachers only'])+chooseClassroom(false)+input('title','Notice title')+'<label>Message<textarea name="message" required maxlength="2000" rows="4"></textarea></label>'+publish();

case 'students':return chooseClassroom(false)+input('name','Child name')+input('dob','Date of birth','date')+select('gender','Gender',['Male','Female','Prefer not to say'])+input('email','Parent email','email',false)+select('program','Class',classes)+input('academic_year','Academic starting year','number')+input('parent','Parent / guardian name')+input('mobile','Parent phone','tel')+select('nursery_status','Previous Nursery',['Not applicable','Completed','In progress','Not attended'])+select('lkg_status','Previous LKG',['Not applicable','Completed','In progress','Not attended'])+input('previous_school','Previous school','text',false)+input('previous_city','Previous school city','text',false);
case 'enquiries':return input('name','Parent name')+input('mobile','Parent phone','tel')+input('child_name','Child name')+select('program','Class of interest',classes)+input('follow_up','Follow-up date','date')+notes();
case 'attendance':return chooseStudent()+input('date','Attendance date','date')+select('status','Status',['Present','Absent','Leave']);
case 'invoices':return chooseStudent()+input('title','Fee / instalment name')+amount()+input('due_date','Due date','date');
case 'payments':return select('invoice_id','Fee request',(records.invoices||[]).map(i=>[i.id,label(i)+' · '+i.title+' · balance '+money(i.amount_paise-paid(i.id))]))+amount()+input('date','Payment date','date')+select('method','Method',['Cash','UPI','Bank transfer','Cheque'])+input('reference','Receipt / transaction reference');
case 'orders':return select('order_for','Order for',['School stock','Classroom','Child'])+chooseClassroom(false)+chooseStudent().replace('required','')+select('category','Category',['Books','Student kits','Uniforms'])+input('item','Item / class / edition')+input('size','Uniform size','text',false)+input('quantity','Quantity','number')+notes();
case 'ledger':return amount()+input('date','Payment date','date')+input('reference','Bank / UPI transaction reference')+notes();
case 'support':return input('subject','Subject')+notes();
}}
function renderContent(){
 root.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tab===tab));
 (root.querySelector('#portalStatus')||{}).textContent='';const area=root.querySelector('#portalContent');
 if(loading&&!Object.keys(records).length){area.innerHTML='<div class="portal-empty">Loading your school workspace…</div>';return}
 if(learningTabs.includes(tab)){window.renderNeoLearning(area,{tab,school,token,mode,classrooms:records.classrooms||[],teachers:records.teacher_access||[]});return}
 if(['payments','inventory','reports'].includes(tab)&&(['students','classrooms','invoices','payments',...(tab==='inventory'?['stock_items','stock_moves']:[])].some(k=>errors[k]))){area.innerHTML='<p class="portal-error">Required records could not load. Return to Overview and refresh before continuing.</p>';return}
 if(['payments','inventory','reports'].includes(tab)){window.renderNeoOperations(area,{tab,records,call,refresh:loadRecords,status:portalNotice});return}
 if(tab==='tickets'){const api=async(path,body)=>{const r=await fetch(BASE+'/api/learning/'+path+'?school_id='+encodeURIComponent(school.school_id),{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json();if(!r.ok)throw Error(b.error);return b};window.renderNeoTickets(area,{api,role:mode,status:portalNotice,teachers:records.teacher_access||[]});return}
 if(errors[tab]){area.innerHTML=`<div class="portal-error"><h3>${names[tab]} could not load</h3><p>${esc(errors[tab])}</p><button id="retryPortal">Retry connection</button></div>`;area.querySelector('button').onclick=loadRecords;return}
 if(tab==='parent_access'||tab==='teacher_access'){renderAccess(area);return}

 if(tab==='dashboard'){
 if(['students','invoices','payments','attendance','orders','enquiries'].some(k=>!records[k])){area.innerHTML=`<div class="portal-error"><h3>Some school records could not load</h3><p>${esc(Object.entries(errors).map(([k,e])=>names[k]+': '+e).join(' · '))}</p><button id="retryPortal">Retry connection</button><p>You can still open the other sections.</p></div>`;area.querySelector('button').onclick=loadRecords;return}
 const fees=records.invoices.reduce((a,i)=>a+Math.max(0,i.amount_paise-paid(i.id)),0);
 const metrics=[['Students',records.students.length],['Present today',records.attendance.filter(a=>a.date===today()&&a.status==='Present').length],['Fees outstanding',money(fees)],['Open orders',records.orders.filter(o=>!['Delivered','Cancelled'].includes(o.status)).length],['Follow-ups due',records.enquiries.filter(e=>e.follow_up<=today()&&!['Converted','Lost'].includes(e.status)).length]];
 area.innerHTML=`<div class="portal-tools"><button id="refreshPortal">Refresh records</button></div><div class="portal-grid">${metrics.map(([k,v])=>`<article class="portal-card"><p>${k}</p><strong class="metric">${esc(v)}</strong></article>`).join('')}</div><article class="portal-card" style="margin-top:16px"><h3>Today’s work</h3><p>Record attendance, review fee balances and contact parents. Place book, kit and uniform requests from Orders.</p><p>Fee receipts are school-recorded entries. Head-office payments remain pending until verified. Online checkout and automatic messaging are not connected in this version.</p></article>`;area.querySelector('#refreshPortal').onclick=loadRecords;return;
 }
 const help={teacher_tasks:'Assign a preparation task, activity or report deadline. The teacher sees it in My tasks and records completion or a reason.',classrooms:'Create classroom sections and academic years. Assign students and teacher accounts to the right classroom.',fee_structures:'Create one instalment for a classroom. It is assigned automatically to existing and newly added students in that classroom. Apply again to backfill older structures without duplicates.',homework:'Published activities appear in the parent portal for this classroom. Drafts stay within the school.',announcements:'Publish notices to one classroom, or leave classroom blank for all parents in this school.',students:'Register confirmed students. Class selection requires school review; this form does not automatically approve admission.',enquiries:'Record enquiries handled by this school. Website enquiries remain in the head-office CRM until an assignment workflow is connected.',attendance:'Saving again for the same student and date updates attendance.',invoices:'Create a fee request for each instalment. Existing financial records cannot be edited here.',payments:'Record money already received. This does not collect an online payment. Check references before submitting.',orders:'Head office will confirm product availability, pricing and dispatch. Submitting a request does not place a paid purchase.',ledger:'Record a payment already made to head office. Head office verifies the reference; no online payment is taken here.',support:'Send an operational support request to head office. For urgent help, use your usual direct contact.'};
 area.innerHTML=`<h3>${names[tab]}</h3><p>${help[tab]}</p><details class="portal-editor" ${!(records[tab]||[]).length?'open':''}><summary>＋ Add ${tab==='classrooms'?'classroom':tab==='fee_structures'?'fee structure':tab==='homework'?'homework':tab==='announcements'?'parent notice':tab==='payments'?'payment receipt':tab==='invoices'?'fee request':tab==='ledger'?'payment record':tab==='students'?'student':tab==='attendance'?'attendance':tab==='orders'?'order request':tab==='support'?'support request':'enquiry'}</summary><form id="portalForm"><div class="fields">${fields()}</div><button type="submit">Save ${tab==='orders'?'request':'record'}</button></form></details><label>Search ${names[tab].toLowerCase()}<input id="portalFilter" type="search" placeholder="Search names, references or status"></label><div id="portalRecords" class="portal-grid"></div>`;
 if(tab==='students'){const form=area.querySelector('#portalForm');form.elements.classroom_id.onchange=()=>{const c=(records.classrooms||[]).find(c=>c.id===form.elements.classroom_id.value);if(c){form.elements.program.value=c.program;form.elements.academic_year.value=c.academic_year}}}
 let requestId=crypto.randomUUID();
 area.querySelector('#portalForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;(root.querySelector('#portalStatus')||{}).textContent='Saving…';const b=Object.fromEntries(new FormData(e.target));b.request_id=requestId;if('published' in b)b.published=true;else if(['homework','announcements'].includes(tab))b.published=false;if(b.capacity)b.capacity=Number(b.capacity);if(b.amount){b.amount_paise=Math.round(Number(b.amount)*100);delete b.amount}if(b.quantity)b.quantity=Number(b.quantity);try{await call(tab,'POST',b);requestId=crypto.randomUUID();await loadRecords();(root.querySelector('#portalStatus')||{}).textContent='Record saved.'}catch(error){(root.querySelector('#portalStatus')||{}).textContent=error.message;button.disabled=false}};
 area.querySelector('#portalFilter').oninput=e=>renderCards(e.target.value);renderCards('');
}
function renderCards(query){
 const area=root.querySelector('#portalRecords');const list=records[tab].filter(r=>(JSON.stringify(r)+' '+label(r)).toLowerCase().includes(query.toLowerCase()));
 area.innerHTML=list.length?list.map(r=>{
 const s=tab==='students'?r:student(r.student_id);const phone=tab==='enquiries'?r.mobile:s?.mobile;
 let title=r.name||r.subject||r.item||r.title||label(r)||r.reference||r.id;
 let lines=[];
 if(tab==='teacher_tasks')lines=[(records.teacher_access||[]).find(t=>t.account_id===r.teacher_id)?.name,r.instructions,'Due: '+r.due_date,r.status,...(r.history||[]).map(h=>h.date+' · '+h.status+': '+h.comment)];
 if(tab==='classrooms')lines=[r.program+' · '+r.academic_year,'Teacher: '+r.teacher,'Capacity: '+r.capacity,'Assigned students: '+(records.students||[]).filter(s=>s.classroom_id===r.id).length];
 if(tab==='fee_structures')lines=[classroomName(r.classroom_id),money(r.amount_paise),'Due: '+r.due_date];
 if(tab==='homework')lines=[classroomName(r.classroom_id),r.instructions,'Due: '+r.due_date,r.published?'Published to parents':'Draft'];
 if(tab==='announcements')lines=[r.classroom_id?classroomName(r.classroom_id):'All school parents',r.message,r.published?'Published to parents':'Draft'];
 if(tab==='students')lines=[r.program+' · '+r.academic_year,'Classroom: '+classroomName(r.classroom_id),'DOB: '+r.dob,'Parent: '+r.parent,'Phone: '+r.mobile,'Previous school: '+(r.previous_school||'Not recorded'),'Nursery: '+r.nursery_status+' · LKG: '+r.lkg_status];
 if(tab==='enquiries')lines=[r.child_name+' · '+r.program,'Follow-up: '+r.follow_up,r.status,r.notes,r.office_note];
 if(tab==='attendance')lines=[r.date,r.status];
 if(tab==='invoices')lines=[label(r),'Due: '+r.due_date,'Fee: '+money(r.amount_paise),'Received: '+money(paid(r.id)),'Outstanding: '+money(r.amount_paise-paid(r.id)),r.amount_paise<=paid(r.id)?'Paid':r.due_date<today()?'Overdue':'Upcoming / due today'];
 if(tab==='payments')lines=[money(r.amount_paise)+' · '+r.method,r.date,'Reference: '+r.reference,'Receipt ID: '+r.id,r.status];
 if(tab==='orders')lines=[r.category+' · '+r.quantity+' items','Size: '+(r.size||'—'),'For: '+(r.child_name||r.classroom_name||r.order_for||'School stock'),r.status,r.notes,r.office_note];
 if(tab==='ledger')lines=[money(r.amount_paise),r.date,'Reference: '+r.reference,r.status,r.notes,r.office_note];
 if(tab==='support')lines=[r.notes,r.status,r.office_note];
 const tel=(phone||'').replace(/[^+0-9]/g,'');
 return `<article class="portal-card"><h3>${esc(title)}</h3>${lines.filter(Boolean).map(l=>`<p>${esc(l)}</p>`).join('')}<div class="portal-tools">${phone?`<a href="tel:${esc(tel)}">Call parent</a>`:''}${tab==='invoices'?`<button class="secondary" data-remind="${esc(r.id)}">Copy reminder</button>`:''}${tab==='students'?`<button class="secondary" data-profile="${esc(r.id)}">View summary</button><button class="secondary" data-assign="${esc(r.id)}">Assign classroom</button>`:''}${tab==='fee_structures'?`<button data-apply="${esc(r.id)}">Apply to classroom</button>`:''}${['homework','announcements'].includes(tab)?`<button data-publish="${esc(r.id)}">${r.published?'Unpublish':'Publish'}</button>`:''}${(tab==='enquiries'||mode==='admin'&&['orders','ledger','support'].includes(tab))?`<button class="secondary" data-update="${esc(r.id)}">Update status</button>`:''}</div><div data-extra="${esc(r.id)}"></div></article>`;
 }).join(''):'<p class="portal-empty">No matching records. Add your first record above.</p>';
 wireExtras(area);
 area.querySelectorAll('[data-remind]').forEach(b=>b.onclick=async()=>{const i=records.invoices.find(x=>x.id===b.dataset.remind);const balance=i.amount_paise-paid(i.id);const box=b.closest('article').querySelector('[data-extra]');if(balance<=0){box.textContent='No payment is due for this fee request.';return}const text=`Dear parent, ${school.name} reminds you that ${money(balance)} is due for ${label(i)} — ${i.title}, due ${i.due_date}. Please contact the school if you have already paid. Thank you.`;box.textContent=text;try{await navigator.clipboard.writeText(text);(root.querySelector('#portalStatus')||{}).textContent='Reminder copied. Review and send through your messaging app. Nothing has been sent automatically.'}catch{(root.querySelector('#portalStatus')||{}).textContent='Copy the reminder shown on the card and send through your messaging app.'}});
 area.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{const id=b.dataset.profile;const invoices=records.invoices.filter(x=>x.student_id===id);const at=records.attendance.filter(x=>x.student_id===id);b.closest('article').querySelector('[data-extra]').innerHTML=`<hr><p>Attendance entries: ${at.length} · Present: ${at.filter(x=>x.status==='Present').length}</p><p>Fees outstanding: ${money(invoices.reduce((n,x)=>n+Math.max(0,x.amount_paise-paid(x.id)),0))}</p>${invoices.map(x=>`<p>${esc(x.title)} · ${money(x.amount_paise-paid(x.id))} outstanding</p>`).join('')}`});
 area.querySelectorAll('[data-update]').forEach(b=>b.onclick=()=>{const box=b.closest('article').querySelector('[data-extra]');const opts=tab==='enquiries'?['New','Contacted','Visit planned','Converted','Lost']:tab==='orders'?['Submitted','Approved','Dispatched','Delivered','Cancelled']:tab==='ledger'?['Pending verification','Verified','Rejected']:['Open','In progress','Resolved'];box.innerHTML=`<form>${select('status','Status',opts)}${input('office_note',tab==='enquiries'?'Follow-up note':'Head-office note','text',false)}<button>Save status</button></form>`;box.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await call(tab,'PATCH',Object.fromEntries(new FormData(e.target)),b.dataset.update);await loadRecords()}catch(error){(root.querySelector('#portalStatus')||{}).textContent=error.message;e.submitter.disabled=false}}});
}

function classroomName(id){return (records.classrooms||[]).find(c=>c.id===id)?.name||'Not assigned'}
function portalNotice(text){(root.querySelector('#portalStatus')||{}).textContent=text}
function wireExtras(area){
 area.querySelectorAll('[data-assign]').forEach(button=>button.onclick=()=>{const box=button.closest('article').querySelector('[data-extra]');box.innerHTML=`<form>${chooseClassroom()}<button>Save classroom</button></form>`;box.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await call('students','PATCH',Object.fromEntries(new FormData(e.target)),button.dataset.assign);await loadRecords();portalNotice('Classroom assigned.')}catch(error){portalNotice(error.message);e.submitter.disabled=false}}});
 area.querySelectorAll('[data-apply]').forEach(button=>button.onclick=async()=>{const fee=records.fee_structures.find(f=>f.id===button.dataset.apply),count=(records.students||[]).filter(s=>s.classroom_id===fee.classroom_id).length;if(!confirm(`Create ${fee.title} charges of ${money(fee.amount_paise)} each for ${count} students? Existing charges from this structure will be skipped.`))return;button.disabled=true;try{const b=await call('apply_fees','POST',{},fee.id);await loadRecords();portalNotice(`${b.created} new fee requests created. Parents can see them after sign in.`)}catch(e){portalNotice(e.message);button.disabled=false}});
 area.querySelectorAll('[data-publish]').forEach(button=>button.onclick=async()=>{const row=records[tab].find(r=>r.id===button.dataset.publish);button.disabled=true;try{await call(tab,'PATCH',{published:!row.published},row.id);await loadRecords();portalNotice(row.published?'Removed from parent view.':'Published to parents.')}catch(e){portalNotice(e.message);button.disabled=false}});
}
function renderAccess(area){
 const teacher=tab==='teacher_access',accounts=records[tab]||[];
 area.innerHTML=`<h3>${teacher?'Teacher':'Parent'} access</h3><p>${teacher?'Assign classrooms to a teacher. They can record attendance and post homework for those classrooms.':'Create a separate parent login for each child. Parents see only their child’s attendance, fees and published classroom updates.'}</p><p>Share the ID and initial password privately. The user can change their password after signing in.</p><a href="/${teacher?'teachers':'parents'}.html" target="_blank" rel="noopener">Open ${teacher?'teacher':'parent'} sign in ↗</a><details class="portal-editor" open><summary>＋ Create / reset access</summary><form id="accessForm"><div class="fields">${teacher?select('account_id','New or existing teacher',[['new','Create new teacher'],...accounts.map(a=>[a.account_id,a.name])])+input('name','Teacher name')+'<label>Assigned classrooms<select name="classroom_ids" multiple required size="5">'+(records.classrooms||[]).map(c=>`<option value="${esc(c.id)}">${esc(c.name+' · '+c.academic_year)}</option>`).join('')+'</select><small>Select all applicable classrooms.</small></label>':chooseStudent()}<label>Initial / replacement password<input name="password" type="password" required minlength="12" maxlength="128" autocomplete="new-password"></label></div><button>Save access</button></form><div id="accessResult" role="status"></div></details><div class="portal-grid">${accounts.map(a=>`<article class="portal-card"><h3>${esc(teacher?a.name:student(a.student_id)?.name||'Student')}</h3><p>${esc(a.account_id)}</p><p>${a.active?'Access enabled':'Access disabled'}</p>${teacher?`<p>${esc(a.classroom_ids.map(classroomName).join(', '))}</p>`:''}<button class="secondary" data-disable="${esc(teacher?a.account_id:a.student_id)}" ${!a.active?'disabled':''}>Disable access</button></article>`).join('')}</div>`;
 area.querySelector('#accessForm').onsubmit=async e=>{e.preventDefault();const form=e.target,fd=new FormData(form),body=Object.fromEntries(fd),id=teacher?(body.account_id==='new'?'':body.account_id):body.student_id;if(teacher)body.classroom_ids=fd.getAll('classroom_ids');e.submitter.disabled=true;try{const b=await call(tab,'POST',body,id);form.reset();await loadRecords();root.querySelector('#accessResult').textContent='Account ID: '+b.account_id+'. Share the password you entered through your usual private channel.'}catch(error){portalNotice(error.message);e.submitter.disabled=false}};
 area.querySelectorAll('[data-disable]').forEach(button=>button.onclick=async()=>{if(!confirm('Disable this login and invalidate its active sessions?'))return;button.disabled=true;try{await call(tab,'POST',{disable:true},button.dataset.disable);await loadRecords()}catch(e){portalNotice(e.message);button.disabled=false}});
}
})();
