/* Neo school workspace. Uses existing school/head-office sessions. */
(()=>{
const css=document.createElement('style');css.textContent=`
#neoWorkspace{margin:24px 0;color:#071b52}#neoWorkspace nav{display:flex;gap:8px;overflow:auto;padding:12px 0}#neoWorkspace nav button{white-space:nowrap;background:#eaf1fb;color:#071b52}#neoWorkspace nav button[aria-pressed=true]{background:#071b52;color:white}.portal-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:14px}.portal-card{padding:18px;background:white;border:1px solid #dce5ef;border-radius:16px;overflow-wrap:anywhere}.portal-card h3{margin:0 0 10px}.portal-card strong.metric{font-size:30px;display:block}.portal-card p{margin:8px 0}.portal-tools{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.portal-tools a{padding:10px;background:#eaf1fb;border-radius:8px;text-decoration:none}#portalForm{max-width:none}#portalForm select,#portalForm textarea,#portalFilter{font:inherit;padding:12px;border:1px solid #cbd6e5;border-radius:9px;width:100%;background:white}#portalForm .fields{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:0 18px}.portal-empty{padding:30px;background:white;border-radius:16px}#neoWorkspace details{background:white;padding:18px;border-radius:16px;margin:16px 0}#portalStatus{white-space:pre-wrap}#portalRecords{margin:16px 0}.portal-pill{display:inline-block;background:#eaf1fb;padding:5px 9px;border-radius:99px;font-size:13px}@media(max-width:600px){header{flex-wrap:wrap}header img{width:110px}main{padding:0 14px}.panel{padding:16px}#neoWorkspace nav{position:sticky;top:0;background:#f5f8fd;z-index:2}}
`;document.head.append(css);
const root=document.createElement('section');root.id='neoWorkspace';root.hidden=true;document.querySelector('main').insertBefore(root,document.getElementById('detail'));
let school=null,tab='dashboard',records={},generation=0;
const names={dashboard:'Overview',students:'Students',enquiries:'Enquiries',attendance:'Attendance',invoices:'Fees',payments:'Receipts',orders:'Orders',ledger:'Head-office payments',support:'Support'};
const classes=['Playgroup','Nursery','LKG','UKG','Daycare'];
const money=x=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(x/100);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const student=id=>records.students?.find(x=>x.id===id);
const label=r=>student(r.student_id)?.name||r.student_id;
const paid=id=>(records.payments||[]).filter(p=>p.invoice_id===id).reduce((n,p)=>n+p.amount_paise,0);
async function call(kind,method='GET',data,id=''){
 const r=await fetch(BASE+'/api/portal/'+encodeURIComponent(school.school_id)+'/'+kind+(id?'/'+encodeURIComponent(id):''),{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});
 const b=await r.json();if(!r.ok){if(r.status===401){window.closeNeoWorkspace();document.getElementById('logout').click()}throw Error(b.error||'Request failed.');}return b;
}
async function loadRecords(){const stamp=++generation;(root.querySelector('#portalStatus')||{}).textContent='Loading school records…';try{const pairs=await Promise.all(Object.keys(names).filter(k=>k!=='dashboard').map(async k=>[k,(await call(k)).records]));if(stamp!==generation)return;records=Object.fromEntries(pairs);renderContent()}catch(e){if(stamp!==generation)return;(root.querySelector('#portalStatus')||{}).textContent=e.message}}
window.openNeoWorkspace=s=>{school=s;tab='dashboard';records={};root.hidden=false;root.innerHTML=`<h2>${esc(s.name)} · School workspace</h2><p>Manage your school’s daily work. All amounts are in INR.</p><nav aria-label="School workspace">${Object.entries(names).map(([k,v])=>`<button data-tab="${k}" aria-pressed="${k===tab}">${v}</button>`).join('')}</nav><div id="portalStatus" role="status" aria-live="polite"></div><div id="portalContent"></div>`;root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;renderContent()});loadRecords()};
window.closeNeoWorkspace=()=>{generation++;school=null;records={};root.hidden=true;root.replaceChildren()};
const input=(key,title,type='text',required=true)=>`<label>${title}<input name="${key}" type="${type}" ${required?'required':''} ${type==='number'?'min="1" step="1"':''} ${type==='text'?'maxlength="200"':''}></label>`;
const select=(key,title,options)=>`<label>${title}<select name="${key}" required><option value="">Choose…</option>${options.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}">${esc(t)}</option>`}).join('')}</select></label>`;
const chooseStudent=()=>select('student_id','Student',(records.students||[]).map(s=>[s.id,s.name+' · '+s.program]));
const amount=()=>'<label>Amount (INR)<input name="amount" type="number" min="0.01" max="1000000" step="0.01" required></label>';
const notes=()=>'<label>Notes<textarea name="notes" maxlength="1000" rows="3"></textarea></label>';
function fields(){switch(tab){
case 'students':return input('name','Child name')+input('dob','Date of birth','date')+select('program','Class',classes)+input('academic_year','Academic starting year','number')+input('parent','Parent / guardian name')+input('mobile','Parent phone','tel')+select('nursery_status','Previous Nursery',['Not applicable','Completed','In progress','Not attended'])+select('lkg_status','Previous LKG',['Not applicable','Completed','In progress','Not attended'])+input('previous_school','Previous school','text',false)+input('previous_city','Previous school city','text',false);
case 'enquiries':return input('name','Parent name')+input('mobile','Parent phone','tel')+input('child_name','Child name')+select('program','Class of interest',classes)+input('follow_up','Follow-up date','date')+notes();
case 'attendance':return chooseStudent()+input('date','Attendance date','date')+select('status','Status',['Present','Absent','Leave']);
case 'invoices':return chooseStudent()+input('title','Fee / instalment name')+amount()+input('due_date','Due date','date');
case 'payments':return select('invoice_id','Fee request',(records.invoices||[]).map(i=>[i.id,label(i)+' · '+i.title+' · balance '+money(i.amount_paise-paid(i.id))]))+amount()+input('date','Payment date','date')+select('method','Method',['Cash','UPI','Bank transfer','Cheque'])+input('reference','Receipt / transaction reference');
case 'orders':return select('category','Category',['Books','Student kits','Uniforms'])+input('item','Item / class / edition')+input('size','Uniform size','text',false)+input('quantity','Quantity','number')+notes();
case 'ledger':return amount()+input('date','Payment date','date')+input('reference','Bank / UPI transaction reference')+notes();
case 'support':return input('subject','Subject')+notes();
}}
function renderContent(){
 root.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tab===tab));
 (root.querySelector('#portalStatus')||{}).textContent='';const area=root.querySelector('#portalContent');
 if(!records.students){area.innerHTML='<p>Records have not loaded. <button id="retryPortal">Retry</button></p>';area.querySelector('button').onclick=loadRecords;return}
 if(tab==='dashboard'){
 const fees=records.invoices.reduce((a,i)=>a+Math.max(0,i.amount_paise-paid(i.id)),0);
 const metrics=[['Students',records.students.length],['Present today',records.attendance.filter(a=>a.date===today()&&a.status==='Present').length],['Fees outstanding',money(fees)],['Open orders',records.orders.filter(o=>!['Delivered','Cancelled'].includes(o.status)).length],['Follow-ups due',records.enquiries.filter(e=>e.follow_up<=today()&&!['Converted','Lost'].includes(e.status)).length]];
 area.innerHTML=`<div class="portal-tools"><button id="refreshPortal">Refresh records</button></div><div class="portal-grid">${metrics.map(([k,v])=>`<article class="portal-card"><p>${k}</p><strong class="metric">${esc(v)}</strong></article>`).join('')}</div><article class="portal-card" style="margin-top:16px"><h3>Today’s work</h3><p>Record attendance, review fee balances and contact parents. Place book, kit and uniform requests from Orders.</p><p>Fee receipts are school-recorded entries. Head-office payments remain pending until verified. Online checkout and automatic messaging are not connected in this version.</p></article>`;area.querySelector('#refreshPortal').onclick=loadRecords;return;
 }
 const help={students:'Register confirmed students. Class selection requires school review; this form does not automatically approve admission.',enquiries:'Record enquiries handled by this school. Website enquiries remain in the head-office CRM until an assignment workflow is connected.',attendance:'Saving again for the same student and date updates attendance.',invoices:'Create a fee request for each instalment. Existing financial records cannot be edited here.',payments:'Record money already received. This does not collect an online payment. Check references before submitting.',orders:'Head office will confirm product availability, pricing and dispatch. Submitting a request does not place a paid purchase.',ledger:'Record a payment already made to head office. Head office verifies the reference; no online payment is taken here.',support:'Send an operational support request to head office. For urgent help, use your usual direct contact.'};
 area.innerHTML=`<h3>${names[tab]}</h3><p>${help[tab]}</p><details><summary>Add ${tab==='payments'?'payment receipt':tab==='invoices'?'fee request':tab==='ledger'?'payment record':tab==='students'?'student':tab==='attendance'?'attendance':tab==='orders'?'order request':tab==='support'?'support request':'enquiry'}</summary><form id="portalForm"><div class="fields">${fields()}</div><button type="submit">Save ${tab==='orders'?'request':'record'}</button></form></details><label>Search ${names[tab].toLowerCase()}<input id="portalFilter" type="search" placeholder="Search names, references or status"></label><div id="portalRecords" class="portal-grid"></div>`;
 let requestId=crypto.randomUUID();
 area.querySelector('#portalForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;(root.querySelector('#portalStatus')||{}).textContent='Saving…';const b=Object.fromEntries(new FormData(e.target));b.request_id=requestId;if(b.amount){b.amount_paise=Math.round(Number(b.amount)*100);delete b.amount}if(b.quantity)b.quantity=Number(b.quantity);try{await call(tab,'POST',b);requestId=crypto.randomUUID();await loadRecords();(root.querySelector('#portalStatus')||{}).textContent='Record saved.'}catch(error){(root.querySelector('#portalStatus')||{}).textContent=error.message;button.disabled=false}};
 area.querySelector('#portalFilter').oninput=e=>renderCards(e.target.value);renderCards('');
}
function renderCards(query){
 const area=root.querySelector('#portalRecords');const list=records[tab].filter(r=>(JSON.stringify(r)+' '+label(r)).toLowerCase().includes(query.toLowerCase()));
 area.innerHTML=list.length?list.map(r=>{
 const s=tab==='students'?r:student(r.student_id);const phone=tab==='enquiries'?r.mobile:s?.mobile;
 let title=r.name||r.subject||r.item||r.title||label(r)||r.reference||r.id;
 let lines=[];
 if(tab==='students')lines=[r.program+' · '+r.academic_year,'DOB: '+r.dob,'Parent: '+r.parent,'Phone: '+r.mobile,'Previous school: '+(r.previous_school||'Not recorded'),'Nursery: '+r.nursery_status+' · LKG: '+r.lkg_status];
 if(tab==='enquiries')lines=[r.child_name+' · '+r.program,'Follow-up: '+r.follow_up,r.status,r.notes,r.office_note];
 if(tab==='attendance')lines=[r.date,r.status];
 if(tab==='invoices')lines=[label(r),'Due: '+r.due_date,'Fee: '+money(r.amount_paise),'Received: '+money(paid(r.id)),'Balance: '+money(r.amount_paise-paid(r.id))];
 if(tab==='payments')lines=[money(r.amount_paise)+' · '+r.method,r.date,'Reference: '+r.reference,'Receipt ID: '+r.id,r.status];
 if(tab==='orders')lines=[r.category+' · '+r.quantity+' items','Size: '+(r.size||'—'),r.status,r.notes,r.office_note];
 if(tab==='ledger')lines=[money(r.amount_paise),r.date,'Reference: '+r.reference,r.status,r.notes,r.office_note];
 if(tab==='support')lines=[r.notes,r.status,r.office_note];
 const tel=(phone||'').replace(/[^+0-9]/g,'');
 return `<article class="portal-card"><h3>${esc(title)}</h3>${lines.filter(Boolean).map(l=>`<p>${esc(l)}</p>`).join('')}<div class="portal-tools">${phone?`<a href="tel:${esc(tel)}">Call parent</a>`:''}${tab==='invoices'?`<button class="secondary" data-remind="${esc(r.id)}">Copy reminder</button>`:''}${tab==='students'?`<button class="secondary" data-profile="${esc(r.id)}">View student summary</button>`:''}${(tab==='enquiries'||mode==='admin'&&['orders','ledger','support'].includes(tab))?`<button class="secondary" data-update="${esc(r.id)}">Update status</button>`:''}</div><div data-extra="${esc(r.id)}"></div></article>`;
 }).join(''):'<p class="portal-empty">No matching records. Add your first record above.</p>';
 area.querySelectorAll('[data-remind]').forEach(b=>b.onclick=async()=>{const i=records.invoices.find(x=>x.id===b.dataset.remind);const balance=i.amount_paise-paid(i.id);const box=b.closest('article').querySelector('[data-extra]');if(balance<=0){box.textContent='No payment is due for this fee request.';return}const text=`Dear parent, ${school.name} reminds you that ${money(balance)} is due for ${label(i)} — ${i.title}, due ${i.due_date}. Please contact the school if you have already paid. Thank you.`;box.textContent=text;try{await navigator.clipboard.writeText(text);(root.querySelector('#portalStatus')||{}).textContent='Reminder copied. Review and send through your messaging app. Nothing has been sent automatically.'}catch{(root.querySelector('#portalStatus')||{}).textContent='Copy the reminder shown on the card and send through your messaging app.'}});
 area.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{const id=b.dataset.profile;const invoices=records.invoices.filter(x=>x.student_id===id);const at=records.attendance.filter(x=>x.student_id===id);b.closest('article').querySelector('[data-extra]').innerHTML=`<hr><p>Attendance entries: ${at.length} · Present: ${at.filter(x=>x.status==='Present').length}</p><p>Fees outstanding: ${money(invoices.reduce((n,x)=>n+Math.max(0,x.amount_paise-paid(x.id)),0))}</p>${invoices.map(x=>`<p>${esc(x.title)} · ${money(x.amount_paise-paid(x.id))} outstanding</p>`).join('')}`});
 area.querySelectorAll('[data-update]').forEach(b=>b.onclick=()=>{const box=b.closest('article').querySelector('[data-extra]');const opts=tab==='enquiries'?['New','Contacted','Visit planned','Converted','Lost']:tab==='orders'?['Submitted','Approved','Dispatched','Delivered','Cancelled']:tab==='ledger'?['Pending verification','Verified','Rejected']:['Open','In progress','Resolved'];box.innerHTML=`<form>${select('status','Status',opts)}${input('office_note',tab==='enquiries'?'Follow-up note':'Head-office note','text',false)}<button>Save status</button></form>`;box.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await call(tab,'PATCH',Object.fromEntries(new FormData(e.target)),b.dataset.update);await loadRecords()}catch(error){(root.querySelector('#portalStatus')||{}).textContent=error.message;e.submitter.disabled=false}}});
}
})();
