/* Neo school workspace. Uses existing school/head-office sessions. */
(()=>{
const root=document.createElement('section');root.id='neoWorkspace';root.hidden=true;document.querySelector('main').insertBefore(root,document.getElementById('detail'));
let school=null,tab='dashboard',records={},errors={},generation=0,loading=false;
const learningTabs=['calendar','curriculum','timetable','learning_report'];
const plannedTabs=new Set(['daily_accounts','hr_workflow','transport','visitor_gate','vendors_assets','maintenance','student_lifecycle','health_safety','approvals','notifications','audit_trail','library','adoption_ptm']);
const names={dashboard:'Overview',school_setup:'School setup & readiness',daily_accounts:'Daily accounts & vouchers',hr_workflow:'Leave & advances',transport:'Transport & safety',visitor_gate:'Visitor & gate',vendors_assets:'Purchase, vendors & assets',maintenance:'Maintenance & housekeeping',student_lifecycle:'Promotion, TC & exit',health_safety:'Health & child safety',approvals:'Approvals',notifications:'Notification centre',audit_trail:'Audit trail',library:'Library',adoption_ptm:'Adoption calls & PTM',calendar:'School calendar',curriculum:'Curriculum & calendar',timetable:'Teacher timetable',learning_report:'Learning report',students:'Students',classrooms:'Classrooms',fee_structures:'Fee structures',homework:'Homework',announcements:'Parent notices',parent_access:'Parent access',teacher_access:'Manage teachers',teacher_tasks:'Teacher tasks & reports',staff:'Staff',staff_attendance:'Staff attendance',payroll:'Payroll',exams:'Exams & hall tickets',assessments:'Assessments & report cards',documents:'Documents & downloads',enquiries:'Enquiries',attendance:'Attendance',invoices:'Assigned fees',payments:'Collect payment',inventory:'Inventory & stores',reports:'Reports & Excel',tickets:'Parent concerns',orders:'Orders',ledger:'Head-office payments',support:'Support'};
const departments=[
 ['dashboard','School overview',['dashboard']],
 ['setup','School setup',['school_setup']],
 ['academics','Academics',['calendar','curriculum','timetable','learning_report','classrooms','homework','exams','assessments']],
 ['students','Students & parents',['students','attendance','adoption_ptm','student_lifecycle','health_safety','parent_access','tickets']],
 ['teachers','Teachers',['teacher_access','teacher_tasks']],
 ['frontoffice','Front office',['enquiries','announcements','visitor_gate']],
 ['hr','HR & payroll',['staff','staff_attendance','hr_workflow','payroll']],
 ['finance','Fees & accounts',['fee_structures','invoices','payments','daily_accounts','ledger']],
 ['inventory','Inventory & stores',['inventory','orders','vendors_assets']],
 ['transport','Transport & safety',['transport']],
 ['maintenance','Maintenance',['maintenance']],
 ['library','Library',['library']],
 ['governance','Approvals & control',['approvals','notifications','audit_trail']],
 ['documents','Documents & reports',['documents','reports']],
 ['support','Operations & support',['support']]
];
const classes=['Playgroup','Nursery','LKG','UKG','Daycare'];
const money=x=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(x/100);
const today=()=>{const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),v=Object.fromEntries(parts.map(x=>[x.type,x.value]));return v.year+'-'+v.month+'-'+v.day};
const validPhone=v=>/^[+0-9 ()-]{8,20}$/.test(String(v||'').trim());
const student=id=>records.students?.find(x=>x.id===id);
const label=r=>student(r.student_id)?.name||r.student_id;
const paid=id=>(records.payments||[]).filter(p=>p.invoice_id===id).reduce((n,p)=>n+p.amount_paise,0);
async function call(kind,method='GET',data,id=''){
 const requestToken=token;
 const r=await fetch(BASE+'/api/portal/'+encodeURIComponent(school.school_id)+'/'+kind+(id?'/'+encodeURIComponent(id):''),{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});
 const b=await r.json().catch(()=>({error:'The server returned an unreadable response.'}));if(!r.ok){if(r.status===401&&token===requestToken){window.closeNeoWorkspace();document.getElementById('logout').click()}throw Error(r.status===404?'This feature requires the latest CRM Worker. Ask head office to deploy portal v2.':b.error||'Request failed.');}return b;
}
async function loadRecords(){const stamp=++generation;loading=true;renderContent();const keys=Object.keys(names).filter(k=>k!=='dashboard'&&!learningTabs.includes(k)&&!plannedTabs.has(k)&&!['inventory','reports','tickets','documents'].includes(k));keys.push('stock_items','stock_moves');const results=await Promise.allSettled(keys.map(async k=>[k,await call(k)]));if(stamp!==generation)return false;errors={};results.forEach((result,i)=>{const k=keys[i];if(result.status==='fulfilled'){records[k]=result.value[1].records||result.value[1].accounts||[]}else{errors[k]=result.reason.message;delete records[k]}});loading=false;renderContent();return !errors[tab]}
window.openNeoWorkspace=s=>{school=s;tab='dashboard';records={};errors={};root.hidden=false;
 const departmentCards=departments.map(([id,title,tabs])=>tabs.length===1?`<button class="neo-single-department" data-tab="${tabs[0]}" aria-pressed="${tabs[0]===tab}">${esc(title)}</button>`:`<details class="panel neo-department" ${id==='academics'?'open':''}><summary>${esc(title)}</summary><div class="actions">${tabs.map(k=>`<button class="secondary" data-tab="${k}" aria-pressed="${k===tab}">${esc(names[k])}</button>`).join('')}</div></details>`).join('');
 root.innerHTML=`<div class="portal-hero"><div class="portal-identity"><span class="eyebrow brand-eyebrow"><b class="brand-neo">NEO</b> <b class="brand-school">SCHOOL</b> <b class="brand-india">INDIA</b> <i>·</i> <b class="brand-city">${esc(s.city)}</b></span><h2>${esc(s.name)}</h2><p>School Portal · Today’s workspace & head-office connection</p></div><div class="portal-profile"><img src="/neo%20owl.jpeg" alt="Neo" width="100" height="120"></div></div><aside class="neo-department-nav" aria-label="School departments">${departmentCards}<button type="button" id="navSignOut" class="nav-signout">Sign out</button></aside><div id="portalStatus" role="status" aria-live="polite"></div><div id="portalContent"></div>`;
 root.querySelector('#navSignOut').onclick=()=>document.getElementById('logout')?.click();root.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;root.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.tab===tab)));renderContent()});loadRecords()};
window.closeNeoWorkspace=()=>{generation++;school=null;records={};errors={};loading=false;root.hidden=true;root.replaceChildren()};
const input=(key,title,type='text',required=true)=>`<label>${title}<input name="${key}" type="${type}" ${required?'required':''} ${type==='number'?'min="1" step="1"':''} ${type==='text'?'maxlength="200"':''}></label>`;
const select=(key,title,options)=>`<label>${title}<select name="${key}" required><option value="">Choose…</option>${options.map(x=>{const [v,t]=Array.isArray(x)?x:[x,x];return `<option value="${esc(v)}">${esc(t)}</option>`}).join('')}</select></label>`;
const chooseStudent=()=>select('student_id','Student',(records.students||[]).map(s=>[s.id,s.name+' · '+s.program]));
const amount=()=>'<label>Amount (INR)<input name="amount" type="number" min="0.01" max="1000000" step="0.01" required></label>';
const notes=()=>'<label>Notes<textarea name="notes" maxlength="1000" rows="3"></textarea></label>';
const chooseClassroom=(required=true)=>select('classroom_id','Classroom',(records.classrooms||[]).map(c=>[c.id,c.name+' · '+c.program+' · '+c.academic_year])).replace('required',required?'required':'');
const publish=()=>'<label class="check"><input type="checkbox" name="published">Publish to parents now</label>';
function renderPlannedModule(){const copy={
daily_accounts:['Daily accounts & vouchers','Opening cash → income → expenses/vouchers → bank movement → counter closing. Fee collections and future payroll/inventory transactions must feed this ledger without duplicate entry.','Frontend shell ready · backend ledger required'],
hr_workflow:['HR workflow','Late marks, configurable leave types, leave application/approval, salary advances and payroll inputs belong here. Existing Staff/Attendance/Payroll screens remain unchanged until this workflow is connected.','Frontend shell ready · backend HR workflow required'],
transport:['Transport & safety','Route start → approaching pickup → ready → picked up → school drop, with return-trip states. GPS/CCTV stay vendor integrations behind this workflow.','Planned integration · third-party GPS/CCTV later'],
visitor_gate:['Visitor & gate','Visitor entry/exit, purpose, host, gate status and authorised history.','Reserved · backend workflow required'],
vendors_assets:['Purchase, vendors & assets','Shortage/reorder → purchase request → approval → vendor → purchase order → goods received → Inventory update → vendor bill/payment in Accounts. Fixed assets retain purchase value, location and ownership history.','Reserved · backend procurement workflow required'],
maintenance:['Maintenance & housekeeping','Asset complaints, repairs, warranty/service history, vehicle service/insurance/pollution/fitness reminders, plus classroom/toilet/common-area housekeeping schedules, cleaning checks and consumable requirements.','Reserved · backend maintenance workflow required'],
student_lifecycle:['Promotion, TC & exit','Academic-year close → promote child to next class/section, or record withdrawal/TC/exit while preserving the child academic and financial history.','Reserved · backend lifecycle workflow required'],
health_safety:['Health & child safety','Emergency contacts, authorised pickup, first-aid/incident records, parent-informed status and child welfare follow-up with restricted permissions.','Reserved · backend safety workflow required'],
approvals:['Approvals','One principal/authorised inbox for expense, purchase, leave, fee concession/refund, salary advance, stock adjustment and exceptional child-release approvals.','Reserved · backend approval engine required'],
notifications:['Notification centre','Central event → recipient → channel → delivery/read/acknowledgement engine for school, staff and parent communications. Modules should not create independent notification silos.','Reserved · backend notification engine required'],
audit_trail:['Audit trail','Immutable accountability view for who created, changed, approved or reversed sensitive school records and when.','Reserved · backend audit events required'],
library:['Library','Catalogue/accession → issue → student/staff → due → return → overdue/lost/damaged. Kept in the architecture now so Grade 1–10 expansion does not require redesign.','Reserved · backend library workflow required']
};const x=copy[tab];return `<div class="panel"><span class="eyebrow">DEPARTMENT WORKFLOW</span><h3>${esc(x[0])}</h3><p>${esc(x[1])}</p><p><b>Status:</b> ${esc(x[2])}</p><p>This is intentionally not a fake data-entry form. It will become operational only when its persistence, permissions and audit trail are connected.</p></div>`}
function fields(){switch(tab){
case 'teacher_tasks':{const ts=(records.teacher_access||[]).filter(t=>t.active);return select('teacher_id','Teacher',ts.map(t=>[t.account_id,t.name]))+(!ts.length?'<p class="field-help">No teacher account exists. Open <b>Manage teachers</b> to create the master record first.</p>':'')+input('title','Task / report name')+`<label>Due date<input name="due_date" type="date" min="${today()}" required></label>`+'<label>Responsibilities / preparation<textarea name="instructions" required maxlength="2000"></textarea></label>';}
case 'classrooms':{const y=new Date().getFullYear(),years=Array.from({length:5},(_,i)=>{const a=y-2+i;return [String(a),String(a)+'-'+String(a+1).slice(-2)]});const teacherOptions=(records.teacher_access||[]).filter(t=>t.active).map(t=>[t.account_id,t.name]);return input('name','Classroom / section name')+select('program','Programme',classes)+select('academic_year','Academic year',years)+select('teacher_id','Class teacher',teacherOptions)+(!teacherOptions.length?'<p class="field-help">No active teachers yet. <button type="button" class="inline-link" id="createTeacherFromClass">Create teachers</button></p>':'<p class="field-help"><button type="button" class="inline-link" id="manageTeachersFromClass">Manage teachers</button></p>')+input('capacity','Room capacity','number');}
case 'fee_structures':return chooseClassroom()+input('title','Fee / instalment name')+amount()+`<label>Due date<input name="due_date" type="date" min="${today()}" required></label>`;
case 'homework':return chooseClassroom()+select('subject','Subject',['English','Early maths','Environment','Art','Physical development','Telugu','Hindi','Other'])+input('topic',"Today’s topic")+select('homework_type','Homework type',['Reading','Story / conversation','Counting','Drawing','Practical activity','Revision','Worksheet','Other'])+input('title','Activity title')+'<label>Instructions<textarea name="instructions" required maxlength="2000" rows="4"></textarea></label>'+ `<label>Due date<input name="due_date" type="date" min="${today()}" required></label>`+publish();
case 'announcements':return select('category','Announcement type',['General','Holiday','Reopening','Timing change','PTM','Celebration','Event','Assessment','Field trip','Materials reminder','Other'])+select('audience','Audience',['Parents and teachers','Teachers only'])+chooseClassroom(false)+input('title','Notice title')+'<label>Message<textarea name="message" required maxlength="2000" rows="4"></textarea></label>'+publish();

case 'students':return chooseClassroom(false)+input('name','Child name')+`<label>Date of birth<input name="dob" type="date" max="${today()}" required></label>`+select('gender','Gender',['Male','Female','Prefer not to say'])+input('email','Parent email','email',false)+select('program','Class',classes)+`<label>Academic year<input name="academic_year" readonly required placeholder="Select classroom first"></label>`+input('parent','Parent / guardian name')+input('mobile','Parent phone','tel')+select('nursery_status','Previous Nursery',['Not applicable','Completed','In progress','Not attended'])+select('lkg_status','Previous LKG',['Not applicable','Completed','In progress','Not attended'])+input('previous_school','Previous school','text',false)+input('previous_city','Previous school city','text',false);
case 'enquiries':return input('name','Parent name')+input('mobile','Parent phone','tel')+input('child_name','Child name')+select('program','Class of interest',classes)+`<label>Follow-up date<input name="follow_up" type="date" min="${today()}" required></label>`+notes();
case 'attendance':return chooseStudent()+`<label>Attendance date<input name="date" type="date" max="${today()}" required></label>`+select('status','Status',['Present','Absent','Leave']);
case 'invoices':return chooseStudent()+input('title','Fee / instalment name')+amount()+`<label>Due date<input name="due_date" type="date" min="${today()}" required></label>`;
case 'payments':return select('invoice_id','Fee request',(records.invoices||[]).filter(i=>Math.max(0,i.amount_paise-paid(i.id))>0).map(i=>[i.id,label(i)+' · '+i.title+' · balance '+money(Math.max(0,i.amount_paise-paid(i.id)))]))+amount()+`<label>Payment date<input name="date" type="date" max="${today()}" required></label>`+select('method','Method',['Cash','UPI','Bank transfer','Cheque'])+input('reference','Receipt / transaction reference');
case 'orders':return select('order_for','Order for',['School stock','Classroom','Child'])+chooseClassroom(false)+chooseStudent().replace('required','')+select('category','Category',['Books','Student kits','Uniforms'])+input('item','Item / class / edition')+input('size','Uniform size','text',false)+input('quantity','Quantity','number')+notes();
case 'ledger':return amount()+`<label>Payment date<input name="date" type="date" max="${today()}" required></label>`+input('reference','Bank / UPI transaction reference')+notes();
case 'support':return input('subject','Subject')+notes();
}}
function renderSchoolSetup(area){
 const classrooms=records.classrooms||[],students=records.students||[],teachers=(records.teacher_access||[]).filter(x=>x.active),staff=(records.staff||[]).filter(x=>x.status!=='Inactive'),fees=records.fee_structures||[],stock=records.stock_items||[];
 const programmes=[...new Set(classrooms.map(x=>x.program).filter(Boolean))],assignedTeachers=new Set(),unassignedClasses=[];
 classrooms.forEach(c=>{const teacherRef=c.teacher_id||c.teacher_account_id||c.teacher;if(teacherRef)assignedTeachers.add(String(teacherRef));else unassignedClasses.push(c)});
 const studentClassLinks=students.filter(s=>s.classroom_id).length,feeClassLinks=new Set(fees.map(f=>f.classroom_id).filter(Boolean)).size;
 const steps=[
  ['Classes & sections',classrooms.length>0,classrooms.length+' classroom / section'+(classrooms.length===1?'':'s')+' · '+programmes.length+' programme'+(programmes.length===1?'':'s'),'classrooms'],
  ['Teachers',teachers.length>0,teachers.length+' active teacher account'+(teachers.length===1?'':'s')+' · create once, reuse everywhere','teacher_access'],
  ['Teacher assignment',classrooms.length>0&&unassignedClasses.length===0,classrooms.length?unassignedClasses.length+' class'+(unassignedClasses.length===1?'':'es')+' without a stored teacher assignment':'Create classes first','classrooms'],
  ['Students',students.length>0,students.length+' student'+(students.length===1?'':'s')+' · '+studentClassLinks+' linked to a classroom','students'],
  ['Fee structure',fees.length>0,fees.length+' fee structure'+(fees.length===1?'':'s')+' · '+feeClassLinks+' class link'+(feeClassLinks===1?'':'s'),'fee_structures'],
  ['Timetable',null,'Published timetable status is managed in the connected timetable workflow.','timetable'],
  ['Opening inventory',stock.length>0,stock.length+' stock item'+(stock.length===1?'':'s')+' currently available in Inventory','inventory'],
  ['Transport',null,'Optional per child. Route / vehicle / trip backend is reserved.','transport']
 ];
 const known=steps.filter(x=>x[1]!==null),done=known.filter(x=>x[1]).length,pct=known.length?Math.round(done/known.length*100):0;
 area.innerHTML=`<section class="school-setup-readiness"><span class="eyebrow word-colors"><i>SCHOOL</i> <i>SETUP</i> <i>·</i> <i>READINESS</i></span><div class="setup-head"><div><h2>Prepare this school to operate</h2><p>One setup sequence before daily operations begin. Existing records are reused; this screen does not create duplicate data.</p></div><strong>${pct}% known setup ready</strong></div><div class="setup-progress"><progress value="${done}" max="${known.length||1}"></progress><span>${done} of ${known.length} verifiable foundations currently have data</span></div><div class="setup-step-grid">${steps.map((x,i)=>`<button type="button" class="setup-step ${x[1]===true?'is-ready':x[1]===false?'needs-setup':'backend-pending'}" data-setup-tab="${esc(x[3])}"><b>${i+1}</b><span><strong>${esc(x[0])}</strong><small>${esc(x[2])}</small></span><em>${x[1]===true?'Ready':x[1]===false?'Needs setup':'Check module'}</em></button>`).join('')}</div><div class="portal-card setup-rule"><h3>Setup rule</h3><p>Every master record is created once and reused everywhere. Teacher accounts, students, classes/sections, fee structures and inventory items must be linked by their existing record IDs instead of being re-entered in another module.</p></div><div class="portal-error"><strong>Backend boundaries</strong><p>Teacher assignment currently depends on the fields exposed by existing classroom records. Transport setup and timetable publication status are not duplicated here; their connected workflows remain the source of truth.</p></div></section>`;
 area.querySelectorAll('[data-setup-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.setupTab;root.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.tab===tab)));renderContent()});
}
function renderContent(){if(tab==='school_setup'){const box=document.getElementById('portalContent');if(box)renderSchoolSetup(box);return;}if(tab==='adoption_ptm'){const box=document.getElementById('portalContent');if(box)box.innerHTML=`<section class="workflow-blueprint"><span class="eyebrow word-colors"><i>STUDENT</i> <i>CARE</i> <i>·</i> <i>WEEKLY</i> <i>CYCLE</i></span><h2>Adoption calls & PTM</h2><p>One connected child-progress workflow for teacher follow-up, parent feedback, accountable next actions and PTM review. Persistence will activate when the CRM Worker exposes the required endpoints; no browser-only records are created.</p><div class="workflow-steps"><article><b>1</b><strong>Assign children</strong><span>Class Teacher / mentor owns a defined group of children.</span></article><article><b>2</b><strong>Weekly adoption call</strong><span>Due once each week with completed / missed visibility.</span></article><article><b>3</b><strong>Parent feedback</strong><span>Learning, participation, home practice and parent concern.</span></article><article><b>4</b><strong>Next action</strong><span>Owner + due date + Open / In progress / Resolved.</span></article><article><b>5</b><strong>Child 360</strong><span>Learning, observations, attendance, assessments and follow-ups.</span></article><article><b>6</b><strong>PTM report</strong><span>Previous points, progress, open actions and agreed next steps.</span></article></div><div class="portal-grid"><article class="portal-card"><h3>School Master view</h3><p>Calls due/completed/missed, teacher-wise completion, children not contacted, open concerns and overdue actions.</p></article><article class="portal-card"><h3>Teacher view</h3><p>My adopted children, this week’s calls, parent feedback and assigned follow-ups.</p></article><article class="portal-card"><h3>Parent-safe view</h3><p>Shared progress, agreed actions and PTM report only. Internal school/teacher notes remain private.</p></article></div><div class="portal-error"><strong>Backend pending</strong><p>Required data objects: adoption assignments, weekly calls, feedback, action owners/status, PTM sessions and parent-safe PTM reports.</p></div></section>`;return;}if(plannedTabs.has(tab)){const box=document.getElementById('portalContent');if(box)box.innerHTML=renderPlannedModule();return;}
 root.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.tab===tab));
 (root.querySelector('#portalStatus')||{}).textContent='';const area=root.querySelector('#portalContent');
 if(loading&&!Object.keys(records).length){area.innerHTML='<div class="portal-empty">Loading your school workspace…</div>';return}
 if(learningTabs.includes(tab)){window.renderNeoLearning(area,{tab,school,token,mode,classrooms:records.classrooms||[],teachers:records.teacher_access||[],students:records.students||[],assessments:records.assessments||[]});return}
 if(['staff','staff_attendance','payroll','exams','assessments','documents'].includes(tab)){const needed={staff:['staff'],staff_attendance:['staff','staff_attendance'],payroll:['staff','payroll'],exams:['exams'],assessments:['students','assessments'],documents:['students']}[tab]||[];const missing=needed.filter(k=>errors[k]||!Object.prototype.hasOwnProperty.call(records,k));if(missing.length){area.innerHTML=`<div class="portal-error"><h3>${esc(names[tab])} is not available yet</h3><p>The school portal is ready, but the CRM Worker has not provided: ${esc(missing.map(k=>k.replaceAll('_',' ')).join(', '))}. Existing school data is safe; this module will activate when backend support is deployed.</p><button id="retryPortal">Retry connection</button></div>`;area.querySelector('#retryPortal').onclick=loadRecords;return}if(typeof window.renderNeoPeopleDocs!=='function'){area.innerHTML='<div class="portal-error"><h3>Module failed to load</h3><p>Refresh this page to load staff, payroll and document tools.</p></div>';return}window.renderNeoPeopleDocs(area,{tab,records,call,refresh:loadRecords,status:portalNotice,school});return}
 if(['payments','inventory','reports'].includes(tab)&&(['students','classrooms','invoices','payments',...(tab==='inventory'?['stock_items','stock_moves']:[])].some(k=>errors[k]))){area.innerHTML='<p class="portal-error">Required records could not load. Return to Overview and refresh before continuing.</p>';return}
 if(['payments','inventory','reports'].includes(tab)){window.renderNeoOperations(area,{tab,records,call,refresh:loadRecords,status:portalNotice});return}
 if(tab==='tickets'){const api=async(path,body)=>{const r=await fetch(BASE+'/api/learning/'+path+'?school_id='+encodeURIComponent(school.school_id),{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json();if(!r.ok)throw Error(b.error);return b};window.renderNeoTickets(area,{api,role:mode,status:portalNotice,teachers:records.teacher_access||[]});return}
 if(errors[tab]){area.innerHTML=`<div class="portal-error"><h3>${names[tab]} could not load</h3><p>${esc(errors[tab])}</p><button id="retryPortal">Retry connection</button></div>`;area.querySelector('button').onclick=loadRecords;return}
 if(tab==='parent_access'||tab==='teacher_access'){renderAccess(area);return}

 if(tab==='dashboard'){
 if(['students','invoices','payments','attendance','orders','enquiries'].some(k=>!records[k])){area.innerHTML=`<div class="portal-error"><h3>Some school records could not load</h3><p>${esc(Object.entries(errors).map(([k,e])=>names[k]+': '+e).join(' · '))}</p><button id="retryPortal">Retry connection</button><p>You can still open the other sections.</p></div>`;area.querySelector('button').onclick=loadRecords;return}
 const fees=records.invoices.reduce((a,i)=>a+Math.max(0,i.amount_paise-paid(i.id)),0);
 const attendanceToday=records.attendance.filter(a=>a.date===today()),attendanceRecorded=new Set(attendanceToday.map(a=>a.student_id)).size,attendancePending=Math.max(0,records.students.length-attendanceRecorded),overdueFees=records.invoices.filter(i=>i.amount_paise>paid(i.id)&&i.due_date&&i.due_date<today()).length,openOrders=records.orders.filter(o=>!['Delivered','Cancelled','Completed','Closed'].includes(o.status)).length,followUpsDue=records.enquiries.filter(e=>e.follow_up<=today()&&!['Converted','Lost'].includes(e.status)).length,staffReady=Array.isArray(records.staff),staffAttendanceReady=Array.isArray(records.staff_attendance),payrollReady=Array.isArray(records.payroll),activeStaff=staffReady?records.staff.filter(s=>s.status!=='Inactive').length:null,staffMarked=staffAttendanceReady?new Set(records.staff_attendance.filter(a=>a.date===today()).map(a=>a.staff_id)).size:null,staffPending=staffReady&&staffAttendanceReady?Math.max(0,activeStaff-staffMarked):null,payrollMonth=today().slice(0,7),payrollProcessed=payrollReady?records.payroll.filter(p=>p.month===payrollMonth).length:null;
 const todayPayments=records.payments.filter(p=>p.date===today()),paymentMethod=p=>String(p.method||'').toLowerCase(),isCheque=p=>['cheque','check'].includes(paymentMethod(p)),isUpi=p=>paymentMethod(p)==='upi',isBank=p=>['bank transfer','bank','transfer','neft','rtgs','imps'].includes(paymentMethod(p)),cashToday=todayPayments.filter(p=>paymentMethod(p)==='cash').reduce((n,p)=>n+(p.amount_paise||0),0),chequeToday=todayPayments.filter(isCheque).reduce((n,p)=>n+(p.amount_paise||0),0),upiToday=todayPayments.filter(isUpi).reduce((n,p)=>n+(p.amount_paise||0),0),bankToday=todayPayments.filter(isBank).reduce((n,p)=>n+(p.amount_paise||0),0),otherDigitalToday=todayPayments.filter(p=>paymentMethod(p)!=='cash'&&!isCheque(p)&&!isUpi(p)&&!isBank(p)).reduce((n,p)=>n+(p.amount_paise||0),0),digitalToday=upiToday+bankToday+otherDigitalToday,incomeToday=cashToday+digitalToday+chequeToday;
 const metrics=[['Students',records.students.length],['Attendance today',attendanceRecorded+'/'+records.students.length+(attendancePending?' · '+attendancePending+' pending':' · Complete')],['Fees outstanding',money(fees)+(overdueFees?' · '+overdueFees+' overdue':'')],['Income recorded today',money(incomeToday)],['Cash collected today',money(cashToday)],['Digital/bank today',money(digitalToday)],['Open orders',openOrders],['Follow-ups due',followUpsDue],['Staff',staffReady?activeStaff:'Backend pending'],['Staff attendance',staffPending===null?'Backend pending':staffMarked+'/'+activeStaff+(staffPending?' · '+staffPending+' pending':' · Complete')],['Payroll '+payrollMonth,payrollProcessed===null?'Backend pending':payrollProcessed+' records']];
 const attention=[attendancePending?attendancePending+' student attendance pending':'',overdueFees?overdueFees+' overdue fee request'+(overdueFees===1?'':'s'):'',followUpsDue?followUpsDue+' admission follow-up'+(followUpsDue===1?'':'s')+' due':'',staffPending>0?staffPending+' staff attendance pending':'',!Array.isArray(records.staff)?'HR backend pending':'',!Array.isArray(records.payroll)?'Payroll backend pending':''].filter(Boolean);
 const totalFees=records.invoices.reduce((a,i)=>a+(i.amount_paise||0),0),paidFees=Math.max(0,totalFees-fees),feePct=totalFees?Math.round((paidFees/totalFees)*100):100;
 const attendancePct=records.students.length?Math.round((attendanceRecorded/records.students.length)*100):0,cashPct=incomeToday?Math.round((cashToday/incomeToday)*100):0,upiPct=incomeToday?Math.round((upiToday/incomeToday)*100):0,bankPct=incomeToday?Math.round(((bankToday+otherDigitalToday)/incomeToday)*100):0,chequePct=Math.max(0,100-cashPct-upiPct-bankPct),staffPct=staffReady&&staffAttendanceReady&&activeStaff?Math.round((staffMarked/activeStaff)*100):0,payrollTotal=staffReady?activeStaff:0,payrollPct=payrollReady&&payrollTotal?Math.min(100,Math.round((payrollProcessed/payrollTotal)*100)):0;
 const health=[
  ['Attendance',attendanceRecorded+' marked',attendancePending+' pending',attendancePct,0,'Marked','Pending','ready'],
  ['Fees',money(paidFees)+' collected',money(fees)+' due',feePct,totalFees?Math.min(100-feePct,Math.round((fees?Math.min(fees,totalFees):0)/totalFees*100)):0,'Collected','Due','ready'],
  ['Income today',money(cashToday)+' cash · '+money(upiToday)+' UPI',money(bankToday+otherDigitalToday)+' bank transfer · '+money(chequeToday)+' cheque',cashPct,upiPct,'Cash','UPI','income',bankPct,chequePct],
  ['Staff attendance',staffAttendanceReady?staffMarked+' marked':'Backend pending',staffAttendanceReady&&staffReady?staffPending+' pending':'Not connected',staffPct,0,'Marked','Pending',staffAttendanceReady?'ready':'pending'],
  ['Payroll',payrollReady?payrollProcessed+' processed':'Backend pending',payrollReady&&staffReady?Math.max(0,payrollTotal-payrollProcessed)+' pending':'Not connected',payrollPct,0,'Processed','Pending',payrollReady?'ready':'pending']
 ];
 area.innerHTML=`<section class="executive-snapshot"><div class="snapshot-head"><div><span class="eyebrow word-colors"><i>SCHOOL</i> <i>MASTER</i> <i>·</i> <i>TODAY</i></span><h2>Today snapshot</h2><p>Completed versus remaining at a glance. <strong>Needs attention · ${attention.length}</strong></p></div><button id="refreshPortal" class="snapshot-refresh" type="button" title="Refresh records" aria-label="Refresh records">↻</button></div><div class="health-strip">${health.map(([label,done,due,pct,critical,doneLabel,dueLabel,state,third,fourth])=>`<article class="health-item ${state}"><div class="health-ring" style="--done:${pct};--critical:${critical};--third:${third||0};--fourth:${fourth||0}"><span>${state==='pending'?'—':state==='income'?'100%':pct+'%'}</span></div><div class="health-copy"><small>${esc(label)}</small><b>${esc(done)}</b><em>${esc(due)}</em><div class="health-legend"><span><i class="legend-done"></i>${esc(doneLabel)}</span><span><i class="legend-due"></i>${esc(dueLabel)}</span>${state==='income'?'<span><i class="legend-third"></i>Bank transfer</span><span><i class="legend-fourth"></i>Cheque</span>':critical?'<span><i class="legend-critical"></i>Attention</span>':''}</div></div></article>`).join('')}</div></section><div class="attention-row">${attention.length?attention.map(x=>`<article class="attention-chip"><span></span><strong>${esc(x)}</strong></article>`).join(''):'<article class="attention-chip good"><span></span><strong>No current attention flags from connected records.</strong></article>'}</div><h3>Today at a glance</h3><div class="portal-grid">${metrics.map(([k,v])=>`<article class="portal-card"><p>${k}</p><strong class="metric">${esc(v)}</strong></article>`).join('')}</div><article class="portal-card" style="margin-top:16px"><h3>Operational status</h3><p>Inventory & Stores is available from its department. Daily Accounts & Vouchers, leave/late marks/advances, Visitor & Gate, Vendors & Assets and Transport are reserved as explicit workflows and remain backend-dependent rather than storing fake browser-only records.</p><p>Fee receipts are school-recorded entries. Head-office payments remain pending until verified. Online checkout and automatic messaging are not connected in this version.</p></article>`;area.querySelector('#refreshPortal').onclick=loadRecords;return;
 }
 const help={teacher_tasks:'Assign a preparation task, activity or report deadline. The teacher sees it in My tasks and records completion or a reason.',classrooms:'Create classroom sections and academic years. Assign students and teacher accounts to the right classroom.',fee_structures:'Create one instalment for a classroom. It is assigned automatically to existing and newly added students in that classroom. Apply again to backfill older structures without duplicates.',homework:'Published activities appear in the parent portal for this classroom. Drafts stay within the school.',announcements:'Publish notices to one classroom, or leave classroom blank for all parents in this school.',students:'Register confirmed students. Class selection requires school review; this form does not automatically approve admission.',enquiries:'Record enquiries handled by this school. Website enquiries remain in the head-office CRM until an assignment workflow is connected.',attendance:'Saving again for the same student and date updates attendance.',invoices:'Create a fee request for each instalment. Existing financial records cannot be edited here.',payments:'Record money already received. This does not collect an online payment. Check references before submitting.',orders:'Head office will confirm product availability, pricing and dispatch. Submitting a request does not place a paid purchase.',ledger:'Record a payment already made to head office. Head office verifies the reference; no online payment is taken here.',support:'Send an operational support request to head office. For urgent help, use your usual direct contact.'};
 area.innerHTML=`<h3>${names[tab]}</h3><p>${help[tab]}</p><details class="portal-editor" ${!(records[tab]||[]).length?'open':''}><summary>＋ Add ${tab==='classrooms'?'classroom':tab==='fee_structures'?'fee structure':tab==='homework'?'homework':tab==='announcements'?'parent notice':tab==='payments'?'payment receipt':tab==='invoices'?'fee request':tab==='ledger'?'payment record':tab==='students'?'student':tab==='attendance'?'attendance':tab==='orders'?'order request':tab==='support'?'support request':'enquiry'}</summary><form id="portalForm"><div class="fields">${fields()}</div><button type="submit">Save ${tab==='orders'?'request':'record'}</button></form></details>${tab==='students'?`<div class="student-master-note"><strong>Student master · single entry</strong><span>Create each child once. Fees, attendance, kit, parent access, transport and promotion must reuse this Student ID.</span><div><button type="button" class="inline-link" data-student-link="parent_access">Parent credentials</button><button type="button" class="inline-link" data-student-link="orders">Books / kits</button><button type="button" class="inline-link" data-student-link="student_lifecycle">Promotion / TC / exit</button></div></div><div class="student-list-filters"><label>Academic year<select id="studentYearFilter"><option value="">All years</option>${[...new Set((records.classrooms||[]).map(c=>c.academic_year).filter(Boolean))].sort().map(y=>`<option>${esc(y)}</option>`).join('')}</select></label><label>Class / section<select id="studentClassFilter"><option value="">All classes</option>${(records.classrooms||[]).map(c=>`<option value="${esc(c.id)}">${esc(c.name+' · '+c.program)}</option>`).join('')}</select></label></div>`:''}<label>Search ${names[tab].toLowerCase()}<input id="portalFilter" type="search" placeholder="Search names, references or status"></label><div id="portalRecords" class="portal-grid"></div>`;
 if(tab==='classrooms'){const jump=area.querySelector('#createTeacherFromClass')||area.querySelector('#manageTeachersFromClass');if(jump)jump.onclick=()=>{tab='teacher_access';root.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.tab===tab)));renderContent()}}
 if(tab==='students'){const form=area.querySelector('#portalForm');form.elements.classroom_id.onchange=()=>{const c=(records.classrooms||[]).find(c=>c.id===form.elements.classroom_id.value);if(c){form.elements.program.value=c.program;form.elements.academic_year.value=c.academic_year}}} if(tab==='students')area.querySelectorAll('[data-student-link]').forEach(b=>b.onclick=()=>{tab=b.dataset.studentLink;root.querySelectorAll('[data-tab]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.tab===tab)));renderContent()});
 let requestId=crypto.randomUUID();
 area.querySelector('#portalForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;(root.querySelector('#portalStatus')||{}).textContent='Saving…';const b=Object.fromEntries(new FormData(e.target));if(['students','enquiries'].includes(tab)&&!validPhone(b.mobile)){(root.querySelector('#portalStatus')||{}).textContent='Enter a valid parent phone number.';button.disabled=false;return}if(tab==='students'&&b.dob>today()){(root.querySelector('#portalStatus')||{}).textContent='Date of birth cannot be in the future.';button.disabled=false;return}if(['attendance','payments','ledger'].includes(tab)&&b.date>today()){(root.querySelector('#portalStatus')||{}).textContent='Future dates are not allowed for this record.';button.disabled=false;return}b.request_id=requestId;if('published' in b)b.published=true;else if(['homework','announcements'].includes(tab))b.published=false;if(b.capacity)b.capacity=Number(b.capacity);if(b.amount){b.amount_paise=Math.round(Number(b.amount)*100);delete b.amount}if(b.quantity)b.quantity=Number(b.quantity);try{await call(tab,'POST',b);requestId=crypto.randomUUID();await loadRecords();(root.querySelector('#portalStatus')||{}).textContent='Record saved.'}catch(error){(root.querySelector('#portalStatus')||{}).textContent=error.message;button.disabled=false}};
 const rerender=()=>renderCards(area.querySelector('#portalFilter').value);area.querySelector('#portalFilter').oninput=rerender;if(tab==='students'){area.querySelector('#studentYearFilter').onchange=rerender;area.querySelector('#studentClassFilter').onchange=rerender}renderCards('');
}
function renderCards(query){
 const area=root.querySelector('#portalRecords');let source=records[tab];if(tab==='students'){const y=root.querySelector('#studentYearFilter')?.value||'',cl=root.querySelector('#studentClassFilter')?.value||'';source=source.filter(r=>(!y||String(r.academic_year)===y)&&(!cl||String(r.classroom_id)===cl))}const list=source.filter(r=>(JSON.stringify(r)+' '+label(r)).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>{if(tab==='enquiries'){const closed=s=>['Converted','Lost'].includes(s),ac=closed(a.status),bc=closed(b.status),ad=a.follow_up||'9999-12-31',bd=b.follow_up||'9999-12-31';return ac-bc||ad.localeCompare(bd)}if(tab==='invoices'){const ab=Math.max(0,a.amount_paise-paid(a.id)),bb=Math.max(0,b.amount_paise-paid(b.id)),ao=ab>0&&a.due_date&&a.due_date<today(),bo=bb>0&&b.due_date&&b.due_date<today();return bo-ao||(bb>0)-(ab>0)||(a.due_date||'').localeCompare(b.due_date||'')}if(tab==='teacher_tasks'){const done=s=>['Completed','Not completed'].includes(s),ac=done(a.status),bc=done(b.status),ao=!ac&&a.due_date&&a.due_date<today(),bo=!bc&&b.due_date&&b.due_date<today();return ac-bc||bo-ao||(a.due_date||'').localeCompare(b.due_date||'')}return 0});
 area.innerHTML=list.length?list.map(r=>{
 const s=tab==='students'?r:student(r.student_id);const phone=tab==='enquiries'?r.mobile:s?.mobile;
 let title=r.name||r.subject||r.item||r.title||label(r)||r.reference||r.id;
 let lines=[];
 if(tab==='teacher_tasks')lines=[(records.teacher_access||[]).find(t=>t.account_id===r.teacher_id)?.name,r.instructions,'Due: '+r.due_date,r.status,!['Completed','Not completed'].includes(r.status)&&r.due_date<today()?'OVERDUE':!['Completed','Not completed'].includes(r.status)&&r.due_date===today()?'DUE TODAY':'',...(r.history||[]).map(h=>h.date+' · '+h.status+': '+h.comment)];
 if(tab==='classrooms'){const teacher=(records.teacher_access||[]).find(t=>String(t.account_id)===String(r.teacher_id||r.teacher_account_id||r.teacher));lines=[r.program+' · '+r.academic_year,'Teacher: '+(teacher?.name||'Not assigned'),'Capacity: '+r.capacity,'Assigned students: '+(records.students||[]).filter(s=>s.classroom_id===r.id).length];}
 if(tab==='fee_structures')lines=[classroomName(r.classroom_id),money(r.amount_paise),'Due: '+r.due_date];
 if(tab==='homework')lines=[classroomName(r.classroom_id),r.instructions,'Due: '+r.due_date,r.published?'Published to parents':'Draft'];
 if(tab==='announcements')lines=[r.classroom_id?classroomName(r.classroom_id):'All school parents',r.message,r.published?'Published to parents':'Draft'];
 if(tab==='students')lines=['Student ID: '+r.id,r.program+' · '+r.academic_year,'Class / section: '+classroomName(r.classroom_id),'Parent: '+r.parent,'Mobile: '+r.mobile,'Admission date: '+(r.admission_date||'Not available'),'Uniform size: '+(r.uniform_size||'Not available'),'Kit: '+(r.kit_status||'Inventory link pending'),'Parent app: '+(r.app_status||'Credential status unavailable')];
 if(tab==='enquiries')lines=[r.child_name+' · '+r.program,'Follow-up: '+r.follow_up,r.status,r.follow_up&&r.follow_up<today()&&!['Converted','Lost'].includes(r.status)?'FOLLOW-UP OVERDUE':r.follow_up===today()&&!['Converted','Lost'].includes(r.status)?'FOLLOW-UP TODAY':'',r.notes,r.office_note];
 if(tab==='attendance')lines=[r.date,r.status];
 if(tab==='invoices')lines=[label(r),'Due: '+r.due_date,'Fee: '+money(r.amount_paise),'Received: '+money(paid(r.id)),'Outstanding: '+money(Math.max(0,(Number(r.amount_paise)||0)-paid(r.id))),r.amount_paise<=paid(r.id)?'Paid':r.due_date<today()?'Overdue':'Upcoming / due today'];
 if(tab==='payments')lines=[money(r.amount_paise)+' · '+r.method,r.date,'Reference: '+r.reference,'Receipt ID: '+r.id,r.status];
 if(tab==='orders')lines=[r.category+' · '+r.quantity+' items','Size: '+(r.size||'—'),'For: '+(r.child_name||r.classroom_name||r.order_for||'School stock'),r.status,r.notes,r.office_note];
 if(tab==='ledger')lines=[money(r.amount_paise),r.date,'Reference: '+r.reference,r.status,r.notes,r.office_note];
 if(tab==='support')lines=[r.notes,r.status,r.office_note];
 const tel=(phone||'').replace(/[^+0-9]/g,'');
 return `<article class="portal-card"><h3>${esc(title)}</h3>${lines.filter(Boolean).map(l=>`<p>${esc(l)}</p>`).join('')}<div class="portal-tools">${phone?`<a href="tel:${esc(tel)}">Call parent</a>`:''}${tab==='invoices'?`<button class="secondary" data-remind="${esc(r.id)}">Copy reminder</button>`:''}${tab==='students'?`<button class="secondary" data-profile="${esc(r.id)}">View summary</button><button class="secondary" data-assign="${esc(r.id)}">Assign classroom</button>`:''}${tab==='fee_structures'?`<button data-apply="${esc(r.id)}">Apply to classroom</button>`:''}${['homework','announcements'].includes(tab)?`<button data-publish="${esc(r.id)}">${r.published?'Unpublish':'Publish'}</button>`:''}${(tab==='enquiries'||mode==='admin'&&['orders','ledger','support'].includes(tab))?`<button class="secondary" data-update="${esc(r.id)}">Update status</button>`:''}</div><div data-extra="${esc(r.id)}"></div></article>`;
 }).join(''):'<p class="portal-empty">No matching records. Add your first record above.</p>';
 wireExtras(area);
 area.querySelectorAll('[data-remind]').forEach(b=>b.onclick=async()=>{const i=records.invoices.find(x=>x.id===b.dataset.remind);const balance=Math.max(0,(Number(i.amount_paise)||0)-paid(i.id));const box=b.closest('article').querySelector('[data-extra]');if(balance<=0){box.textContent='No payment is due for this fee request.';return}const text=`Dear parent, ${school.name} reminds you that ${money(balance)} is due for ${label(i)} — ${i.title}, due ${i.due_date}. Please contact the school if you have already paid. Thank you.`;box.textContent=text;try{await navigator.clipboard.writeText(text);(root.querySelector('#portalStatus')||{}).textContent='Reminder copied. Review and send through your messaging app. Nothing has been sent automatically.'}catch{(root.querySelector('#portalStatus')||{}).textContent='Copy the reminder shown on the card and send through your messaging app.'}});
 area.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>{const id=b.dataset.profile;const invoices=records.invoices.filter(x=>x.student_id===id);const at=records.attendance.filter(x=>x.student_id===id);b.closest('article').querySelector('[data-extra]').innerHTML=`<hr><p>Attendance entries: ${at.length} · Present: ${at.filter(x=>x.status==='Present').length}</p><p>Fees outstanding: ${money(invoices.reduce((n,x)=>n+Math.max(0,x.amount_paise-paid(x.id)),0))}</p>${invoices.map(x=>`<p>${esc(x.title)} · ${money(Math.max(0,(Number(x.amount_paise)||0)-paid(x.id)))} outstanding</p>`).join('')}`});
 area.querySelectorAll('[data-update]').forEach(b=>b.onclick=()=>{const box=b.closest('article').querySelector('[data-extra]');const opts=tab==='enquiries'?['New','Contacted','Visit planned','Converted','Lost']:tab==='orders'?['Submitted','Approved','Dispatched','Delivered','Cancelled']:tab==='ledger'?['Pending verification','Verified','Rejected']:['Open','In progress','Resolved'];box.innerHTML=`<form>${select('status','Status',opts)}${input('office_note',tab==='enquiries'?'Follow-up note':'Head-office note','text',false)}<button>Save status</button></form>`;box.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await call(tab,'PATCH',Object.fromEntries(new FormData(e.target)),b.dataset.update);await loadRecords()}catch(error){(root.querySelector('#portalStatus')||{}).textContent=error.message;e.submitter.disabled=false}}});
}

function classroomName(id){return (records.classrooms||[]).find(c=>c.id===id)?.name||'Not assigned'}
function portalNotice(text){(root.querySelector('#portalStatus')||{}).textContent=text}
function wireExtras(area){
 area.querySelectorAll('[data-assign]').forEach(button=>button.onclick=()=>{const box=button.closest('article').querySelector('[data-extra]');box.innerHTML=`<form>${chooseClassroom()}<button>Save classroom</button></form>`;box.querySelector('form').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await call('students','PATCH',Object.fromEntries(new FormData(e.target)),button.dataset.assign);await loadRecords();portalNotice('Classroom assigned.')}catch(error){portalNotice(error.message);e.submitter.disabled=false}}});
 area.querySelectorAll('[data-apply]').forEach(button=>button.onclick=async()=>{const fee=records.fee_structures.find(f=>f.id===button.dataset.apply),count=(records.students||[]).filter(s=>s.classroom_id===fee.classroom_id).length;if(!confirm(`Create ${fee.title} charges of ${money(fee.amount_paise)} each for ${count} students? Existing charges from this structure will be skipped.`))return;button.disabled=true;try{const b=await call('apply_fees','POST',{},fee.id);await loadRecords();portalNotice(`${b.created} new fee requests created. Parents can see them after sign in.`)}catch(e){portalNotice(e.message);button.disabled=false}});
 area.querySelectorAll('[data-publish]').forEach(button=>button.onclick=async()=>{const row=records[tab].find(r=>r.id===button.dataset.publish);button.disabled=true;try{await call(tab,'PATCH',{published:!row.published},row.id);await loadRecords();portalNotice(row.published?'Removed from parent view.':'Published to parents.')}catch(e){portalNotice(e.message);button.disabled=false}});
}
function renderAccess(area){
 const teacher=tab==='teacher_access',accounts=(records[tab]||[]).slice().sort((a,b)=>String(teacher?a.name:student(a.student_id)?.name||'').localeCompare(String(teacher?b.name:student(b.student_id)?.name||''))),activeCount=accounts.filter(a=>a.active).length;
 const teacherCreate=teacher?`<span class="eyebrow word-colors"><i>TEACHER</i> <i>MASTER</i> <i>·</i> <i>SINGLE</i> <i>ENTRY</i></span><h3>Manage teachers</h3><p>Create each teacher once here. The same Teacher ID is reused for classroom assignment, timetable, tasks and academic delivery.</p>`:`<h3>Parent access</h3><p>Create a separate parent login for each child. Parents see only their child’s permitted information.</p>`;
 area.innerHTML=`${teacherCreate}<p>Share login credentials privately. Password reset changes access only; it does not create another person record.</p><div class="portal-grid">${card(teacher?'Teacher accounts':'Access accounts',`<strong class="metric">${accounts.length}</strong><p>${activeCount} enabled · ${accounts.length-activeCount} disabled</p>`)}</div><a href="/${teacher?'teachers':'parents'}.html" target="_blank" rel="noopener">Open ${teacher?'teacher':'parent'} sign in ↗</a><details class="portal-editor" open><summary>＋ ${teacher?'Add / manage teacher':'Create / reset access'}</summary><form id="accessForm"><div class="fields">${teacher?select('account_id','Teacher record',[['new','＋ Add new teacher'],...accounts.map(a=>[a.account_id,a.name])])+input('name','Teacher name')+'<label>Assigned classrooms<select name="classroom_ids" multiple required size="5">'+(records.classrooms||[]).map(c=>`<option value="${esc(c.id)}">${esc(c.name+' · '+c.academic_year)}</option>`).join('')+'</select><small>Reuse the same teacher record for all applicable classrooms.</small></label>':chooseStudent()}<label>Initial / replacement password<input name="password" type="password" required minlength="8" maxlength="128" autocomplete="new-password"></label></div><button>${teacher?'Save teacher':'Save access'}</button></form><div id="accessResult" role="status"></div></details><div class="portal-grid">${accounts.map(a=>`<article class="portal-card"><h3>${esc(teacher?a.name:student(a.student_id)?.name||'Student')}</h3><p>${teacher?'Teacher ID: ':'Account ID: '}${esc(a.account_id)}</p><p>${a.active?'Access enabled':'Access disabled'}</p>${teacher?`<p>Assigned: ${esc(a.classroom_ids.map(classroomName).join(', ')||'No classroom yet')}</p>`:''}<button class="secondary" data-disable="${esc(teacher?a.account_id:a.student_id)}" ${!a.active?'disabled':''}>${a.active?'Disable access':'Access disabled'}</button></article>`).join('')}</div>`;
 if(teacher){const f=area.querySelector('#accessForm');f.elements.account_id.onchange=()=>{const a=accounts.find(a=>a.account_id===f.elements.account_id.value);f.elements.name.value=a?.name||'';for(const o of f.elements.classroom_ids.options)o.selected=!!a?.classroom_ids.includes(o.value);f.elements.password.value=''};}
 area.querySelector('#accessForm').onsubmit=async e=>{e.preventDefault();const form=e.target,fd=new FormData(form),body=Object.fromEntries(fd),id=teacher?(body.account_id==='new'?'':body.account_id):body.student_id;if(teacher)body.classroom_ids=fd.getAll('classroom_ids');e.submitter.disabled=true;try{const b=await call(tab,'POST',body,id);form.reset();await loadRecords();root.querySelector('#accessResult').textContent=(teacher?'Teacher ID: ':'Account ID: ')+b.account_id+'. Credentials can be shared through the usual private channel.'}catch(error){portalNotice(error.message);e.submitter.disabled=false}};
 area.querySelectorAll('[data-disable]').forEach(button=>button.onclick=async()=>{if(!confirm('Disable this login and invalidate its active sessions?'))return;button.disabled=true;try{await call(tab,'POST',{disable:true},button.dataset.disable);await loadRecords()}catch(e){portalNotice(e.message);button.disabled=false}});
}
})();
