/* Neo timetable administration: Draft -> Save -> Edit -> Publish. */
(()=>{
 const original=window.renderNeoLearning;
 if(typeof original!=='function')return;
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const days=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
 window.renderNeoLearning=async function(area,ctx){
  if(ctx.tab!=='timetable')return original(area,ctx);
  const api=async(path,body)=>{const r=await fetch('https://neo-lead-crm-api.umakanthgilla.workers.dev/api/learning/'+path+'?school_id='+encodeURIComponent(ctx.school.school_id),{method:body?'POST':'GET',headers:{Authorization:'Bearer '+ctx.token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Request failed');return b};
  const classroom=id=>ctx.classrooms.find(c=>c.id===id)?.name||id;
  const teacher=id=>ctx.teachers.find(t=>t.account_id===id)?.name||id;
  area.innerHTML='<p>Loading timetable…</p>';
  try{
   const state=await api('timetable');
   let revision=Number(state.revision||0),status=state.status||'Draft',publishedAt=state.published_at||null,slots=Array.isArray(state.slots)?state.slots.map(x=>({...x})):[],editing=-1,dirty=false;
   area.innerHTML=`<div class="row" style="align-items:flex-start"><div><h3>Weekly timetable</h3><p>Create and save a draft first. Teachers and parents receive only the published timetable.</p></div><span id="ttStatus" class="portal-pill"></span></div><div class="panel"><form id="ttForm"><div class="fields"><label>Teacher<select name="teacher_id" required><option value="">Choose…</option>${ctx.teachers.filter(t=>t.active).map(t=>`<option value="${esc(t.account_id)}">${esc(t.name)}</option>`).join('')}</select></label><label>Weekday<select name="weekday">${days.map((d,i)=>`<option value="${i}">${d}</option>`).join('')}</select></label><label>Type<select name="type"><option>Teaching</option><option>Break</option><option>Planning</option></select></label><label>Subject / label<input name="subject" required maxlength="100"></label><label>Classroom<select name="classroom_id"><option value="">Not applicable</option>${ctx.classrooms.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label><label>Start<input name="start" type="time" required></label><label>End<input name="end" type="time" required></label></div><button id="ttAdd">Add to draft</button> <button type="button" id="ttCancel" class="secondary" hidden>Cancel edit</button></form></div><p id="ttMessage" role="status"></p><div id="ttList"></div><div class="actions"><button id="ttSave" class="secondary">Save Draft</button><button id="ttPublish">Publish Timetable</button><button id="ttDownload" class="secondary">Download Published Timetable</button></div>`;
   const msg=t=>area.querySelector('#ttMessage').textContent=t;
   const setStatus=()=>{const n=area.querySelector('#ttStatus');n.textContent=(dirty?'Unsaved changes · ':'')+status+' · Revision '+revision+(publishedAt?' · Published '+new Date(publishedAt).toLocaleString('en-IN'):'');area.querySelector('#ttDownload').disabled=status!=='Published'};
   const form=area.querySelector('#ttForm');
   const reset=()=>{editing=-1;form.reset();area.querySelector('#ttAdd').textContent='Add to draft';area.querySelector('#ttCancel').hidden=true};
   const draw=()=>{const ordered=slots.map((s,i)=>({s,i})).sort((a,b)=>a.s.weekday-b.s.weekday||a.s.start.localeCompare(b.s.start));area.querySelector('#ttList').innerHTML='<div class="table-wrap"><table><thead><tr><th>Teacher</th><th>Day</th><th>Time</th><th>Period</th><th>Classroom</th><th>Draft actions</th></tr></thead><tbody>'+ordered.map(({s,i})=>`<tr><td>${esc(teacher(s.teacher_id))}</td><td>${esc(days[s.weekday])}</td><td>${esc(s.start)}–${esc(s.end)}</td><td>${esc(s.type)}: ${esc(s.subject)}</td><td>${esc(s.classroom_id?classroom(s.classroom_id):'—')}</td><td><button type="button" class="secondary" data-edit="${i}">Edit</button> <button type="button" class="secondary" data-remove="${i}">Remove</button></td></tr>`).join('')+'</tbody></table></div>'+(slots.length?'':'<p class="portal-empty">No timetable periods in this draft yet.</p>');area.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{slots.splice(Number(b.dataset.remove),1);dirty=true;reset();draw();setStatus();msg('Period removed from draft. Save Draft to keep this change.')});area.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{editing=Number(b.dataset.edit);const s=slots[editing];for(const k of ['teacher_id','weekday','type','subject','classroom_id','start','end'])form.elements[k].value=s[k]??'';area.querySelector('#ttAdd').textContent='Update draft period';area.querySelector('#ttCancel').hidden=false;form.scrollIntoView({behavior:'smooth',block:'center'})})};
   form.onsubmit=e=>{e.preventDefault();const s=Object.fromEntries(new FormData(form));s.weekday=Number(s.weekday);if(s.type==='Teaching'&&!s.classroom_id){msg('Teaching periods need a classroom.');return}if(s.start>=s.end){msg('End time must be after start time.');return}if(editing>=0)slots[editing]=s;else slots.push(s);dirty=true;reset();draw();setStatus();msg('Draft changed. Save Draft before publishing.')};
   area.querySelector('#ttCancel').onclick=reset;
   const save=async action=>{const b=await api('timetable',{revision,slots,action});revision=Number(b.revision);status=b.status|| (action==='publish'?'Published':'Draft');publishedAt=b.published_at||publishedAt;dirty=false;setStatus();msg(action==='publish'?'Timetable published. Teachers and parents can refresh to see the published schedule.':'Draft saved. It is not visible to teachers or parents until you publish it.')};
   area.querySelector('#ttSave').onclick=async e=>{e.target.disabled=true;try{await save('save')}catch(err){msg(err.message)}finally{e.target.disabled=false}};
   area.querySelector('#ttPublish').onclick=async e=>{if(dirty){msg('Save Draft first, then publish the saved timetable.');return}if(!slots.length){msg('Add at least one timetable period before publishing.');return}if(!confirm('Publish this timetable to assigned teachers and parents?'))return;e.target.disabled=true;try{await save('publish')}catch(err){msg(err.message)}finally{e.target.disabled=false}};
   area.querySelector('#ttDownload').onclick=async e=>{e.target.disabled=true;try{const fresh=await api('timetable');if(fresh.status!=='Published')throw Error('Publish the timetable before downloading it.');const rows=(fresh.published_slots||fresh.slots||[]).map(s=>({Teacher:teacher(s.teacher_id),Day:days[s.weekday],Start:s.start,End:s.end,Type:s.type,Subject:s.subject,Classroom:s.classroom_id?classroom(s.classroom_id):''}));if(!rows.length)throw Error('No published timetable periods to download.');await window.neoExport('neo-published-timetable',rows);msg('Published timetable download prepared.')}catch(err){msg(err.message)}finally{e.target.disabled=status!=='Published'}};
   draw();setStatus();
  }catch(e){area.innerHTML='<h3>Weekly timetable</h3><p role="alert">'+esc(e.message)+'</p>'}
 };
})();
