/* Neo School India transport: school setup, child-scoped parent view, separate driver operations. */
(function(){
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const opt=(rows,label)=>rows.map(r=>`<option value="${esc(r.id)}">${esc(label(r))}</option>`).join('');
 const field=(name,label,type='text')=>`<label>${label}<input name="${name}" type="${type}" required></label>`;
 const choose=(name,label,options)=>`<label>${label}<select name="${name}" required><option value="">Choose…</option>${options}</select></label>`;
 const form=(name,fields,kind)=>`<form class="panel transport-form" data-kind="${kind}"><h3>${name}</h3><div class="portal-grid">${fields}</div><button>Save ${name}</button></form>`;
 const dates=['insurance','pollution','fitness','tax'];
 const status=(area,msg)=>{const el=area.querySelector('[data-transport-status]');if(el)el.textContent=msg};
 async function school(area,{school,token,base}){
  const endpoint=base+'/api/transport/school/';
  const api=async(kind,method='GET',body,id='')=>{const r=await fetch(endpoint+kind+'/'+encodeURIComponent(school.school_id)+(id?'/'+encodeURIComponent(id):''),{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Transport unavailable.');return d};
  async function draw(){
   try{
    const [d,access]=await Promise.all([api('routes'),api('access')]),vehicles=d.vehicles.filter(v=>v.active),routes=d.routes.filter(r=>r.active),assignments=d.assignments.filter(a=>a.active),classrooms=d.classrooms||[],programs=[...new Set(classrooms.map(c=>c.program))],available=d.students.filter(s=>!d.assignments.some(a=>a.student_id===s.id)),staff=d.staff.filter(s=>s.status!=='Inactive'),names=new Map(d.students.map(s=>[s.id,s.name])),today=new Date(Date.now()+330*60000).toISOString().slice(0,10);
    area.innerHTML=`<div class="learning-welcome"><div><span class="eyebrow">SCHOOL OPERATIONS · TRANSPORT</span><h2>Transport</h2><p>Manage vehicles, routes, staff access and locked child assignments. Drivers record daily trips in their separate portal.</p></div></div><p class="portal-status" data-transport-status role="status"></p><div class="portal-grid">`+
     form('Vehicle',field('registration_no','Registration number')+field('label','Vehicle name')+field('capacity','Seating capacity','number')+dates.map(k=>field(k+'_expiry',k[0].toUpperCase()+k.slice(1)+' expiry','date')).join(''),'vehicles')+
     form('Route',field('name','Route name')+choose('vehicle_id','Vehicle',opt(vehicles,v=>v.registration_no+' · '+v.label))+choose('driver_staff_id','Driver (Staff Master)',opt(staff,s=>s.name+' · '+s.id))+`<label>Vehicle attendant (Staff Master)<select name="attendant_staff_id"><option value="">No attendant</option>${opt(staff,s=>s.name+' · '+s.id)}</select></label><label>Daily trip runs<select name="trip_count"><option value="1">One</option><option value="2">Two</option></select></label><label>Stops in pickup order, one per line<textarea name="stops" rows="4" required></textarea></label>`,'routes')+
     form('Child assignment',choose('route_id','Route',opt(routes,r=>r.name))+`<label>Class<select name="program" required><option value="">Choose class…</option>${programs.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join('')}</select></label><label>Section<select name="classroom_id" required><option value="">Select class first</option></select></label><label>Student<select name="student_id" required><option value="">Select section first</option></select></label><label>Stop<select name="stop" required><option value="">Select route first</option></select></label><label class="transport-run" hidden>Trip run<select name="run_no"><option value="1">Run 1</option><option value="2">Run 2</option></select></label><p>Each child can be assigned once. The saved route is locked.</p>`,'assignments')+
     form('Driver / attendant access',choose('staff_id','Assigned staff',opt(staff,s=>s.name+' · '+s.id))+`<label>Role<select name="role"><option>Driver</option><option>Attendant</option></select></label>${field('password','New password','password')}<p>Use 8 or more characters with upper and lower case letters, a number and a symbol. Reissuing access resets the password.</p>`,'access')+'</div>'+
     `<section class="panel"><h3>Vehicles and renewal dates</h3>${vehicles.map(v=>`<div class="transport-row"><b>${esc(v.registration_no)} · ${esc(v.label)}</b><p>${dates.map(k=>esc(k)+' '+esc(v[k+'_expiry']||'not set')).join(' · ')}</p><form data-renew="${esc(v.id)}" class="portal-grid">${dates.map(k=>`<label>${esc(k)}<input type="date" name="${k}_expiry" value="${esc(v[k+'_expiry']||'')}" required></label>`).join('')}<button>Save renewal dates</button></form></div>`).join('')||'<p>No vehicles yet.</p>'}</section>`+
     `<section class="panel"><h3>Routes and assigned children</h3>${routes.map(r=>`<div class="transport-row"><b>${esc(r.name)}</b> · ${esc(d.vehicles.find(v=>v.id===r.vehicle_id)?.registration_no||'')} · ${esc(d.staff.find(s=>s.id===r.driver_staff_id)?.name||'')}<p>Stops: ${esc(r.stops.join(' → '))} · ${Number(r.trip_count||1)} run(s)</p><p>Children: ${esc(assignments.filter(a=>a.route_id===r.id).map(a=>(names.get(a.student_id)||a.student_id)+' ('+a.stop+', run '+(a.run_no||1)+')').join(', ')||'None')}</p></div>`).join('')||'<p>No routes yet.</p>'}</section>`+
     `<section class="panel"><h3>Driver portal access</h3><p>Share the transport ID and password privately with the assigned staff. Portal: <a href="driver.html">Driver / Attendant login</a>.</p>${access.accounts.map(a=>`<p>${esc(a.account_id)} · ${esc(d.staff.find(s=>s.id===a.staff_id)?.name||a.staff_id)} · ${esc(a.role)}</p>`).join('')||'<p>No accounts yet.</p>'}</section>`+
     `<section class="panel"><h3>Today's trip monitor</h3>${d.trips.filter(t=>t.date===today).map(t=>`<div class="transport-row"><b>${esc(routes.find(r=>r.id===t.route_id)?.name||t.route_id)} · ${esc(t.direction)} · Run ${esc(t.run_no||1)}</b><p>${esc(t.status)} · ${(t.events||[]).length} child updates · Start ${esc(t.odometer_start_km??'—')} km · Finish ${esc(t.odometer_end_km??'—')} km</p><div class="actions"><button type="button" class="secondary" data-photo="${esc(t.id)}" data-phase="start">Start photo</button>${t.status==='Completed'?`<button type="button" class="secondary" data-photo="${esc(t.id)}" data-phase="finish">Finish photo</button>`:''}</div></div>`).join('')||'<p>No trip started today.</p>'}</section>`;
    area.querySelectorAll('[data-photo]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const r=await fetch(base+'/api/transport/photo/'+encodeURIComponent(button.dataset.photo)+'/'+button.dataset.phase,{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw Error('Photo unavailable.');const url=URL.createObjectURL(await r.blob());{const image=document.createElement('img');image.src=url;image.alt='Vehicle odometer '+button.dataset.phase+' photo';image.style.cssText='max-width:100%;max-height:320px;display:block;margin-top:12px;border-radius:12px';button.parentElement.appendChild(image);image.onload=()=>setTimeout(()=>URL.revokeObjectURL(url),60000)}}catch(err){status(area,err.message)}finally{button.disabled=false}});
    const assignment=area.querySelector('[data-kind="assignments"]'),routeSelect=assignment.querySelector('[name="route_id"]'),stop=assignment.querySelector('[name="stop"]'),run=assignment.querySelector('.transport-run');
    routeSelect.onchange=()=>{const r=routes.find(x=>x.id===routeSelect.value);stop.innerHTML='<option value="">Choose stop…</option>'+(r?.stops||[]).map(s=>`<option>${esc(s)}</option>`).join('');run.hidden=Number(r?.trip_count||1)<2};
    const program=assignment.querySelector('[name="program"]'),section=assignment.querySelector('[name="classroom_id"]'),student=assignment.querySelector('[name="student_id"]');
    program.onchange=()=>{section.innerHTML='<option value="">Choose section…</option>'+opt(classrooms.filter(c=>c.program===program.value),c=>c.name+' · '+(c.academic_year||''));student.innerHTML='<option value="">Select section first</option>'};
    section.onchange=()=>student.innerHTML='<option value="">Choose student…</option>'+opt(available.filter(s=>s.classroom_id===section.value),s=>s.name);
    area.querySelectorAll('form.transport-form').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const body=Object.fromEntries(new FormData(f));if(f.dataset.kind==='routes')body.stops=body.stops.split('\n').map(s=>s.trim()).filter(Boolean);if(f.dataset.kind==='vehicles')body.capacity=Number(body.capacity);if(f.dataset.kind==='access'){const result=await api('access','POST',body);await draw();status(area,'Access saved. Transport ID: '+result.account_id+' — share the password privately.');return}body.request_id=crypto.randomUUID();await api(f.dataset.kind,'POST',body);await draw()}catch(err){status(area,err.message);button.disabled=false}});
    area.querySelectorAll('form[data-renew]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{await api('compliance','PATCH',Object.fromEntries(new FormData(f)),f.dataset.renew);await draw()}catch(err){status(area,err.message);e.submitter.disabled=false}});
   }catch(err){area.innerHTML=`<section class="panel portal-error"><h3>Transport unavailable</h3><p>${esc(err.message)}</p><button data-retry>Retry</button></section>`;area.querySelector('[data-retry]').onclick=draw}
  }
  await draw();
 }
 async function parent(area,{token,base}){
  try{const r=await fetch(base+'/api/transport/parent/me',{headers:{Authorization:'Bearer '+token}}),d=await r.json();if(!r.ok)throw Error(d.error||'Transport unavailable.');area.innerHTML=`<div class="learning-welcome"><div><span class="eyebrow">MY CHILD · TRANSPORT</span><h2>Transport</h2><p>Today's pickup, drop and route updates.</p></div></div><section class="panel"><h3>Today's alerts</h3>${(d.alerts||[]).map(a=>`<p class="transport-row">${esc(a.message)} <small>${esc(new Date(a.at).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'}))}</small></p>`).join('')||'<p>No alerts yet.</p>'}</section>`+(d.assignments.length?d.assignments.map(a=>{const route=d.routes.find(r=>r.id===a.route_id),vehicle=d.vehicles.find(v=>v.id===route?.vehicle_id);return `<section class="panel"><h3>${esc(route?.name||'Assigned route')}</h3><p>Stop: ${esc(a.stop)} · Run ${esc(a.run_no||1)} · Vehicle ${esc(vehicle?.registration_no||'Pending')}</p>${d.trips.filter(t=>t.route_id===a.route_id&&Number(t.run_no||1)===Number(a.run_no||1)).map(t=>`<div class="transport-row"><b>${esc(t.direction)} · ${esc(t.status)}</b><p>${esc((t.events||[]).map(e=>e.type).join(' · ')||'No child update yet')}</p></div>`).join('')}</section>`}).join(''):'<section class="panel"><p>No transport assignment for your child.</p></section>');setTimeout(()=>{if(area.isConnected&&area.getClientRects().length)parent(area,{token,base})},30000)}catch(err){area.innerHTML=`<section class="panel portal-error"><h3>Transport unavailable</h3><p>${esc(err.message)}</p></section>`}
 }
 window.NeoTransport={school,parent};
})();
