(()=>{
'use strict';
if(window.__neoVisitorGate)return;window.__neoVisitorGate=true;
let currentSchool=null,rendering=false,timer=0,liveTimer=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const root=()=>document.getElementById('neoWorkspace');
const activeTab=()=>root()?.querySelector('.neo-department-nav [data-tab][aria-pressed="true"]')?.dataset.tab||'';
const base=()=>typeof BASE==='string'?BASE:'';
const auth=()=>typeof token==='string'?token:'';
const prevOpen=window.openNeoWorkspace;if(typeof prevOpen==='function')window.openNeoWorkspace=function(s){currentSchool=s||null;return prevOpen.apply(this,arguments)};
const prevClose=window.closeNeoWorkspace;if(typeof prevClose==='function')window.closeNeoWorkspace=function(){currentSchool=null;return prevClose.apply(this,arguments)};
async function api(path,method='GET',body){
 if(!currentSchool?.school_id)throw Error('Open a school portal first.');
 const r=await fetch(base()+'/api/visitor-gate/school/'+encodeURIComponent(currentSchool.school_id)+(path?'/'+path:''),{method,headers:{Authorization:'Bearer '+auth(),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 const d=await r.json().catch(()=>({error:'Unreadable server response.'}));if(!r.ok)throw Error(d.error||(r.status===404?'Visitor & Gate Worker update is not deployed yet.':'Visitor & Gate unavailable.'));return d;
}
const option=(rows,label)=>rows.map(x=>`<option value="${esc(x.id)}">${esc(label(x))}</option>`).join('');
const nowTime=v=>v?new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'—';
function status(text){const n=root()?.querySelector('#portalStatus');if(n)n.textContent=text||'';}
function pickupActions(p){if(p.status==='Waiting parent confirmation')return `<button class="secondary" data-pickup-action="reject" data-id="${esc(p.id)}">Reject request</button>`;if(p.status==='Parent confirmed')return `<button data-pickup-action="approve_gate_pass" data-id="${esc(p.id)}">Approve gate pass</button><button class="secondary" data-pickup-action="reject" data-id="${esc(p.id)}">Reject</button>`;if(p.status==='Approved for release')return `<button data-pickup-action="release" data-id="${esc(p.id)}">Release child</button><button class="secondary" data-pickup-action="reject" data-id="${esc(p.id)}">Cancel pass</button>`;return ''}
async function render(){
 if(rendering||activeTab()!=='visitor_gate'||!currentSchool)return;
 const area=root()?.querySelector('#portalContent');if(!area)return;rendering=true;if(!area.querySelector('#neoVisitorGate'))area.innerHTML='<p class="portal-empty">Loading Visitor & Gate…</p>';
 try{
  const d=await api('');if(activeTab()!=='visitor_gate')return;
  const visitors=d.visitors||[],pickups=d.pickups||[],staff=(d.staff||[]).filter(x=>x.status!=='Inactive'),students=(d.students||[]).filter(x=>x.status!=='Withdrawn');
  const inside=visitors.filter(x=>x.status==='Inside').length,waiting=visitors.filter(x=>x.status==='Waiting approval').length,pickupWaiting=pickups.filter(x=>['Waiting parent confirmation','Parent confirmed','Approved for release'].includes(x.status)).length;
  const publicUrl=location.origin+'/gate-checkin.html?school_id='+encodeURIComponent(currentSchool.school_id),qr='https://api.qrserver.com/v1/create-qr-code/?size=220x220&margin=8&data='+encodeURIComponent(publicUrl);
  area.innerHTML=`<div id="neoVisitorGate"><span class="eyebrow">FRONT OFFICE · CHILD SAFETY</span><h2>Visitor & Gate</h2><p>Gate staff can enter a request manually, or visitors can scan the permanent school QR and submit from their own phone. Child pickup requires parent confirmation first and school approval second.</p><div class="portal-grid"><article class="portal-card"><p>Visitors inside</p><strong class="metric">${inside}</strong></article><article class="portal-card"><p>Visitor approvals waiting</p><strong class="metric">${waiting}</strong></article><article class="portal-card"><p>Pickup actions waiting</p><strong class="metric">${pickupWaiting}</strong></article></div>
  <article class="portal-card" style="margin:16px 0"><div style="display:grid;grid-template-columns:minmax(180px,240px) 1fr;gap:20px;align-items:center"><div style="text-align:center"><img src="${esc(qr)}" alt="Gate self check-in QR code" style="width:min(220px,100%);background:white;border:1px solid #dbe4ef;border-radius:14px;padding:8px"></div><div><span class="eyebrow">PERMANENT SCHOOL GATE QR</span><h3>Scan for Visitor Check-in or Child Pickup</h3><p>Print this QR once and display it at the gate/reception. The public page does not expose the student list or parent contact details.</p><p><a href="${esc(publicUrl)}" target="_blank" rel="noopener">Open self check-in page</a></p><div class="actions"><button type="button" data-copy-gate-link>Copy gate link</button><button type="button" class="secondary" data-print-gate-qr>Print QR</button></div></div></div></article>
  <div class="portal-grid"><details class="portal-editor"><summary>＋ Manual visitor check-in</summary><form data-gate-form="visitor"><div class="fields"><label>Visitor name<input name="name" required maxlength="120"></label><label>Mobile<input name="mobile" required maxlength="20"></label><label>Purpose<select name="purpose" required><option value="">Choose…</option><option>Meet teacher</option><option>Meet principal / in-charge</option><option>Admission enquiry</option><option>Vendor / delivery</option><option>Service / maintenance</option><option>Official visit</option><option>Other</option></select></label><label>Whom to meet<select name="host_staff_id"><option value="">School office / general</option>${option(staff,s=>s.name+' · '+s.id)}</select></label><label>Company / organisation<input name="company" maxlength="120"></label><label>Vehicle number<input name="vehicle_no" maxlength="30"></label><label>ID type<select name="id_type"><option value="">Not recorded</option><option>Aadhaar</option><option>Driving licence</option><option>Employee ID</option><option>Other</option></select></label><label>ID last 4 only<input name="id_last4" maxlength="4" inputmode="numeric" pattern="[0-9]{4}"></label><label class="full-width">Note<textarea name="note" maxlength="500"></textarea></label></div><button>Submit visitor request</button></form></details>
  <details class="portal-editor"><summary>＋ Manual child pickup request</summary><form data-gate-form="pickup"><div class="fields"><label>Student<select name="student_id" required><option value="">Choose child…</option>${option(students,s=>s.name+' · '+s.program+' · '+s.id)}</select></label><label>Pickup person<input name="pickup_name" required maxlength="120"></label><label>Mobile<input name="mobile" required maxlength="20"></label><label>Relationship<input name="relationship" required maxlength="80"></label><label>Recorded by<select name="verifier_staff_id"><option value="">School office</option>${option(staff,s=>s.name+' · '+s.id)}</select></label><label class="full-width">Note<textarea name="note" maxlength="500"></textarea></label></div><button>Send parent confirmation request</button></form></details></div>
  <h3>Visitor register</h3><div class="portal-grid">${visitors.map(v=>`<article class="portal-card"><h4>${esc(v.name)}</h4><p><b>${esc(v.gate_pass||'Gate pass pending')}</b> · ${esc(v.status)}</p><p>${esc(v.purpose)}${v.host_name?' · Meet '+esc(v.host_name):''}</p><p>In: ${esc(nowTime(v.checkin_at))}${v.valid_until&&v.status==='Inside'?' · Valid until: '+esc(nowTime(v.valid_until)):''}${v.checkout_at?' · Out: '+esc(nowTime(v.checkout_at)):''}</p><div class="actions">${v.status==='Waiting approval'?`<button data-visitor-action="approve" data-id="${esc(v.id)}">Approve entry</button><button class="secondary" data-visitor-action="reject" data-id="${esc(v.id)}">Reject</button>`:''}${v.status==='Inside'?`<button data-visitor-action="checkout" data-id="${esc(v.id)}">Check out</button>`:''}</div></article>`).join('')||'<p class="portal-empty">No visitor entries yet.</p>'}</div>
  <h3>Child pickup register</h3><div class="portal-grid">${pickups.map(p=>`<article class="portal-card"><h4>${esc(p.student_name||p.student_id)}</h4><p>${esc(p.pickup_name)} · ${esc(p.relationship)} · Parent: <b>${esc(p.parent_status||'Legacy flow')}</b></p><p><b>${esc(p.gate_pass||'Pickup pass pending')}</b> · ${esc(p.status)}</p><p>${esc(nowTime(p.created_at))}${p.parent_confirmed_at?' · Parent confirmed '+esc(nowTime(p.parent_confirmed_at)):''}${p.valid_until&&p.status==='Approved for release'?' · Pass valid until '+esc(nowTime(p.valid_until)):''}${p.released_at?' · Released '+esc(nowTime(p.released_at)):''}</p><div class="actions">${pickupActions(p)}</div></article>`).join('')||'<p class="portal-empty">No child pickup requests yet.</p>'}</div></div>`;
  area.querySelector('[data-copy-gate-link]')?.addEventListener('click',async e=>{try{await navigator.clipboard.writeText(publicUrl);status('✓ Gate self check-in link copied.')}catch{status('Gate link: '+publicUrl)}});
  area.querySelector('[data-print-gate-qr]')?.addEventListener('click',()=>{const w=open('','_blank');if(!w)return;w.document.write(`<title>Neo School India Gate QR</title><body style="font-family:system-ui;text-align:center;padding:40px;color:#071b52"><img src="/neo-top-logo.jpeg" style="width:180px"><h1>${esc(currentSchool.name||'Neo School India')}</h1><h2>Visitor Check-in & Child Pickup</h2><p>Scan this QR at the school gate.</p><img src="${esc(qr)}" style="width:300px"><p style="word-break:break-all">${esc(publicUrl)}</p></body>`);w.document.close();setTimeout(()=>w.print(),700)});
  area.querySelectorAll('[data-gate-form]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const body=Object.fromEntries(new FormData(form));body.request_id=crypto.randomUUID();try{await api(form.dataset.gateForm,'POST',body);status(form.dataset.gateForm==='pickup'?'✓ Pickup request sent to parent confirmation flow.':'✓ Visitor request saved.');rendering=false;await render()}catch(err){status(err.message);b.disabled=false}});
  area.querySelectorAll('[data-visitor-action]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('visitor/'+encodeURIComponent(b.dataset.id),'PATCH',{action:b.dataset.visitorAction});status('✓ Visitor status updated.');rendering=false;await render()}catch(err){status(err.message);b.disabled=false}});
  area.querySelectorAll('[data-pickup-action]').forEach(b=>b.onclick=async()=>{if(b.dataset.pickupAction==='release'&&!confirm('Parent and school approvals are complete. Release this child now?'))return;b.disabled=true;try{await api('pickup/'+encodeURIComponent(b.dataset.id),'PATCH',{action:b.dataset.pickupAction});status('✓ Pickup status updated.');rendering=false;await render()}catch(err){status(err.message);b.disabled=false}});
 }catch(err){area.innerHTML=`<div id="neoVisitorGate" class="portal-error"><h3>Visitor & Gate backend pending</h3><p>${esc(err.message)}</p><p>No browser-only visitor or child-release records are created.</p></div>`;}finally{rendering=false;}
}
function schedule(){clearTimeout(timer);timer=setTimeout(render,0)}
document.addEventListener('click',e=>{if(e.target.closest('#neoWorkspace [data-tab="visitor_gate"]'))schedule()},true);
window.addEventListener('neo:open-tab',e=>{if(e.detail?.tab==='visitor_gate')schedule()});
new MutationObserver(()=>{if(activeTab()==='visitor_gate'&&!root()?.querySelector('#neoVisitorGate'))schedule()}).observe(document.body,{childList:true,subtree:true});
liveTimer=setInterval(()=>{if(activeTab()==='visitor_gate'&&currentSchool&&!rendering)render()},10000);
})();
