(()=>{
'use strict';
if(window.__neoVisitorGate)return;window.__neoVisitorGate=true;
let currentSchool=null,rendering=false,timer=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const root=()=>document.getElementById('neoWorkspace');
const activeTab=()=>root()?.querySelector('.neo-department-nav [data-tab][aria-pressed="true"]')?.dataset.tab||'';
const base=()=>typeof BASE==='string'?BASE:'';
const auth=()=>typeof token==='string'?token:'';
const prevOpen=window.openNeoWorkspace;if(typeof prevOpen==='function')window.openNeoWorkspace=function(s){currentSchool=s||null;return prevOpen.apply(this,arguments)};
const prevClose=window.closeNeoWorkspace;if(typeof prevClose==='function')window.closeNeoWorkspace=function(){currentSchool=null;return prevClose.apply(this,arguments)};
async function api(path,method='GET',body){
 if(!currentSchool?.school_id)throw Error('Open a school portal first.');
 const r=await fetch(base()+'/api/visitor-gate/school/'+encodeURIComponent(currentSchool.school_id)+(path?'/'+path:''),{method,headers:{Authorization:'Bearer '+auth(),'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
 const d=await r.json().catch(()=>({error:'Unreadable server response.'}));if(!r.ok)throw Error(d.error||(r.status===404?'Visitor & Gate Worker update is not deployed yet.':'Visitor & Gate unavailable.'));return d;
}
const option=(rows,label)=>rows.map(x=>`<option value="${esc(x.id)}">${esc(label(x))}</option>`).join('');
const nowTime=v=>v?new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'—';
function status(text){const n=root()?.querySelector('#portalStatus');if(n)n.textContent=text||'';}
async function render(){
 if(rendering||activeTab()!=='visitor_gate'||!currentSchool)return;
 const area=root()?.querySelector('#portalContent');if(!area)return;rendering=true;area.innerHTML='<p class="portal-empty">Loading Visitor & Gate…</p>';
 try{
  const d=await api('');if(activeTab()!=='visitor_gate')return;
  const visitors=d.visitors||[],pickups=d.pickups||[],staff=(d.staff||[]).filter(x=>x.status!=='Inactive'),students=(d.students||[]).filter(x=>x.status!=='Withdrawn');
  const inside=visitors.filter(x=>x.status==='Inside').length,waiting=visitors.filter(x=>x.status==='Waiting approval').length,pickupWaiting=pickups.filter(x=>x.status==='Waiting approval').length;
  area.innerHTML=`<div id="neoVisitorGate"><span class="eyebrow">FRONT OFFICE · CHILD SAFETY</span><h2>Visitor & Gate</h2><p>Record who entered, why they came, whom they are meeting, and when they left. Child pickup is a separate authorisation flow.</p><div class="portal-grid"><article class="portal-card"><p>Visitors inside</p><strong class="metric">${inside}</strong></article><article class="portal-card"><p>Visitor approvals waiting</p><strong class="metric">${waiting}</strong></article><article class="portal-card"><p>Child pickups waiting</p><strong class="metric">${pickupWaiting}</strong></article></div>
  <div class="portal-grid"><details class="portal-editor" open><summary>＋ Visitor check-in</summary><form data-gate-form="visitor"><div class="fields"><label>Visitor name<input name="name" required maxlength="120"></label><label>Mobile<input name="mobile" required maxlength="20"></label><label>Purpose<select name="purpose" required><option value="">Choose…</option><option>Meet teacher</option><option>Meet principal / in-charge</option><option>Admission enquiry</option><option>Vendor / delivery</option><option>Service / maintenance</option><option>Official visit</option><option>Other</option></select></label><label>Whom to meet<select name="host_staff_id"><option value="">School office / general</option>${option(staff,s=>s.name+' · '+s.id)}</select></label><label>Company / organisation<input name="company" maxlength="120"></label><label>Vehicle number<input name="vehicle_no" maxlength="30"></label><label>ID type<select name="id_type"><option value="">Not recorded</option><option>Aadhaar</option><option>Driving licence</option><option>Employee ID</option><option>Other</option></select></label><label>ID last 4 only<input name="id_last4" maxlength="4" inputmode="numeric" pattern="[0-9]{4}"></label><label class="full-width">Note<textarea name="note" maxlength="500"></textarea></label></div><button>Check in & create gate pass</button></form></details>
  <details class="portal-editor"><summary>＋ Child pickup authorisation</summary><form data-gate-form="pickup"><div class="fields"><label>Student<select name="student_id" required><option value="">Choose child…</option>${option(students,s=>s.name+' · '+s.program+' · '+s.id)}</select></label><label>Pickup person<input name="pickup_name" required maxlength="120"></label><label>Mobile<input name="mobile" required maxlength="20"></label><label>Relationship<input name="relationship" required maxlength="80"></label><label>Authorisation method<select name="authorization_method" required><option value="">Choose…</option><option>Pickup card</option><option>Parent confirmation</option><option>School approval</option><option>Known guardian</option><option>Other</option></select></label><label>Reference / last 4<input name="reference" maxlength="80"></label><label>Verified by<select name="verifier_staff_id"><option value="">School office</option>${option(staff,s=>s.name+' · '+s.id)}</select></label><label class="full-width">Note<textarea name="note" maxlength="500"></textarea></label></div><button>Create pickup request</button></form></details></div>
  <h3>Visitor register</h3><div class="portal-grid">${visitors.map(v=>`<article class="portal-card"><h4>${esc(v.name)}</h4><p><b>${esc(v.gate_pass||'Gate pass pending')}</b> · ${esc(v.status)}</p><p>${esc(v.purpose)}${v.host_name?' · Meet '+esc(v.host_name):''}</p><p>In: ${esc(nowTime(v.checkin_at))}${v.checkout_at?' · Out: '+esc(nowTime(v.checkout_at)):''}</p><div class="actions">${v.status==='Waiting approval'?`<button data-visitor-action="approve" data-id="${esc(v.id)}">Approve entry</button><button class="secondary" data-visitor-action="reject" data-id="${esc(v.id)}">Reject</button>`:''}${v.status==='Inside'?`<button data-visitor-action="checkout" data-id="${esc(v.id)}">Check out</button>`:''}</div></article>`).join('')||'<p class="portal-empty">No visitor entries yet.</p>'}</div>
  <h3>Child pickup register</h3><div class="portal-grid">${pickups.map(p=>`<article class="portal-card"><h4>${esc(p.student_name||p.student_id)}</h4><p>${esc(p.pickup_name)} · ${esc(p.relationship)} · ${esc(p.authorization_method)}</p><p><b>${esc(p.gate_pass||'Pickup pass pending')}</b> · ${esc(p.status)}</p><p>${esc(nowTime(p.created_at))}${p.released_at?' · Released '+esc(nowTime(p.released_at)):''}</p><div class="actions">${p.status==='Waiting approval'?`<button data-pickup-action="release" data-id="${esc(p.id)}">Verify & release child</button><button class="secondary" data-pickup-action="reject" data-id="${esc(p.id)}">Reject</button>`:''}</div></article>`).join('')||'<p class="portal-empty">No child pickup requests yet.</p>'}</div></div>`;
  area.querySelectorAll('[data-gate-form]').forEach(form=>form.onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const body=Object.fromEntries(new FormData(form));body.request_id=crypto.randomUUID();try{await api(form.dataset.gateForm,'POST',body);status('✓ Gate record saved.');rendering=false;await render()}catch(err){status(err.message);b.disabled=false}});
  area.querySelectorAll('[data-visitor-action]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await api('visitor/'+encodeURIComponent(b.dataset.id),'PATCH',{action:b.dataset.visitorAction});status('✓ Visitor status updated.');rendering=false;await render()}catch(err){status(err.message);b.disabled=false}});
  area.querySelectorAll('[data-pickup-action]').forEach(b=>b.onclick=async()=>{if(b.dataset.pickupAction==='release'&&!confirm('Release this child to the verified pickup person?'))return;b.disabled=true;try{await api('pickup/'+encodeURIComponent(b.dataset.id),'PATCH',{action:b.dataset.pickupAction});status('✓ Pickup status updated.');rendering=false;await render()}catch(err){status(err.message);b.disabled=false}});
 }catch(err){area.innerHTML=`<div id="neoVisitorGate" class="portal-error"><h3>Visitor & Gate backend pending</h3><p>${esc(err.message)}</p><p>No browser-only visitor or child-release records are created.</p></div>`;}finally{rendering=false;}
}
function schedule(){clearTimeout(timer);timer=setTimeout(render,0)}
document.addEventListener('click',e=>{if(e.target.closest('#neoWorkspace [data-tab="visitor_gate"]'))schedule()},true);
window.addEventListener('neo:open-tab',e=>{if(e.detail?.tab==='visitor_gate')schedule()});
new MutationObserver(()=>{if(activeTab()==='visitor_gate'&&!root()?.querySelector('#neoVisitorGate'))schedule()}).observe(document.body,{childList:true,subtree:true});
})();
