import { DatabaseSync } from 'node:sqlite';
import { readFileSync, writeFileSync } from 'node:fs';
const source='worker/neo-lead-crm-api-worker-transport-phase1.js';
writeFileSync('worker/transport-qa-worker.mjs',readFileSync(source,'utf8')+'\nexport {transportPortal,transportOperations,sendTransportPush,transportRenewalSweep};\n');
const {transportPortal,transportOperations,sendTransportPush,transportRenewalSweep}=await import('./transport-qa-worker.mjs');
const db=new DatabaseSync(':memory:');
const DB={
 prepare(sql){return {sql,args:[],bind(...args){this.args=args;return this},async first(){return db.prepare(this.sql).get(...this.args)||null},async all(){return {results:db.prepare(this.sql).all(...this.args)}},async run(){const r=db.prepare(this.sql).run(...this.args);return {meta:{changes:r.changes}}}}},
 async batch(stmts){db.exec('BEGIN');try{const out=[];for(const s of stmts)out.push(await s.run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}
};
const env={DB,ADMIN_PASSWORD:'transport-qa-secret'};
const vapidPair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);env.VAPID_PRIVATE_JWK=JSON.stringify(await crypto.subtle.exportKey('jwk',vapidPair.privateKey));
const schoolId='TESTSCHOOL',secret=env.ADMIN_PASSWORD;
const token=async(role,id,version)=>{
 const payload=Buffer.from(JSON.stringify({role,...id,version,exp:Date.now()+3600000})).toString('base64url');
 const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);
 const sig=Buffer.from(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(payload))).toString('base64url');
 return payload+'.'+sig;
};
const schoolToken=await token('school',{school_id:schoolId},'school-hash');
const req=(path,method='GET',body,auth=schoolToken)=>new Request('https://example.test/api/transport/'+path,{method,headers:{Authorization:'Bearer '+auth,'Content-Type':'application/json',Origin:'https://neoschoolindia.com'},...(body?{body:JSON.stringify(body)}:{})});
async function call(path,method,body,auth,ctx){const request=req(path,method,body,auth),url=new URL('https://example.test/api/transport/'+path);const r=await transportOperations(request,env,url,ctx)||await transportPortal(request,env,url);return {status:r.status,body:await r.json()}}
const assert=(c,m)=>{if(!c)throw Error(m)};
db.exec('CREATE TABLE neo_schools(school_id TEXT PRIMARY KEY,name TEXT,city TEXT,owner TEXT,password_hash TEXT,salt TEXT,active INTEGER DEFAULT 1)');
await call('school/routes/'+schoolId);
db.prepare('INSERT INTO neo_schools(school_id,name,city,owner,password_hash,salt) VALUES (?,?,?,?,?,?)').run(schoolId,'Test School','Jagtial','QA','school-hash','salt');
const put=(kind,id,data)=>db.prepare('INSERT INTO neo_portal_records(school_id,kind,id,data) VALUES (?,?,?,?)').run(schoolId,kind,id,JSON.stringify(data));
put('staff','DRIVER01',{name:'Test Driver',status:'Active'});
put('staff','HELPER01',{name:'Test Helper',status:'Active'});
put('classrooms','CLASS001',{name:'LKG A',program:'LKG',academic_year:'2026'});
put('classrooms','CLASS002',{name:'UKG A',program:'UKG',academic_year:'2026'});
put('students','CHILD001',{name:'Child A',program:'LKG',classroom_id:'CLASS001'});
put('students','CHILD002',{name:'Child B',program:'UKG',classroom_id:'CLASS002'});
put('students','CHILD003',{name:'Child C',program:'LKG',classroom_id:'CLASS001'});
db.prepare('INSERT INTO neo_parent_accounts(account_id,school_id,student_id,password_hash,salt) VALUES (?,?,?,?,?)').run('NP-PARENT01',schoolId,'CHILD001','parent-hash','salt');
db.prepare('INSERT INTO neo_parent_accounts(account_id,school_id,student_id,password_hash,salt) VALUES (?,?,?,?,?)').run('NP-PARENT02',schoolId,'CHILD002','parent-hash','salt');
let r=await call('school/vehicles/'+schoolId,'POST',{request_id:'VEHICLE01',registration_no:'TS01AB1234',label:'Bus 1',capacity:2,insurance_expiry:'2027-12-01',pollution_expiry:'2027-12-01',fitness_expiry:'2027-12-01',tax_expiry:'2027-12-01'});assert(r.status===201,'vehicle '+JSON.stringify(r));
const photo='data:image/jpeg;base64,'+Buffer.from([255,216,1,2,255,217]).toString('base64');
r=await call('school/documents/'+schoolId+'/VEHICLE01','POST',{type:'insurance',expiry_date:'2028-01-01',photo});assert(r.status===201,'vehicle document upload '+JSON.stringify(r));const documentId=r.body.id;
r=await call('school/documents/'+schoolId+'?vehicle_id=VEHICLE01');assert(r.status===200&&r.body.documents.length===1&&r.body.documents[0].expiry_date==='2028-01-01','vehicle document list');
r=await call('school/documents/'+schoolId+'/VEHICLE01','POST',{type:'rc',expiry_date:'',photo});assert(r.status===201,'vehicle RC upload');const rcId=r.body.id;
const documentRequest=req('document/'+documentId);const documentImage=await transportOperations(documentRequest,env,new URL(documentRequest.url));assert(documentImage.status===200&&documentImage.headers.get('Content-Type')==='image/jpeg'&&documentImage.headers.get('Access-Control-Allow-Origin')==='https://neoschoolindia.com','authorized document photo permits website origin');
r=await call('school/routes/'+schoolId);assert(r.body.vehicles[0].insurance_expiry==='2028-01-01','document date updates vehicle');
r=await call('school/routes/'+schoolId,'POST',{request_id:'ROUTE001',name:'Route 1',vehicle_id:'VEHICLE01',driver_staff_id:'DRIVER01',attendant_staff_id:'HELPER01',stops:['Market','School'],trip_count:2});assert(r.status===201,'route '+JSON.stringify(r));
r=await call('school/staff-documents/'+schoolId+'/DRIVER01','POST',{type:'aadhaar',expiry_date:'',photo});assert(r.status===201,'optional driver Aadhaar');
r=await call('school/staff-documents/'+schoolId+'/HELPER01','POST',{type:'aadhaar',expiry_date:'',photo});assert(r.status===201,'optional helper Aadhaar');
r=await call('school/staff-documents/'+schoolId+'/HELPER01','POST',{type:'license',expiry_date:'2028-01-01',photo});assert(r.status===400,'helper cannot upload driving licence');
r=await call('school/assignments/'+schoolId,'POST',{request_id:'WRONGCLASS',route_id:'ROUTE001',student_id:'CHILD001',classroom_id:'CLASS002',stop:'Market'});assert(r.status===400,'wrong class');
r=await call('school/assignments/'+schoolId,'POST',{request_id:'ASSIGN001',route_id:'ROUTE001',student_id:'CHILD001',classroom_id:'CLASS001',stop:'Market',run_no:1});assert(r.status===201,'assign '+JSON.stringify(r));
r=await call('school/assignments/'+schoolId,'POST',{request_id:'ASSIGN002',route_id:'ROUTE001',student_id:'CHILD002',classroom_id:'CLASS002',stop:'School',run_no:1});assert(r.status===201,'assign second');
r=await call('school/assignments/'+schoolId,'POST',{request_id:'ASSIGN003',route_id:'ROUTE001',student_id:'CHILD003',classroom_id:'CLASS001',stop:'Market',run_no:2});assert(r.status===201,'second run capacity independent');
r=await call('school/assignments/'+schoolId,'POST',{request_id:'DUPLICATE',route_id:'ROUTE001',student_id:'CHILD001',classroom_id:'CLASS001',stop:'School'});assert(r.status===409,'duplicate child');
r=await call('school/assignments/'+schoolId+'/ASSIGN001','PATCH',{active:false});assert(r.status===403,'locked assignment');
r=await call('school/trips/'+schoolId,'POST',{request_id:'SCHOOLOPS',route_id:'ROUTE001'});assert(r.status===403,'school cannot operate trips');
r=await call('school/access/'+schoolId,'POST',{staff_id:'DRIVER01',role:'Driver',password:'TestDriver1!'});assert(r.status===201,'create transport access '+JSON.stringify(r));const account=r.body.account_id;
r=await call('school/access/'+schoolId,'POST',{staff_id:'HELPER01',role:'Attendant',password:'TestHelper1!'});assert(r.status===201,'create helper access');const helperAccount=r.body.account_id;
r=await call('login','POST',{account_id:helperAccount,password:'TestHelper1!'},'');assert(r.status===200,'helper login');const helper=r.body.token;
r=await call('login','POST',{account_id:account,password:'TestDriver1!'},'');assert(r.status===200,'driver login '+JSON.stringify(r));const driver=r.body.token;
r=await call('driver/me','GET',null,driver);assert(r.status===200&&r.body.routes.length===1&&r.body.students.length===3,'scoped manifest');
r=await call('push/key','GET',null,driver);assert(r.status===200&&r.body.publicKey.length>80,'VAPID public key');
r=await call('push/subscription','POST',{endpoint:'https://fcm.googleapis.com/fcm/send/test-transport'},driver);assert(r.status===200,'driver browser subscription');
r=await call('push/subscription','POST',{endpoint:'http://localhost/private'},driver);assert(r.status===400,'unsafe push endpoint rejected');
const originalFetch=globalThis.fetch;let pushRequest;globalThis.fetch=async(url,options)=>{pushRequest={url,options};return {status:201}};
await sendTransportPush(env,schoolId,'transport',[account]);globalThis.fetch=originalFetch;
assert(pushRequest?.url==='https://fcm.googleapis.com/fcm/send/test-transport'&&pushRequest.options.headers.Authorization.startsWith('vapid t=')&&pushRequest.options.headers.TTL==='120','VAPID push sent to assigned subscription');
const vapidToken=pushRequest.options.headers.Authorization.match(/vapid t=([^,]+)/)?.[1],vapidParts=vapidToken?.split('.');assert(vapidParts?.length===3&&await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},vapidPair.publicKey,Buffer.from(vapidParts[2],'base64url'),new TextEncoder().encode(vapidParts.slice(0,2).join('.'))),'VAPID JWT signature verifies');
r=await call('driver/care','POST',{vehicle_id:'VEHICLE01',type:'Fuel refill',odometer_km:99,litres:10,amount_paise:20000,note:'Fuel invoice',photo},driver);assert(r.status===201,'driver care report '+JSON.stringify(r));const careId=r.body.id;
r=await call('school/care/'+schoolId);assert(r.status===200&&r.body.records.some(c=>c.id===careId),'school sees care report');
r=await call('driver/care/VEHICLE01','GET',null,driver);assert(r.status===200&&r.body.records.some(c=>c.id===careId),'driver sees care history');
r=await call('driver/care','POST',{vehicle_id:'VEHICLE01',type:'Tyre air',odometer_km:null,litres:null,amount_paise:0,note:'Air pressure checked'},driver);assert(r.status===201,'tyre air needs no fuel readings');const airId=r.body.id;
r=await call('driver/care/VEHICLE01','GET',null,driver);assert(r.body.records.some(c=>c.id===airId&&c.type==='Tyre air'&&c.odometer_km===null),'tyre air stores no artificial odometer');
r=await call('driver/care','POST',{vehicle_id:'VEHICLE01',type:'Maintenance',odometer_km:null,litres:null,amount_paise:0,note:'Door latch checked'},driver);assert(r.status===201,'maintenance needs no fuel readings');
const invoiceRequest=req('carephoto/'+careId,'GET',null,driver);const invoice=await transportOperations(invoiceRequest,env,new URL(invoiceRequest.url));assert(invoice.status===200&&invoice.headers.get('Access-Control-Allow-Origin')==='https://neoschoolindia.com','driver invoice image');
r=await call('school/care/'+schoolId+'/'+careId+'/confirm','POST',{paid_to:'Fuel station',payment_mode:'Cash'});assert(r.status===200&&r.body.voucher_no,'school posts transport voucher '+JSON.stringify(r));
assert(db.prepare("SELECT count(*) n FROM neo_portal_records WHERE school_id=? AND kind='daily_accounts' AND id=?").get(schoolId,'FIN_CARE_'+careId).n===1,'transport expense posts once to ledger');
r=await call('school/care/'+schoolId+'/'+careId+'/confirm','POST',{paid_to:'Fuel station',payment_mode:'Cash'});assert(r.status===409,'duplicate transport voucher blocked');
r=await call('driver/documents/VEHICLE01','GET',null,driver);assert(r.status===200&&r.body.documents.length===2&&r.body.documents.some(d=>d.id===rcId),'assigned driver document list includes RC');
r=await call('driver/staff-documents/HELPER01','GET',null,driver);assert(r.status===200&&r.body.documents.some(d=>d.type==='aadhaar'),'driver sees assigned helper documents');
r=await call('driver/start','POST',{route_id:'ROUTE001',direction:'Pickup',run_no:1,fuel_ok:true,tyres_ok:true,condition_ok:true,odometer_km:100,photo},driver);assert(r.status===409&&r.body.error.includes('driving licence'),'trip requires licence');
r=await call('school/staff-documents/'+schoolId+'/DRIVER01','POST',{type:'license',expiry_date:'2028-01-01',photo});assert(r.status===201,'mandatory driver licence upload');const licenceId=r.body.id;
const licenceRequest=req('staff-document/'+licenceId,'GET',null,driver);const licenceImage=await transportOperations(licenceRequest,env,new URL(licenceRequest.url));assert(licenceImage.status===200&&licenceImage.headers.get('Access-Control-Allow-Origin')==='https://neoschoolindia.com','driver can show licence image');
r=await call('driver/staff-documents/DRIVER01','GET',null,helper);assert(r.status===404,'helper cannot browse driver identity documents');
const helperBlockedRequest=req('staff-document/'+licenceId,'GET',null,helper);const helperBlockedImage=await transportOperations(helperBlockedRequest,env,new URL(helperBlockedRequest.url));assert(helperBlockedImage.status===404,'helper cannot fetch driver licence photo');
const driverDocumentRequest=req('document/'+documentId,'GET',null,driver);const driverDocumentImage=await transportOperations(driverDocumentRequest,env,new URL(driverDocumentRequest.url));assert(driverDocumentImage.status===200&&driverDocumentImage.headers.get('Content-Type')==='image/jpeg'&&driverDocumentImage.headers.get('Access-Control-Allow-Origin')==='https://neoschoolindia.com','assigned driver document photo permits website origin');
r=await call('driver/documents/ANOTHER-VEHICLE','GET',null,driver);assert(r.status===404,'unassigned vehicle documents denied');
db.prepare("UPDATE neo_portal_records SET data=json_set(data,'$.active',json('false')) WHERE school_id=? AND kind='transport_routes' AND id=?").run(schoolId,'ROUTE001');
const revokedDocumentRequest=req('document/'+documentId,'GET',null,driver);const revokedDocument=await transportOperations(revokedDocumentRequest,env,new URL(revokedDocumentRequest.url));assert(revokedDocument.status===404,'driver loses photo access after route deactivation');
r=await call('driver/documents/VEHICLE01','GET',null,driver);assert(r.status===404,'driver loses document list after route deactivation');
db.prepare("UPDATE neo_portal_records SET data=json_set(data,'$.active',json('true')) WHERE school_id=? AND kind='transport_routes' AND id=?").run(schoolId,'ROUTE001');
r=await call('school/access/'+schoolId,'POST',{staff_id:'OTHER001',role:'Driver',password:'OtherStaff1!'});assert(r.status===400,'unassigned staff cannot get access');
const firstParent=await token('parent',{account_id:'NP-PARENT01'},'parent-hash'),secondParent=await token('parent',{account_id:'NP-PARENT02'},'parent-hash');
await call('push/subscription','POST',{endpoint:'https://fcm.googleapis.com/fcm/send/school'},schoolToken);
await call('push/subscription','POST',{endpoint:'https://fcm.googleapis.com/fcm/send/parent-one'},firstParent);
await call('push/subscription','POST',{endpoint:'https://fcm.googleapis.com/fcm/send/parent-two'},secondParent);
let sent=[],pending=[];globalThis.fetch=async(url)=>{sent.push(url);return {status:201}};const pushContext={waitUntil(p){pending.push(p)}};const flushPush=async()=>{await Promise.all(pending);pending=[]};
r=await call('driver/start','POST',{route_id:'ROUTE001',direction:'Pickup',run_no:1,fuel_ok:true,tyres_ok:true,condition_ok:true,odometer_km:100,photo},schoolToken);assert(r.status===401,'school cannot start');
r=await call('driver/start','POST',{route_id:'ROUTE001',direction:'Pickup',run_no:1,fuel_ok:true,tyres_ok:true,condition_ok:true,odometer_km:100,photo},driver,pushContext);assert(r.status===201,'driver start '+JSON.stringify(r));const trip=r.body.id;await flushPush();assert(sent.some(x=>x.endsWith('/school'))&&sent.some(x=>x.endsWith('/parent-one'))&&sent.some(x=>x.endsWith('/parent-two')),'trip start pushes school and all parents');sent=[];
const rows=kind=>db.prepare('SELECT data FROM neo_portal_records WHERE school_id=? AND kind=?').all(schoolId,kind).map(x=>JSON.parse(x.data));
assert(rows('notifications').some(x=>x.title==='Transport trip started'&&x.message.includes('100 km')),'school start notification and reading');
assert(rows('transport_alerts').filter(x=>x.trip_id===trip).length===2,'start notifies every child');
r=await call('driver/start','POST',{route_id:'ROUTE001',direction:'Pickup',run_no:2,fuel_ok:true,tyres_ok:true,condition_ok:true,odometer_km:100,photo},driver);assert(r.status===201,'independent second run '+JSON.stringify(r));
r=await call('driver/start','POST',{route_id:'ROUTE001',direction:'Pickup',run_no:1,fuel_ok:true,tyres_ok:true,condition_ok:true,odometer_km:100,photo},driver);assert(r.status===409,'same run duplicate');
r=await call('driver/finish','POST',{trip_id:trip,odometer_km:101,photo},driver);assert(r.status===409,'finish needs child events');
r=await call('driver/event','POST',{trip_id:trip,student_id:'CHILD002',event_type:'Picked up'},driver);assert(r.status===409,'stop order');
r=await call('driver/event','POST',{trip_id:trip,student_id:'CHILD001',event_type:'Picked up'},driver,pushContext);assert(r.status===200,'first child '+JSON.stringify(r));await flushPush();assert(!sent.some(x=>x.endsWith('/parent-one'))&&sent.some(x=>x.endsWith('/parent-two')),'pickup push only to waiting parent');globalThis.fetch=originalFetch;
assert(rows('transport_alerts').filter(x=>x.trip_id===trip&&x.student_id==='CHILD001').length===1,'picked child gets no progress alert');
assert(rows('transport_alerts').filter(x=>x.trip_id===trip&&x.student_id==='CHILD002').length===2,'only waiting child gets progress alert');
r=await call('driver/emergency','POST',{trip_id:trip,type:'Delay',message:'Traffic diversion'},driver);assert(r.status===200,'route emergency');
assert(rows('notifications').some(x=>x.title==='Transport emergency · Delay'&&x.message.includes('Traffic diversion')),'school emergency details');
assert(rows('transport_alerts').filter(x=>x.trip_id===trip&&x.event_type==='Emergency').length===2,'emergency notifies route parents');
r=await call('driver/event','POST',{trip_id:trip,student_id:'CHILD002',event_type:'Absent'},driver);assert(r.status===200,'second child');
assert(rows('transport_alerts').some(x=>x.trip_id===trip&&x.student_id==='CHILD002'&&x.event_type==='Absent'),'absent parent direct alert');
r=await call('driver/finish','POST',{trip_id:trip,odometer_km:102,photo},driver);assert(r.status===200,'finish '+JSON.stringify(r));
assert(rows('notifications').some(x=>x.title==='Vehicle arrived at school'&&x.message.includes('102 km')),'school finish notification and reading');
const imageRequest=req('photo/'+trip+'/finish','GET',null,driver);const image=await transportOperations(imageRequest,env,new URL(imageRequest.url));assert(image.status===200&&image.headers.get('Content-Type')==='image/jpeg','photo retrieval');
const parent=await token('parent',{account_id:'NP-PARENT01'},'parent-hash');
r=await call('push/subscription','POST',{endpoint:'https://fcm.googleapis.com/fcm/send/test-parent'},parent);assert(r.status===200,'parent browser subscription');
assert(db.prepare('SELECT role,subject_id FROM neo_transport_push WHERE endpoint=?').get('https://fcm.googleapis.com/fcm/send/test-parent').subject_id==='NP-PARENT01','push recipient bound to authenticated parent');
const blockedDocumentRequest=req('document/'+documentId,'GET',null,parent);const blockedDocument=await transportOperations(blockedDocumentRequest,env,new URL(blockedDocumentRequest.url));assert(blockedDocument.status===401,'parent cannot view private vehicle document');
r=await call('parent/me','GET',null,parent);assert(r.status===200&&r.body.trips.length===1&&r.body.alerts.length===2&&r.body.alerts.every(x=>x.student_id==='CHILD001'),'child-scoped parent view '+JSON.stringify(r));
r=await call('parent/me?from=2026-01-01&to=2026-01-31','GET',null,parent);assert(r.status===200&&r.body.trips.length===0,'parent period excludes trips outside range');
r=await call('parent/me?from=2026-01-01&to=2026-12-31','GET',null,parent);assert(r.status===400,'parent period range capped');
r=await call('school/routes/'+schoolId+'?from=2026-01-01&to=2026-01-31');assert(r.status===200&&r.body.trips.length===0,'school report fetched by bounded period');
r=await call('school/routes/'+schoolId+'?from=2026-01-01&to=2026-12-31');assert(r.status===400,'school report range capped');
const renewalDate=new Date(Date.parse(new Date(Date.now()+330*60000).toISOString().slice(0,10)+'T00:00:00Z')+30*86400000).toISOString().slice(0,10);
db.prepare("UPDATE neo_portal_records SET data=json_set(data,'$.tax_expiry',?) WHERE school_id=? AND kind='transport_vehicles' AND id=?").run(renewalDate,schoolId,'VEHICLE01');
await transportRenewalSweep(env,null);const noticeCount=db.prepare("SELECT count(*) n FROM neo_portal_records WHERE school_id=? AND kind='notifications' AND json_extract(data,'$.title')='Vehicle tax renewal due'").get(schoolId).n;assert(noticeCount===1,'renewal creates school alert');
await transportRenewalSweep(env,null);assert(db.prepare("SELECT count(*) n FROM neo_portal_records WHERE school_id=? AND kind='notifications' AND json_extract(data,'$.title')='Vehicle tax renewal due'").get(schoolId).n===1,'renewal alert is idempotent');
for(let i=0;i<20;i++)put('transport_vehicles','PERF'+i,{registration_no:'TEST'+i,label:'Vehicle '+i,active:true});
for(let i=0;i<600;i++)put('transport_trips','PERF_TRIP'+i,{date:i%2?'2026-04-12':'2026-05-12',route_id:'PERF_ROUTE'+i,direction:'Pickup',run_no:1,status:'Completed',events:[]});
r=await call('school/routes/'+schoolId+'?from=2026-04-01&to=2026-04-30');assert(r.status===200&&r.body.vehicles.length>=20&&r.body.trips.length===300&&r.body.trips.every(t=>t.date==='2026-04-12'),'20-vehicle monthly report excludes other months');
console.log('Transport smoke: route alerts, restricted documents, care vouchers, push targeting, renewal idempotency and 20-vehicle period report passed.');
